### ISSUE TITLE
Custom image based on Docker 1.12.1 cannot run without --privileged flag

### ISSUE THREAD

**Issue by AgeOfMobile** [aws/aws-codebuild-docker-images#1]
Hi,

I tried to modify to Docker (1.12.1) to build a custom image. When I use this custom image to build my code, the command $(aws ecr get-login) say:

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

It seems that the custom image is not run with --privileged flag as the Official Docker image?

Thanks.

**Comment by subinataws** [comment]
That is correct. Privileged flag is not supported outside of the official Docker image vended by AWS CodeBuild. Providing Docker access in custom containers is on our product roadmap. No ETA yet.

**Comment by vishalkuo** [comment]
I don't think this issue should be closed. Acknowledging an issue is not the same as resolving it, especially if there's a plan to implement it in the future.

**Comment by jvusich** [comment]
@vishalkuo You actually can [enable privileged mode](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectEnvironment.html#CodeBuild-Type-ProjectEnvironment-privilegedMode) for custom containers now!

**Comment by muellerc** [comment]
I still have this issue, which was reported originally. I enabled the privileged mode via the console and use the following simple Dockerfile:  
```
FROM aws/codebuild/docker-1.12.1

RUN apt-get update
```  
where "aws/codebuild/docker-1.12.1" is the Docker image you provide and I build locally.

CodeBuild fails with the following message:  
> [Container] 2017/09/08 16:17:56 Running command $(aws ecr get-login --region eu-central-1)
> Flag --email has been deprecated, will be removed in 1.13.
> Cannot connect to the Docker daemon. Is the docker daemon running on this host?
> [Container] 2017/09/08 16:17:57 Command did not exit successfully $(aws ecr get-login --region eu-central-1) exit status 1  

I think we should reopen this issue.

Thanks in advance for looking into it. Let me know if you need some additional information.

**Comment by awsnitin** [comment]
Did you follow the "Docker in custom image" sample http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html

For Docker in custom images, you'll need to start the docker daemon as part of the buildspec.

**Comment by muellerc** [comment]
Thanks awsnitin,  

I got the following error:  
```
[Container] 2017/09/08 19:27:02 Running command nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
[Container] 2017/09/08 19:27:02 Running command timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
timeout: invalid option -- 't' Try 'timeout --help' for more information.
```  
but by removing the '-t' option, it's working.   
You may could update the page http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html.

**Comment by awsnitin** [comment]
The sample is using alpine base image (docker:dind), I think you were using ubuntu base instead. I'll get the documentation updated to address this.

**Comment by muellerc** [comment]
Great, thanks!

**Comment by TimPietrusky** [comment]
I created https://github.com/awsdocs/aws-codebuild-user-guide/issues/2 to update the documentation regarding the problem when using Ubuntu instead of alpine (remove the `-t` from `timeout`):
