### ISSUE TITLE
How often are the images refreshed?

### ISSUE THREAD

**Issue by rynop** [aws/aws-codebuild-docker-images#104]
I rely on the aws-cli in my codebuild, so knowing how often this is updated is important to me.

Specifically, I care about https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/ubuntu-base/14.04

Do you only update the docker image:
1.  when you have changes to a `Dockerfile`
1.  when an OS security fix is released
1.  when aws-cli version is bumped
1.  at a certain cadence (monthly)
1.  combination of the above / something totally different?

Lastly, including a last updated time at https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html would be wonderful...

thanks in advance.

**Comment by Kaixiang-AWS** [comment]
The answer is 5. combination of the above.

Also, thank you for the request on "last updated time", I have passed it to the team for further review. Your feedback is very much appreciated.

**Comment by rynop** [comment]
appreciate the quick response. look forward to the increased transparency.  Feel free to close or keep open for your team to track.
