### ISSUE TITLE
Gradle update and sonar-runner

### ISSUE THREAD

**Issue by mavriksc** [aws/aws-codebuild-docker-images#106]
[commit and file](https://github.com/aws/aws-codebuild-docker-images/commit/2bd76551e48a2bc597ce498503cca9241264bec8#diff-24702f2ecc261f591ff3505eee543a4f)
This update breaks use of old plugins. So while i don't think it should be fixed. maybe you can put info somewhere to make it easy for people to update their stacks...

1. comment out all sonar-runner components( or other broken plugins). Like ` apply plugin sonar-runner` and the config of the plugin later in the file.
2. run `gradle wrapper --gradle-version {required version}` from the project directory.
un-comment items from Step #1 and commit all created files( /gradle folder and gradlew and gradlew.bat)
3. in buildspec.yml, under build.commands add `- chmod +x gradlew`  before the `gradle` command, and change build line from `- gradle ...` to  `- ./gradlew ...`

**Comment by subinataws** [comment]
Thanks for pointing that out. We'll consider adding this to CodeBuild's user guide under troubleshooting section @ https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html.

Marking it resolved here.
