### ISSUE TITLE
Is there pre-built aws codebuild docker images on docker hub

### ISSUE THREAD

**Issue by 199911** [aws/aws-codebuild-docker-images#11]
As topic

**Comment by johnhanks1** [comment]
The AWSCodeBuild curated images are only prebuilt and available when running a build on AWSCodeBuild. Currently they aren't hosted on any other platform.

**Comment by omeid** [comment]
I think there is a lot of value for pushing these images to some sort of public repository, it makes debugging and writing up builds much easier than having to build these images locally every time one needs newer/different images.
