### ISSUE TITLE
running with aws-sam-cli via docker in docker?

### ISSUE THREAD

**Issue by AlJohri** [aws/aws-codebuild-docker-images#110]
is there any guide on how to use this with aws-sam-cli? I'm looking to build my app directly using the buildspec.yml and then run it via aws-sam-cli

currently I need to duplicate the code in my buildspec into a shell script and run it locally prior to running the `sam`

thanks!

related:
- https://github.com/awslabs/aws-sam-cli/issues/181#issuecomment-417885580
- https://github.com/aws/aws-codebuild-docker-images/issues/76

**Comment by subinataws** [comment]
There is no guide to use CodeBuild local with sam-cli. SAM CLI repo is tracking this feature in https://github.com/awslabs/aws-sam-cli/issues/402. Please feel free to provide your use case and upvote to help them prioritize.

Marking this resolved as the feature request can be tracked in sam-cli repo.
