### ISSUE TITLE
post language images to dockerhub?

### ISSUE THREAD

**Issue by AlJohri** [aws/aws-codebuild-docker-images#111]
hi, I'm a little confused by the process for using this repo.

why do I need to first clone and build/tag an image like so: `docker build . -t aws/codebuild/python:3.6.5`. why not just host this image on dockerhub directly for download?

that way when running the `./codebuild_build.sh` script I can specify the `IMAGE_NAME=aws/codebuild/python:3.6.5` directly and use it out of the box?

thanks!

**Comment by subinataws** [comment]
Good call-out. Current images are hosted in ECR and won't be made available in DockerHub.

These Dockerfiles are made available as a reference, since our images themselves aren't available for download directly for our customers.

**Comment by AlJohri** [comment]
I think it might be worth mentioning `codebuild_build.sh` in the main README. It took me some time to figure out how all the pieces fit together. For my use case, and I imagine for most, this script was the main entry point.

In addition, I imagine it should be easy to make the script build the image for me reducing that first step

thanks for the response!
