### ISSUE TITLE
Support for Go 1.11

### ISSUE THREAD

**Issue by jason-riddle** [aws/aws-codebuild-docker-images#112]
Go 1.11 was recently released a little over a week ago. Included in that release is native support for Modules without the need of using `vgo`. Are there plans to add this version as a codebuild image?

**Comment by subinataws** [comment]
If it is a major release, which it appears to be, we'll add that. However, we can't provide an ETA on it. Feel free to use a custom image for Go 1.11 in the meantime.

**Comment by subinataws** [comment]
Added this support in https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.7.0.0
