### ISSUE TITLE
Local build log not shown

### ISSUE THREAD

**Issue by roening** [aws/aws-codebuild-docker-images#114]
Hello,

Sometime when I run the local build no output is showed. The only output is the bellow:

```
Removing agentresources_build_1 ... done
Removing agentresources_agent_1 ... done
Removing network agentresources_default
Removing volume agentresources_user_volume
Removing volume agentresources_source_volume
Creating network "agentresources_default" with the default driver
Creating volume "agentresources_user_volume" with local driver
Creating volume "agentresources_source_volume" with local driver
Creating agentresources_agent_1 ... 
Creating agentresources_agent_1 ... done
Creating agentresources_build_1 ... 
Creating agentresources_build_1 ... done
Attaching to agentresources_agent_1, agentresources_build_1
agentresources_build_1 exited with code 0
Aborting on container exit...
```

Did someone already see this?

Thanks!

**Comment by gemmadlou** [comment]
+1

**Comment by john-mcgowan-wowza** [comment]
I'm trying out locally running codebuild today for the first time and I'm seeing the same behavior. 

Since this is the first time I'm attempting it, I couldn't tell whether or not this was normal.  I have a simple hello world buildspec that just echo's something and I don't see anything.

**Comment by awszhen** [comment]
@roening @gemmadlou @john-mcgowan-wowza, thanks for letting us know about this. Could you please provide us the detailed steps to reproduce this issue?

**Comment by john-mcgowan-wowza** [comment]
@awszhen 

My steps were simple, I followed both of these articles...

https://aws.amazon.com/blogs/devops/announcing-local-build-support-for-aws-codebuild/

https://docs.aws.amazon.com/codebuild/latest/userguide/use-codebuild-agent.html

The only difference is that I was just trying to use the basic ubuntu image and I also tried using my own codebuild docker image that was based off of the basic ubuntu image (with some additional tools installed)

I got the same results in each case.  I'm running this on my OSX machine with 
Docker version 18.03.0-ce, build 0520e24.

**Comment by john-mcgowan-wowza** [comment]
I was able to get it working today after doing the following.

1) Restarted docker on my machine

2) Upgraded Docker on my machine

3) made sure that my artifacts directory was not beneath where the source directory was.

I was eventually able to get a local build to run with my echo "Hello world" command appearing on the console.  But then I go to run the exact same command shortly after that and it doesn't work.

I get this and it just hangs...

```
Creating agentresources_build_1 ... done
Attaching to agentresources_agent_1, agentresources_build_1
agent_1  | time="2018-09-21T23:52:11Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=eefd5d46-516a-43f3-8941-30d8069b3121 version=v2.6.2
agent_1  | time="2018-09-21T23:52:11Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=eefd5d46-516a-43f3-8941-30d8069b3121 version=v2.6.2
agent_1  | time="2018-09-21T23:52:11Z" level=info msg="Starting upload purge in 39m0s" go.version=go1.7.6 instance.id=eefd5d46-516a-43f3-8941-30d8069b3121 version=v2.6.2
agent_1  | time="2018-09-21T23:52:11Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.6 instance.id=eefd5d46-516a-43f3-8941-30d8069b3121 version=v2.6.2
agent_1  | time="2018-09-21T23:52:11Z" level=info msg="listening on [::]:5000" go.version=go1.7.6 instance.id=eefd5d46-516a-43f3-8941-30d8069b3121 version=v2.6.2
```

**Comment by john-mcgowan-wowza** [comment]
> I get this and it just hangs...

Yeah, I'm in a state now where I'm getting it to run once or twice and then when I run it it hangs on the output i shared above.  And a restart of docker on my mac, seems to allow me to run it again after the restart.

I suppose I'm going to have to open up another ticket because now my problem is nothing like what the OP reported.

**Comment by john-mcgowan-wowza** [comment]
@awszhen I raised another issue to capture the stuff that I was running into.

https://github.com/aws/aws-codebuild-docker-images/issues/120

**Comment by awszhen** [comment]
Hi, please use the latest version of the local agent. SHA: 17230d017b97ea06054b93209230943add0c2bc3b888ab565dbbd9368f77bacc

**Comment by subinataws** [comment]
Marking this resolved. @john-mcgowan-wowza @gemmadlou @roening - Please chime in if this issue still persists.
