### ISSUE TITLE
Failed to build image aws-codebuild-docker-images/ubuntu/docker/1.12.1

### ISSUE THREAD

**Issue by danielmaxx** [aws/aws-codebuild-docker-images#115]
When running `docker build -t aws/codebuild/docker:1.12.1 .`, it fails with the following message:

```
E: Version '5.5.59-*' for 'libmysqlclient-dev' was not found
E: Version '9.3.20-*' for 'libpq-dev' was not found
```

I've changed the versions to 5.5.* and 9.3.20.* respectively but I don't know if that's the right value you should have. It works for me tho.

**Comment by subinataws** [comment]
Thanks for reporting it. However, we are only maintaining the images listed in https://github.com/aws/aws-codebuild-docker-images#image-maintenance.
