### ISSUE TITLE
Update Node.js 10.x to the latest 10.10.0 Node.js

### ISSUE THREAD

**Issue by XhmikosR** [aws/aws-codebuild-docker-images#117]
There's a bug in earlier versions, see https://github.com/nodejs/node/issues/20498, so out of the box many people will hit this.

**Comment by rgant** [comment]
I too would like to use a more up to date node and npm. I would really like `npm ci` support.

**Comment by subinataws** [comment]
Thanks for the feature request. We'll add this support in a future release.

**Comment by subinataws** [comment]
Added this support in https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.7.0.0
