### ISSUE TITLE
When might we see an ubuntu 16.04 image?

### ISSUE THREAD

**Issue by chriskinsman** [aws/aws-codebuild-docker-images#12]
Thanks!

**Comment by subinataws** [comment]
We don't have an ETA to share. CodeBuild does support bringing your own Docker images. More information:  http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html

**Comment by kevbook** [comment]
The example in the link always results in
 ``` 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by subinataws** [comment]
@kevbook Did you enable the priviledged flag for your project? You can find this setting under the "Advanced" section of your CodeBuild console/UI.

**Comment by kevbook** [comment]
I did. See screenshot
https://d26dzxoao6i3hh.cloudfront.net/items/1r1K1j2w1l2k3o2K1C3g/Screen%20Shot%20104.png?v=b4d21596

**Comment by dhilsand** [comment]
It looks like docker daemon didn't start. Did you run the following in your build?

```
nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
```

**Comment by kevbook** [comment]
Thanks, it worked. 
I had to use `--storage-driver=vfs`

**Comment by ivan-pinatti** [comment]
I have just dropped a PR for the Ubuntu 16.04 image, enjoy! :)

**Comment by ffxsam** [comment]
...with Node.js v8 would be even better.

**Comment by ivan-pinatti** [comment]
Hi @ffxsam,

In this case I think a fork from the image that I made, adding the Node.js, would be the way to go. Then it would fall under the Node.js category.

**Comment by ffxsam** [comment]
@ivan-pinatti I saw your PR but have no idea what to do with it. How do I set this up with my repo so that it uses this + Node.js v8 for testing & building?

**Comment by ivan-pinatti** [comment]
@ffxsam, you could use the Ubuntu image that I created as a FROM in your to be created Dockerfile and then add the Node.JS in the following layers.

I recommended to fork my branch just because it would be more organized when people from AWS would review and approve the PRs. The problem is, until now I did not see any interaction from them and there is another image PR that is open since May 2017.

@clareliguori, could you please shed some light on it for us?
I opened the PRs #27 and #28 almost a month ago and see no interaction from AWS side yet.

**Comment by ffxsam** [comment]
I see your Dockerfile but I have no idea where to put it or how to make my CodeBuild project use it.

Do I need to use the Docker-in-Docker (`docker:dind`) image as described here? https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html

**Comment by ivan-pinatti** [comment]
@ffxsam nope.

Take a look in the another PR where I added Docker on top of the Ubuntu base image. You will have to do similar to it for the Node.Js.

https://github.com/aws/aws-codebuild-docker-images/pull/28/commits/9ab7bed7afc88cffffb3db9ea59a6ccfb757e882

**Comment by ffxsam** [comment]
Sorry for being dense. I have absolutely zero clue what to do with that Dockerfile in order to have it install Node v8, _and_ get that image into CodeBuild.

**Comment by ivan-pinatti** [comment]
@ffxsam unfortunately there is no manual on how to get the image into CodeBuild, however, you can create your own image, host it at Docker Hub and select it on AWS CodeBuild.

Here is how:
[https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html)

**Comment by ffxsam** [comment]
Ah, gotcha. Yes, this is what I mentioned [above](https://github.com/aws/aws-codebuild-docker-images/issues/12#issuecomment-367919440), using `docker:dind` with CodeBuild to use a custom image.

**Comment by clareliguori** [comment]
Hi @ivan-pinatti, we still do not have an ETA to share for adding official CodeBuild images based on Ubuntu 16.04.

**Comment by ivan-pinatti** [comment]
Hi @clareliguori,

I already did the PR #27 for it, are you going to review it OR to develop one image by your own? What is the game plan?

**Comment by clareliguori** [comment]
@ivan-pinatti I apologize for the long idle time on your PR.  For major changes like a new Ubuntu version, we would likely develop an image (or set of images) in our internal repo first, and then go through our internal image release process.  Your PR gives us a great headstart though.

**Comment by ivan-pinatti** [comment]
Thanks for clarifing it @clareliguori, I hope I have helped. :)

**Comment by chadbrewbaker** [comment]
@clareliguori Sagemaker team has one bumped to 16.04.  

https://github.com/aws/sagemaker-tensorflow-containers/blob/master/docker/1.6.0/base/Dockerfile.cpu

**Comment by XhmikosR** [comment]
This is definitely an important issue. Node.js from [nodesource](https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions) does not support 14.04 for 10.x so it falls back to Node.js v10.1.0 which is very old and has a lot of bugs.

**Comment by johannes-gehrs** [comment]
14.04 will be EoL in April 2019. Please consider working on this soon.

**Comment by subinataws** [comment]
We won't be providing an Ubuntu 16.04 image, instead we'll plan on supporting Ubuntu 18.04 LTS before 14.04.5 is EOL.

**Comment by subinataws** [comment]
https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/1.0/Dockerfile. This will be available to select on CodeBuild's APIs and console/UI in the next few days.
