### ISSUE TITLE
Local CodeBuild fails to run properly (Unless you restart docker service on host)

### ISSUE THREAD

**Issue by john-mcgowan-wowza** [aws/aws-codebuild-docker-images#120]
I've run into a problem with running the local CodeBuild system.   Here are the symptoms that I had first.

Once I got everything all figured out and ran my first local "hello world" buildspec.yml in a project I was quickly confused, beacuse the second time I tried to run it (with everything being identical) it failed.   

One thing that was interesting was that the output I saw was totally different with the failed runs.  For example, this is what a snippet of the output looks like for a successful run.    

```
Creating agentresources_agent_1 ...
Creating agentresources_agent_1 ... done
Creating agentresources_build_1 ...
Creating agentresources_build_1 ... done
Attaching to agentresources_agent_1, agentresources_build_1
agent_1  | [Container] 2018/09/25 17:19:06 Waiting for agent ping
agent_1  | [Container] 2018/09/25 17:19:07 Waiting for DOWNLOAD_SOURCE
agent_1  | [Container] 2018/09/25 17:19:07 Phase is DOWNLOAD_SOURCE
agent_1  | [Container] 2018/09/25 17:19:07 CODEBUILD_SRC_DIR=/codebuild/output/src243631663/src
agent_1  | [Container] 2018/09/25 17:19:07 YAML location is /codebuild/output/src243631663/src/local-buildspec.yml
agent_1  | [Container] 2018/09/25 17:19:07 Processing environment variables
agent_1  | [Container] 2018/09/25 17:19:07 Moving to directory /codebuild/output/src243631663/src
agent_1  | [Container] 2018/09/25 17:19:07 Registering with agent
```

But when It's unsuccessful we see this...

```
Creating agentresources_agent_1 ...
Creating agentresources_agent_1 ... done
Creating agentresources_build_1 ...
Creating agentresources_build_1 ... done
Attaching to agentresources_agent_1, agentresources_build_1
agent_1  | time="2018-09-25T17:19:23Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=cfcd4f02-a786-42a7-8986-7bbe7bdf1c75 version=v2.6.2
agent_1  | time="2018-09-25T17:19:23Z" level=info msg="Starting upload purge in 24m0s" go.version=go1.7.6 instance.id=cfcd4f02-a786-42a7-8986-7bbe7bdf1c75 version=v2.6.2
agent_1  | time="2018-09-25T17:19:23Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=cfcd4f02-a786-42a7-8986-7bbe7bdf1c75 version=v2.6.2
```

Now, it took me a little bit to figure this out, because I'm new to docker, but the agent_1 output that you see in the second (failed) example is actually the output form a `registry` container running.   The second "failed" attempt will basically just sit there running the registry until i CTRL-C out of it.

So I did some experimentation and started up the `amazon/aws-codebuild-local` container with an overridden entrypoint.  Whenever I would override the local_build.sh entry point with /bin/bash and manually run local_build.sh it would work fine. 

So then I decided to create my own image that inherited from `amazon/aws-codebuild-local` and introduce an artificial delay of 1 second before running the local_build.sh entrypoint script.

`Dockerfile`

```
FROM amazon/aws-codebuild-local:latest
COPY slow_your_roll.sh /usr/local/bin/slow_your_roll.sh
RUN chmod a+x /usr/local/bin/slow_your_roll.sh
ENTRYPOINT /usr/local/bin/slow_your_roll.sh
```

`slow_your_roll.sh`

```
#!/bin/bash
echo "Lets wait a bit"
sleep 1
echo "Do the local build"
local_build.sh
```

Every time I ran a test with this container with the 1s sleep it worked fine.

So from what I can tell (at least in my environment)  Is that the aws-codebuild-local container must attempt to work with docker before it's ready, and when it does so, it fails to run the CodeBuild process.

I think the solution might be that the local_build.sh entrypoint needs to have some logic to make sure the host docker environment is ready to be used before going forward?

**Comment by subinataws** [comment]
Thanks for reporting the issue. Could you confirm that you are using the latest version from DockerHub?

**Comment by john-mcgowan-wowza** [comment]
@subinataws Yes, in fact I just did another docker pull just now and reproduced the problem again.  I had probably last pulled a day ago or so before posting this issue.

**Comment by john-mcgowan-wowza** [comment]
Has anybody looked into this issue yet?  I'd prefer to not have to keep around my workaround for this.  I've expanded quite a bit of tooling around the local CodeBuild workflow.

**Comment by ksaito1125** [comment]
The following code specifies AGENT_ID.

```
$ docker run -it --rm --entrypoint bash amazon/aws-codebuild-local 
bash-4.2# grep AGENT_ID `type -p local_build.sh`
    AGENT_ID=$(docker ps | sed -n 2p | cut -c 1-12)
    while [[ -z ${AGENT_ID} ]]; do
            AGENT_ID=$(docker ps | sed -n 2p | cut -c 1-12)
    export LOCAL_AGENT_IMAGE=$(docker inspect --format='{{.Config.Image}}' ${AGENT_ID})
bash-4.2
```

If more than one container is running in a local docker environment, will the following code always correctly identify AGENT_ID?

```
    AGENT_ID=$(docker ps | sed -n 2p | cut -c 1-12)
```

**Comment by awszhen** [comment]
Hi @john-mcgowan-wowza , @ksaito1125 , please use the latest version of the local agent. SHA: 17230d017b97ea06054b93209230943add0c2bc3b888ab565dbbd9368f77bacc

**Comment by subinataws** [comment]
Marking this resolved. @john-mcgowan-wowza, @ksaito1125 - Please chime in if this issue still persists on your end.

**Comment by john-mcgowan-wowza** [comment]
@subinataws Is there a PR that was intended to fix this issue?  I don't see it linked or anything here.  My "add one second of delay" workaround fixed the problem, so I'd be interesting in seeing what the real soltuion to the problem is.

**Comment by subinataws** [comment]
@john-mcgowan-wowza - Update is in the Docker image, so no PR to reference. Can you give it a try without the 1 sec. delay script to confirm this works for you?

**Comment by john-mcgowan-wowza** [comment]
Thanks @subinataws .  Just to clarify.  You said the update was in "the Docker image" by that do you mean the docker container referenced by the codebuild job.  I have my own imaged based off of the ones that you provided, so I will probably need to pull changes down from that one as well.  I'll probably be able to test this in the next few days.
