### ISSUE TITLE
Unable to set environment variables for local builds

### ISSUE THREAD

**Issue by ilyabezdelev** [aws/aws-codebuild-docker-images#121]
Hi,

I am unable to make python 3.6.5 docker image to accept my environment variables either from a file or by using a command line `-e` argument.

Here's what I did:
* Created a sample Python Lambda project with AWS CodeStar
* Followed instructions in [this article](https://aws.amazon.com/blogs/devops/announcing-local-build-support-for-aws-codebuild/)
* Commented out `COPY dockerd-entrypoint.sh /usr/local/bin/` in `Dockerfile` for python 3.6.5
* Built a docker image for `python3.6.5` with `docker build -t aws/codebuild/python365 .`
* Created `vars.env` file in my source directory
* Run the following command to run the build locally: `codebuild_build.sh -i aws/codebuild/python365 -a ../codebuild_artifacts -e vars.env -c`
* Docker runs all the commands just fine but fails on those that use environment variables. The following output from Docker indicates it wasn't able to use the vars.env file: `2018/09/26 05:15:02 [Environment Variables] Couldn't open specified environment variable file: open /LocalBuild/envFile/vars.env: no such file or directory`
* I tried supplying environment variables using the command line by taking the `docker run` command output by `codebuild_build.sh` and adding another variable with `-e "S3_BUCKET=bucket_name"` but to no avail. The variable is not available in the container and the CloudFormation command that uses $S3_BUCKET fails to execute.
* I added `printenv` to the install stage and it doesn't show `S3_BUCKET` in the list of environment variables
* When I add `export S3_BUCKET=bucket_name` to the install stage, it works like magic, indicating there's nothing wrong with the buildspec.yml file.

Can someone help troubleshoot this?

Thanks!

**Comment by subinataws** [comment]
@ilyabezdelev - we need to get that blog post updated. However, please follow the instructions on https://github.com/aws/aws-codebuild-docker-images/blob/master/local_builds/README.md to set the environment variables.

**Comment by subinataws** [comment]
Thanks, @ilyabezdelev. Merged your PR.
