### ISSUE TITLE
core 2.1 - command not found for dotnet

### ISSUE THREAD

**Issue by michelmob** [aws/aws-codebuild-docker-images#127]
The .net core version 2.1 container is working but the command "dotnet" is not  working.

**Comment by michelmob** [comment]
@johnhanks1  I downloaded this version https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.4.0 and is working.

Thanks.

**Comment by subinataws** [comment]
@michelmob - good to hear that. Marking this resolved.
