### ISSUE TITLE
Is an updated image for .NET Core 2.0 planned?

### ISSUE THREAD

**Issue by BarryDahlberg** [aws/aws-codebuild-docker-images#13]
The original .NET image is working nicely for me but I'd like to upgrade soon if possible.

**Comment by subinataws** [comment]
It is on our backlog. However, there's no ETA to share right now. 

CodeBuild does support bringing your own Docker images. That's an option to consider in the short term.

**Comment by BarryDahlberg** [comment]
OK, thanks. I have it working with a custom Docker image for now.

**Comment by awsnitin** [comment]
.NET Core 2.0 image is available now. 
https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/dot-net/core-2

Closing this thread.
