### ISSUE TITLE
Support for Alpine Images

### ISSUE THREAD

**Issue by vibhuyadav** [aws/aws-codebuild-docker-images#131]
Alpine is great for small images sizes. I like keeping my docker images as slim as possible and it also minimizes any security loopholes and vulnerabilities?
Was wondering what the thoughts are currently on supporting this in future?

**Comment by subinataws** [comment]
Currently, we don't have plans to expand beyond Ubuntu and Amazon Linux (in a future release of these images). In the fullness of time, AL will be the base images of all CodeBuild managed images.
