### ISSUE TITLE
EKS optimized CodeBuild images

### ISSUE THREAD

**Issue by rnzsgh** [aws/aws-codebuild-docker-images#132]
It would be great to have an EKS optimized CodeBuild image (complete with Docker) so that you can avoid things like the following in your buildspec.yml

https://github.com/rnzsgh/eks-workshop-sample-api-service-go/blob/master/buildspec.yml

      - mkdir bin
      - curl -sS -o bin/aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o bin/kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/kubectl
      - chmod +x ./bin/kubectl ./bin/aws-iam-authenticator
      - export PATH=$PWD/bin:$PATH

**Comment by subinataws** [comment]
https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/1.0/Dockerfile. This will be available to select on CodeBuild's APIs and console/UI in the next few days.

**Comment by jfdoube** [comment]
Need Kubectl 1.15. Is it possible to include this version ?
