### ISSUE TITLE
Unable to locate package php5-mysql

### ISSUE THREAD

**Issue by konstantinvlasenko** [aws/aws-codebuild-docker-images#136]
Hi,

This is my **buildspec.yml**

> version: 0.1
> phases:
>   install:
>     commands:
>       - apt-get install -y php5-mysql
>       - composer install
>   pre_build:
>     commands:
>       - php -m
>   build:
>     commands:
>       - vendor/bin/phinx migrate

CodeBuild image https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/php/5.6/Dockerfile

Getting this error:  _**Unable to locate package php5-mysql**_ while executing install commands.

Any help appreciated.

**Comment by subinataws** [comment]
Could you please try an "apt-get update" before "apt-get install ..". Also please change the buildspec version number to 0.2. The 0.1 buildspec version while not deprecated, shouldn't really be used.
