### ISSUE TITLE
Provide a Java Open JDK 11 image.

### ISSUE THREAD

**Issue by davidmelia** [aws/aws-codebuild-docker-images#138]
Hi,

Now Java 11 is officially released could you provide an Open JDK 11 image?

Thanks

**Comment by rhanton** [comment]
Seconded.

**Comment by t04glovern** [comment]
I've open a PR #140 with a working solution to this. Keen for feedback from others to validate it works for your workflows.

**Comment by teimatinimarin** [comment]
+1

**Comment by subinataws** [comment]
Thanks for the feature request. We'll add support for openjdk:11.

**Comment by johnhanks1** [comment]
This is now available on our console. Thanks for the contribution.

https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.7.0.0
