### ISSUE TITLE
Upgrade docker image with python3

### ISSUE THREAD

**Issue by kaitea** [aws/aws-codebuild-docker-images#141]
Hi,

Are there plans to update the following Docker build image with python3?

        aws-codebuild-docker-images/ubuntu/docker/17.09.0/Dockerfile

Thank you.

**Comment by subinataws** [comment]
If you need python 3 (we only have 3.6.x as the latest), you can use aws/codebuild/python:3.6.5. You can enable the "privileged" flag for your build project that uses this image to get the same Docker access inside the container like aws-codebuild-docker-images/ubuntu/docker/17.09.0/Dockerfile
