### ISSUE TITLE
.NET core 2.1.5

### ISSUE THREAD

**Issue by gsaadeh** [aws/aws-codebuild-docker-images#146]
Lambda now supports .NET core version 2.1.5 while the sdk in the docker image is still 2.1.4. Can you please update the image version?

ENV DOTNET_SDK_VERSION 2.1.402 -> 2.1.403

Thanks,

George

**Comment by subinataws** [comment]
Thanks for the feature request. We'll add this support in a future release.

**Comment by subinataws** [comment]
Added this support in https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.7.0.0
