### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by TMiguelT** [aws/aws-codebuild-docker-images#149]
I notice that the latest Python 3 image is 3.6. Could a 3.7 image be created?

**Comment by subinataws** [comment]
Thanks for the feature request. We'll add this support in a future release.

**Comment by johnhanks1** [comment]
Released 3.7. This is now available in all Regions on the AWSCodeBuild Console. 

https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.7.0.0
