### ISSUE TITLE
docker-compose not installed in these images

### ISSUE THREAD

**Issue by tobowers** [aws/aws-codebuild-docker-images#15]
I think there's a difference between what's actually running in code-deploy and this docker image. In Code Deploy I use `docker-compose` but when running locally (after building) there is no docker-compose installed here: https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/docker/1.12.1

**Comment by clareliguori** [comment]
Thanks for reporting this!  We now have Docker compose 1.16.1 installed on both the Docker 1.12 and 17 environments (see c04b21f5b386b60c7467043554a4a0780fe5828b)
