### ISSUE TITLE
[Bug] The live dot-net:core-2.1 managed image is out of sync with code tagged as release 1.7.0.0

### ISSUE THREAD

**Issue by janaka** [aws/aws-codebuild-docker-images#155]
The releases tab indicates that 1.7.0.0 has been released. The .NET Core 2.1 Docker file in this release should have the latest version of Mono. But the live image contains an older version of Mono indicating that this image didn't actually get rolled out with the 1.7.0.0. release/. 

https://github.com/aws/aws-codebuild-docker-images/blob/1.7.0.0/ubuntu/dot-net/core-2.1/Dockerfile

managed image name: `aws/codebuild/dot-net:core-2.1`

On CodeBuild cloud:
`Mono --version` 
Output:
```
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1) Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com TLS: __thread SIGSEGV: altstack Notifications: epoll Architecture: amd64 Disabled: none Misc: softdebug LLVM: supported, not enabled. 
```

Building image locally and running build agent locally:
`Mono --version` 
Output:
```
agent_1  | Mono JIT compiler version 5.18.0.225 (tarball Fri Dec 21 19:40:20 UTC 2018) Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com TLS: __thread SIGSEGV: altstack Notifications: epoll Architecture: amd64 Disabled: none Misc: softdebug Interpreter: yes LLVM: yes(600) Suspend: preemptive GC: sgen (concurrent by default)
```

**Comment by janaka** [comment]
Also in the CodeBuild UI it lists image version 1.6.0 although there is no release 1.6.0.0 in the repo or a tag. This is true for the few runtimes I checked like .NET, Java, Android, and Golang.

This is also the latest explicit version that can be picked. Is that an indication that this is also the latest runtime version available live?

**Comment by janaka** [comment]
I've tried choosing both `Always use the latest image for this runtime version` and `aws/codebuild/dot-net:core-2.1-1.6.0`

**Comment by jarroda** [comment]
Just ran into this issue, and I can confirm what Janaka is seeing.  Any movement on this?

**Comment by subinataws** [comment]
@janaka @jarroda - Latest updates for CodeBuild Dockerfiles will be limited to the supported version: https://github.com/aws/aws-codebuild-docker-images#image-maintenance.

CodeBuild's Ubuntu 18.04 based images have latest .NET core available on them: https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/1.0/Dockerfile#L21

You can choose this managed image as "aws/codebuild/standard" on AWS CodeBuild. Let me know if this doesn't work for your use case.
