### ISSUE TITLE
[Feature Request] Add npm into .NET Core docker package

### ISSUE THREAD

**Issue by tonycam14** [aws/aws-codebuild-docker-images#156]
would it be possible to get npm included on the docker image for .net core as alot of projects use angular and react now? It would be handy to save a step.

**Comment by vibhuyadav** [comment]
Even I am installing nodejs on .NET image for the exact reason

**Comment by subinataws** [comment]
https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/1.0/Dockerfile. This will be available to select on CodeBuild's APIs and console/UI in the next few days.
