### ISSUE TITLE
Using secure parameters from parameter store

### ISSUE THREAD

**Issue by lockenj** [aws/aws-codebuild-docker-images#159]
I followed the instructions [here](https://aws.amazon.com/blogs/devops/announcing-local-build-support-for-aws-codebuild/) with the exception of using a custom build image.

My buildspec has `parameter-store` references, when I run it via the `codebuild_build.sh` I get the below error.

`Phase context status code: Decrypted Variables Error Message: parameter does not exist: coin-cobo-srfr-slack-incoming-web-hook`

using `aws ssm get-parameter --name coin-cobo-srfr-slack-incoming-web-hook --with-decryption` from my local host machine it works fine. Any thoughts?

**Comment by awszhen** [comment]
Hi @lockenj , would you please check whether you have passed the correct aws credentials to the local agent?

**Comment by lockenj** [comment]
@awszhen thanks for the quick response. I am using the -c flag and I can verify that I can use the aws cli which pulls from the same ~/.aws/credentials file....

Is there another way I can test this?

**Comment by awszhen** [comment]
@lockenj Did you override the `AWS_REGION` environment variable? Could you please echo the `AWS_REGION` environment variable to see whether it is the same as the value in `~/.aws/config`?

**Comment by lockenj** [comment]
I did not. Where should I do the echo, in the buildspec.yml? I can confirm the shell I am executing the codebuild_build.sh in does not have any AWS_* variables set

**Comment by awszhen** [comment]
Yes, `echo` in the `buildspec.yml` file.

**Comment by djmrr** [comment]
Is there a way to specify a given profile, like as aws cli accepts, like "--profile MyProfile"?

**Comment by jeshan** [comment]
I solved it by running the script as follows:
```
AWS_REGION=us-east-1 ./codebuild_build.sh -i aws/codebuild/docker:18.09.0 -a dist/codebuild-artefacts -c ~/.aws
```

So, it seems that it's the build script that needs the env var.

**Comment by awszhen** [comment]
@lockenj , we could not reproduce this issue on our end.

**Comment by abhi-dev91** [comment]
I was also getting the same issue, even my parameters and pipeline is in the same region.

**Comment by abhi-dev91** [comment]
I went through the issue and found that when I define the parameter in the parameter store, I have added the "/" at the end of the parameter due to which it is not working, now it worked.
