### ISSUE TITLE
How to get/install python 3.6,zip, Pip in a docker image? 

### ISSUE THREAD

**Issue by panyi121** [aws/aws-codebuild-docker-images#16]
I want to use Python3.6, zip, pip command to install dependency libraries and update Lambda Function in a CodeBuild project. 

I tried with 2 options:
1. Use python 3.5.2 docker image,  but it cannot install zip. Error message: Unable to locate package zip
here is my commands to install zip:
- apt-get update && apt-get install -y --no-install-recommends \
        zip unzip
- echo `zip -v`

2. Use Docker image aws/codebuild/docker:1.12.1 which has pip and zip installed, but I have problem to install Python3.6. Error message:  Invalid operation groupinstall. I modified commands from https://stackoverflow.com/questions/44208268/python-3-6-unavailable-in-aws-codebuild-python-3-5-unavailable-in-aws-lambda

      - apt-get groupinstall -y development
      - apt-get install -y zlib-devel
      - curl https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
      - tar xJf Python-3.6.0.tar.xz
      - cd Python-3.6.0
      - ./configure
      - make
      - make install

Any help is appreciated!
Thanks!

**Comment by rog555** [comment]
@panyi121 i dont think this is a codebuild specific issue, have you tried building dockerfile image locally?  How about using aws/codebuild/docker:17.09.0 to build image from amazonlinux:latest with a bunch of yum installs (eg https://github.com/techinasia/amazon-linux-python3.6/blob/master/Dockerfile)

**Comment by clareliguori** [comment]
Python 3.6 image released in 01bfc1f
