### ISSUE TITLE
AWS_SESSION_TOKEN for aws-codebuild-local

### ISSUE THREAD

**Issue by alanthing** [aws/aws-codebuild-docker-images#160]
I've not been able to get `codebuild_build.sh` to work with `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and`AWS_SESSION_TOKEN` but only with `~/.aws/config` and `~/.aws/credentials`, despite the `codebuild_build.sh -c` option saying it will read all `AWS_` environmental variables. My use case is that my buildspec.yml file is running Packer, and I want to use STS-derived credentials instead of an IAM user's keys (MFA is required for admin-like privileges, and I'd like to assume the same role that CodeBuild will use when running on AWS). Is this supported?

**Comment by subinataws** [comment]
@alanthing - This is not supported today. Thanks for reporting that. We'll add this feature in a future release.

**Comment by awszhen** [comment]
Hi @alanthing , please use the latest version of the local agent. SHA: 7cae4f31566fc8a0411b79af5c5dbab144b53e30e25d20bff0320e0f68053678

**Comment by alanthing** [comment]
@subinataws @awszhen works as intended, thank you!
