### ISSUE TITLE
Please upgrade .NET Core image to 2.2

### ISSUE THREAD

**Issue by HakanL** [aws/aws-codebuild-docker-images#161]
.NET Core 2.2 was released on Dec 4, 2018, it would be great to have an updated image for it.

**Comment by subinataws** [comment]
@HakanL - Acknowledged. Thanks for the request. We'll get this updated in our next batch of update.

**Comment by subinataws** [comment]
https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/1.0/Dockerfile. This will be available to select on CodeBuild's APIs and console/UI in the next few days.
