### ISSUE TITLE
Permission denied trying to run the tutorial

### ISSUE THREAD

**Issue by mattsoftware** [aws/aws-codebuild-docker-images#165]
Trying to run the tutorial... https://aws.amazon.com/blogs/devops/announcing-local-build-support-for-aws-codebuild/

I get to the part where we need to run the following command to build the java project... `$ ./codebuild_build.sh -i aws/codebuild/java:openjdk-8 -a /home/ec2-user/environment/artifacts -s /home/ec2-user/environment/sample-web-app`

I created the /home/matt/environment folder, and the /home/matt/environment/artifacts folder, and copied the sample-web-app git project into the environment folder and ran the command and got the following output....

`
[matt@matt openjdk-8]$ ./codebuild_build.sh -i aws/codebuild/java:openjdk-8 -a /home/matt/environment/artifacts -s /home/matt/environment/sample-web-app/
Build Command:

docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=aws/codebuild/java:openjdk-8" -e "ARTIFACTS=/home/matt/environment/artifacts" -e "SOURCE=/home/matt/environment/sample-web-app/" -e "INITIATOR=matt" amazon/aws-codebuild-local:latest

Removing agent-resources_build_1 ... done
Removing agent-resources_agent_1 ... done
Removing network agent-resources_default
Removing volume agent-resources_source_volume
Removing volume agent-resources_user_volume
Creating network "agent-resources_default" with the default driver
Creating volume "agent-resources_source_volume" with local driver
Creating volume "agent-resources_user_volume" with local driver
Creating agent-resources_agent_1 ... done
Creating agent-resources_build_1 ... done
Attaching to agent-resources_agent_1, agent-resources_build_1
agent_1  | touch: cannot touch '/codebuild/output/log': Permission denied
agent_1  | tail: cannot open '/codebuild/output/log' for reading: No such file or directory
agent_1  | mkdir: cannot create directory '/codebuild/input/bin': Permission denied
agent-resources_agent_1 exited with code 1
Stopping agent-resources_build_1 ... done
Aborting on container exit...
`

I'm not sure what I am doing wrong as I believe I have followed the tutorial to the letter (except I do not wish to use cloud9 but use my own local linux machine, keeping true to the 'local' part of running codebuild locally)

Is anyone able to help? Thank You.

**Comment by awszhen** [comment]
Hi @mattsoftware , could you please tell us more about your environment (OS & Docker version)?

**Comment by mattsoftware** [comment]
Sure, I am running linux, CentOS 7. Docker version 1.13.1, build 94f4240/1.13.1

What else do you need to know?

(do you prefer to keep the thread here or on the aws codedeploy forum?)

**Comment by awszhen** [comment]
@mattsoftware , I was not able to reproduce this issue. I am using CentOS 7 and Docker version 18.09.2.
Would you please run `setenforce 0` and try again? Please keep the thread here.

**Comment by mattsoftware** [comment]
@awszhen Thank you for the tip! I completely forgot about selinux, so running ...
```
cat /var/log/audit/audit.log | audit2allow
```
found the issue, and this...
```
chcon -Rt svirt_sandbox_file_t /var/lib/
```
seems to get me back into working (sorry, refuse to turn selinux off, friends dont let friends turn off selinux ;)

Thanks for looking into it for me!
