### ISSUE TITLE
Support for Gradle 4.4+ in java openjdk-8 

### ISSUE THREAD

**Issue by srini156** [aws/aws-codebuild-docker-images#168]
Do we intend to support Gradle version - 4.4 and above (instead of `4.2.1`) in `openjdk-8` default code build docker image?

**Comment by subinataws** [comment]
@srini156 - We'll be providing an updated image, which will have Gradle 5.x with Ubuntu 18.04 base with our next release. 

If you were looking specifically for Gradle 4.x with openjdk-8, please consider using a custom Docker image instead.
