### ISSUE TITLE
Please provide Golang 1.12 image

### ISSUE THREAD

**Issue by maros7** [aws/aws-codebuild-docker-images#174]
Go version `1.12` has been released (https://blog.golang.org/go1.12). Please provide an image for this new version.

**Comment by subinataws** [comment]
Thanks for the feature request. We'll add this support in an upcoming release.

**Comment by subinataws** [comment]
Available in https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/2.0/Dockerfile#L20. This will be released in CodeBuild in the next few days.
