### ISSUE TITLE
aws  .net core 2.2 

### ISSUE THREAD

**Issue by kapivara-oficial** [aws/aws-codebuild-docker-images#176]

**Comment by subinataws** [comment]
https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/1.0/Dockerfile. This will be available to select on CodeBuild's APIs and console/UI in the next few days.

**Comment by HakanL** [comment]
Do we have a time frame on this, "next few days" 16 days ago? It's still not available.

**Comment by subinataws** [comment]
You can use that now with aws/codebuild/standard:1.0. https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/1.0/Dockerfile#L21

**Comment by HakanL** [comment]
But I can't choose that version in CodeBuild, the only .NET Core option is 2.1

**Comment by HakanL** [comment]
![image](https://user-images.githubusercontent.com/407941/55340387-6bdd5280-5459-11e9-8ecc-f09d2fad14d2.png)

**Comment by subinataws** [comment]
Please choose Ubuntu > Standard > 1.0. 
![image](https://user-images.githubusercontent.com/24447312/55340503-b068ee00-5459-11e9-831e-32a00f3df9b7.png)

**Comment by HakanL** [comment]
Oh, that's confusing, why is .NET Core under standard?

**Comment by subinataws** [comment]
We are bundling all runtimes into one image with Ubuntu 18.04. The prior ones were based on Ubuntu 14.04.5, which is technically EOL now and will be removed as an option in the next update.

**Comment by HakanL** [comment]
Ah I see, makes sense. I just tried it and it worked great, thanks!
