### ISSUE TITLE
Unable to run Docker commands in java:openjdk-8 image

### ISSUE THREAD

**Issue by jpblair** [aws/aws-codebuild-docker-images#177]
I'm using the OpenJDK 8 image to build a project with Maven, then copying a compiled artifact into a Docker image to push to ECR.  However, when I try to run the `docker build` command, I get this error: `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`  It seems like Docker is installed in some capacity, since running the image locally, I'm able to run `docker --version`.  I'm using other build artifacts in the CodeBuild job itself, so I don't think a multi-stage Docker build would be suitable for this purpose.

**Comment by subinataws** [comment]
Did you set the privileged mode to true for your CodeBuild project?

**Comment by jpblair** [comment]
@subinataws That seems to have worked, thanks.  What are the implications of running in privileged mode?  Does it introduce any security risks?

**Comment by subinataws** [comment]
Your builds gets ec2 level isolation regardless. Enabling this mode means you get extra permissions as described in Docker documentation.
