### ISSUE TITLE
Default credentials from config are not being used

### ISSUE THREAD

**Issue by OzTK** [aws/aws-codebuild-docker-images#183]
In the case where multiple credential profiles are setup, the default one is not being used. It seems that the last one is being used instead.

### Example case

1. Sample `~/.aws/credentials` file:
```
[default]
aws_access_key_id = ABCDE
aws_secret_access_key = abcde

[production]
aws_access_key_id = FGHIJ
aws_secret_access_key = fghij
```
2. Configure valid permissions to the parameter store on the default account only
3. Use a parameter store provided environment variable in the buildspec

This results in a denied permission on `ssm:GetParameters`

**Comment by awszhen** [comment]
@OzTK Thanks for reporting this issue. We'll fix it in a future release.

**Comment by awszhen** [comment]
Hi, please use latest version of the `codebuild_build.sh` and the local agent. SHA: a8c0057d75c8f4a735859d05ee01eab9bff417b4263f84feb5c38d2d681a3922

**Comment by OzTK** [comment]
Great, thanks for fixing!
