### ISSUE TITLE
Create a NodeJS 8.15.0 docker image

### ISSUE THREAD

**Issue by benniemosher** [aws/aws-codebuild-docker-images#185]
It looks like elasticbeanstalk's lowest version of NodeJS 8 is now 8.15.0. They recently dropped support for 8.11. We need a docker image that will install and use NodeJS 8.15.0.

**Comment by subinataws** [comment]
@benniemosher - Thanks for the contribution. We'll get this updated with our next batch of image update.

**Comment by subinataws** [comment]
https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/2.0/Dockerfile#L19
