### ISSUE TITLE
CODEBUILD_RESOLVED_SOURCE_VERSION Set to Empty on Local Linux Build

### ISSUE THREAD

**Issue by 64BitChris** [aws/aws-codebuild-docker-images#186]
When I attempt to use the  `CODEBUILD_RESOLVED_SOURCE_VERSION` environment variable from within my buildspec, while running the local version of CodeBuild, I get nothing back:

Example: 

`echo $CODEBUILD_RESOLVED_SOURCE_VERSION`

This returns just a blank line.  I've tried to set this explicitly in my environment, but it appears to be getting overwritten when I run the local builds (other environment variables work just fine).

Is there something we need to do to ensure this is set?  I'm running out of a local Git repository.

CodeBuild works remotely and this build is part of a CodePipeline where the sources are passed in from a 'Checkout Sources' step just prior.

Any help would be greatly appreciated.

**Comment by awszhen** [comment]
@64BitChris , please use the latest version of the local agent. SHA: 8e5443ad2aaae0a8e6c005bbf44446ab1fb4601588192413579df16913aba725

**Comment by 64BitChris** [comment]
Great, thank you for replying so quickly @awszhen - I'll give it a try.

**Comment by oliverahul** [comment]
The latest version of the agent at https://gallery.ecr.aws/codebuild/local-builds still doesn't have this fix? CODEBUILD_RESOLVED_SOURCE_VERSION environment variable still not being set in the local builds.
