### ISSUE TITLE
How do I emulate runtime-versions on interactive image?

### ISSUE THREAD

**Issue by joekiller** [aws/aws-codebuild-docker-images#200]
How do I emulate the runtime-versions commands in an interactive docker session with the new standard-image:2.0? With the introduction of the standard-image:2.0 the codebuild spec runtime-versions has a greater presence in workflow. I'd like to be able to test or understand how it affects the environment for my builds.

**Comment by subinataws** [comment]
@joekiller - we'll add support for runtime-versions in CodeBuild-local, which will be the recommended way to verify your buildspec locally.

**Comment by joekiller** [comment]
Okay support seems to already be there. Thanks for all the features. They
are useful.
