### ISSUE TITLE
Standard 2.0 image fails to build on Python install

### ISSUE THREAD

**Issue by pmartindev** [aws/aws-codebuild-docker-images#201]
As the title states, when I attempt to build the image, it fails trying to install Python with the following error:

```
gpg: keybox '/tmp/tmp.C1hMfAzIg1/pubring.kbx' created
gpg: key 2D347EA6AA65421D: 18 signatures not checked due to missing keys
gpg: /tmp/tmp.C1hMfAzIg1/trustdb.gpg: trustdb created
gpg: key 2D347EA6AA65421D: public key "Ned Deily (Python release signing key) <nad@python.org>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Mon Mar 25 21:00:43 2019 UTC
gpg:                using RSA key 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
gpg: Good signature from "Ned Deily (Python release signing key) <nad@python.org>" [unknown]
gpg:                 aka "Ned Deily <nad@baybryj.net>" [unknown]
gpg:                 aka "keybase.io/nad <nad@keybase.io>" [unknown]
gpg:                 aka "Ned Deily (Python release signing key) <nad@acm.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0D96 DF4D 4110 E5C4 3FBF  B17F 2D34 7EA6 AA65 421D
rm: cannot remove '/tmp/tmp.C1hMfAzIg1/S.gpg-agent.extra': No such file or directory
```

**Comment by subinataws** [comment]
@pmartindev - Could you please share your buildspec? Redact any sensitive information. I couldn't reproduce this issue. Here's my sample buildspec for aws/codebuild/standard:2.0

```
version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.6
  build:
    commands:
      - python --version
```

runtime-versions should be defined as (https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html):
![image](https://user-images.githubusercontent.com/24447312/57396002-43462800-717e-11e9-8e7b-157fa1136f7d.png)

Runtime name | Version/versions | How to specify in the buildspec file
-- | -- | --
android | 28 | android: 28
docker | 18 | docker: 18
dotnet | 2.2 | dotnet: 2.2
golang | 1.12 | golang: 1.12
nodejs | 8, 10 | nodejs: 8, nodejs: 10
java | openjdk8, openjdk11 | java: openjdk8, java: openjdk11
php | 7.3 | php: 7.3
python | 3.7 | python: 3.7
ruby | 2.6 | ruby: 2.6

**Comment by pmartindev** [comment]
Sorry @subinataws , I'm not trying to build in CodeBuild, I'm trying to run `docker build -t aws/codebuild/standard:2.0 .` under ./ubuntu/standard/2.0 to produce the docker image.

**Comment by srikanthataws** [comment]
@pmartindev - the docker build is failure is caused by the rm statement 
rm: cannot remove '/tmp/tmp.C1hMfAzIg1/S.gpg-agent.extra': No such file or directory

While I tried to reproduce it in my local, I was getting the same error. But when I retried it, it got built successfully. 

Can you please retry building it?

**Comment by pmartindev** [comment]
@srikanthataws Building the image from scratch failed,  but retrying it built successfully. Thanks for the help!

**Comment by pmartindev** [comment]
Here are the steps I used to create the image:

1. Downloaded the repository
2. Built the image, failed with above error
3. Rebuilt the image, failed with above error
4. Removed the entire Python installation section, built successfully
5. Re-added the entire Python section, built successfully

**Comment by swaincreates** [comment]
I just got this error on my first time trying to build - guess i'll try removing python stuff

**Comment by mycargus** [comment]
Same error here. Using docker for mac 2.0.0.3 (31259). 

I appreciate the amount of work that must go into a project as large as this, and the need to triage and prioritize bugs. That said, I'm a little confused as to why this issue was closed. The workaround steps may work for some but that's a pretty sad state of things to call "good" and close the issue. There is clearly something wrong.
