### ISSUE TITLE
Unable to build aws/codebuild/golang/1.11 noninteractively

### ISSUE THREAD

**Issue by lisp-ceo** [aws/aws-codebuild-docker-images#202]
While trying to build aws/codebuild/golang/1.11, add-apt-repository command asks for confirmation. As such, we're unable to build the container noninteractively. https://gist.github.com/lisp-ceo/c7d2a46b589ca3a01664f8b64d0b39dc

Steps to reproduce:
- git clone git@github.com:aws/aws-codebuild-docker-images.git
- cd ./aws-codebuild-docker-images/ubuntu/golang/1.11 && docker build -t aws/codebuild/golang/1.11 .

Gets the following output https://gist.github.com/lisp-ceo/c7d2a46b589ca3a01664f8b64d0b39dc
By adding the `-y` flag to add-apt-repository, the build proceeds. Would also like to see us add the env var `DEBIAN_FRONTEND=noninteractive`but just adding the `-y` flag is enough. 

Successful build: https://gist.github.com/lisp-ceo/1b713156d72d7cbd7b2ebee890043f98

**Comment by subinataws** [comment]
Merged. Thanks for the contribution.
