### ISSUE TITLE
docker doesn't work as promised migrating from docker:18.09.0 to standard:2.0

### ISSUE THREAD

**Issue by joekiller** [aws/aws-codebuild-docker-images#206]
When upgrading my builds to `aws/codebuild/standard:2.0` I have hit some unexpected behaviors highlighted below. These new issues were especially confusing since the documentation indicates that they should not be problems. Specifically Step 7 of [Change a Build Project's Settings (Console)](https://docs.aws.amazon.com/codebuild/latest/userguide/change-project.html#change-project-console) states that I should neither have to specify PrivilegedMode nor start up the docker daemon when using an official CodeBuild image with Docker support.

Problems:
  1. Switching from builds using `aws/codebuild/docker:18.09.0` to the new one requires updating the CodeBuild to run in PrivilegedMode.
  1. One has to start the docker daemon when using runtime-versions `docker: 18` which was already running when I used `docker:18:09.0`. Otherwise the migrated build ends up erroring with:

> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 

It seems like if the docker runtime is specified in the build then the codebuild image would also turn on docker. I think the second issue is likely an oversight because I didn't hit the problem until I ran a build on the cloud because I am using codebuild_build.sh to test so it seemed to work fine. I'd propose that the docker runtime entry point should check for the socket and then start it if it can't find it. 

Regarding the first problem this makes the pain of upgrading somewhat greater because we manage over eighty builds off one generic template. Without the service being able to tell by my image if I want a privileged build the "standard" image approach is limiting.

**Comment by joekiller** [comment]
Per #1 the problem for us is that when making a codebuild in cloudformation we never had to specify privileged or not. Just the image the image name was enough to get the expected behavior. Now if we update our build to use the new image privileged mode defaults to false.

**Comment by subinataws** [comment]
@joekiller - It is true that when you previously selected aws/codebuild/docker image (based on Ubuntu 14.04), you didn't have to select the privileged mode option. Since the new Ubuntu 18.04 based images are a polyglot image, which has all the CodeBuild supported runtimes, including Docker, you will need to opt-in for the privileged mode if you need Docker access in your build container.

**Comment by joekiller** [comment]
I figured that would be the answer but at least it is confirmed. 

As for point 2 l, it would be good to start the daemon as part of the runtime trigger.

**Comment by subinataws** [comment]
@joekiller - If you enable the privilege mode in your build project, then Docker will be accessible inside your build container. The error "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" will only show up when you have runtime-version set as Docker, but didn't select the privileged mode in AWS CodeBuild on AWS cloud.

sample buildspec:
```
version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
  build:
    commands:
      - docker info
```

**Comment by joekiller** [comment]
Great. Thanks for clarifying all this.

**Comment by nimboya** [comment]
This helped me too. 

Thanks

**Comment by AlexCromer** [comment]
I've posted on other threads about this, but I'm having the same issue even though I've set the privilegedmode: true as well as embedded manual commands into my `install` phase explicitly starting the docker daemon. However, I still get the "is the daemon running?" error.

Any assistance is appreciated.

Alex

**Comment by joekiller** [comment]
You should post an example but my guess is that you need to specifically
state
runtime:
    docker: 18.0

Also this only works with the standard:2.0 codebuild image.

Sent via mobile

**Comment by AlexCromer** [comment]
So here is what is in my buildspec.yaml.

```
phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
```

As far as the codebuild image I am in fact using `aws/codebuild/standard:2.0`

**Comment by AlexCromer** [comment]
I've even gone as far as pulling down the [`standard:2.0` image](https://github.com/aws/aws-codebuild-docker-images) locally and running it and everything runs perfectly fine.....

**Comment by joekiller** [comment]
I setup the following and it seemed fine:

```
[jlawson@joe-9900k ~]$ aws codebuild batch-get-projects --names joe-test
{
    "projects": [
        {
            "name": "joe-test",
            "arn": "arn:aws:codebuild:us-east-1:976940607391:project/joe-test",
            "source": {
                "type": "NO_SOURCE",
                "gitCloneDepth": 1,
                "buildspec": "version: 0.2\n\n#env:\n  #variables:\n     # key: \"value\"\n     # key: \"value\"\n  #parameter-store:\n     # key: \"value\"\n     # key: \"value\"\n  #git-credential-helper: yes\n\nphases:\n  install:\n    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.\n    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.\n    runtime-versions:\n       nodejs: 10\n       docker: 18 \n  #pre_build:\n    #commands:\n      # - command\n      # - command\n  build:\n    commands:\n       - docker ps\n       - node -v\n  #post_build:\n    #commands:\n      # - command\n      # - command\n#artifacts:\n  #files:\n    # - location\n    # - location\n  #name: $(date +%Y-%m-%d)\n  #discard-paths: yes\n  #base-directory: location\n#cache:\n  #paths:\n    # - paths",
                "insecureSsl": false
            },
            "secondarySources": [],
            "secondarySourceVersions": [],
            "artifacts": {
                "type": "NO_ARTIFACTS"
            },
            "secondaryArtifacts": [],
            "cache": {
                "type": "NO_CACHE"
            },
            "environment": {
                "type": "LINUX_CONTAINER",
                "image": "aws/codebuild/standard:2.0",
                "computeType": "BUILD_GENERAL1_SMALL",
                "environmentVariables": [],
                "privilegedMode": true,
                "imagePullCredentialsType": "CODEBUILD"
            },
            "serviceRole": "arn:aws:iam::976940607391:role/service-role/joe-codebuild-test",
            "timeoutInMinutes": 60,
            "queuedTimeoutInMinutes": 480,
            "encryptionKey": "arn:aws:kms:us-east-1:976940607391:alias/aws/s3",
            "tags": [],
            "created": 1565269797.545,
            "lastModified": 1565269958.454,
            "badge": {
                "badgeEnabled": false
            },
            "logsConfig": {
                "cloudWatchLogs": {
                    "status": "ENABLED"
                },
                "s3Logs": {
                    "status": "DISABLED",
                    "encryptionDisabled": false
                }
            }
        }
    ],
    "projectsNotFound": []
}
```

When I disabled privilegedMode, the error returned. I'd check your settings of the project.

The mode setting is somewhat hidden in the options. Under "Edit Environment" you have to click Override Image.

![image](https://user-images.githubusercontent.com/1022919/62706540-c1a0a900-b9bd-11e9-93ff-70d33d2131c7.png)

and then make sure the box is checked:

![image](https://user-images.githubusercontent.com/1022919/62706567-d1b88880-b9bd-11e9-8644-0dd009f96cd1.png)


Otherwise try making sure via the cli ` aws codebuild batch-get-projects --names <build-name>` to confirm your settings.

Also in the future, you should probably start a new issue instead of commenting on one that was closed three months ago.

![image](https://user-images.githubusercontent.com/1022919/62706592-dda44a80-b9bd-11e9-98a8-d096734d136c.png)

![image](https://user-images.githubusercontent.com/1022919/62706588-dc731d80-b9bd-11e9-9f12-313e5a72ad0f.png)

**Comment by joekiller** [comment]
I setup the following and it seemed fine:

```
[jlawson@joe-9900k ~]$ aws codebuild batch-get-projects --names joe-test
{
    "projects": [
        {
            "name": "joe-test",
            "arn": "arn:aws:codebuild:us-east-1:123458690:project/joe-test",
            "source": {
                "type": "NO_SOURCE",
                "gitCloneDepth": 1,
                "buildspec": "version: 0.2\n\n#env:\n  #variables:\n     # key: \"value\"\n     # key: \"value\"\n  #parameter-store:\n     # key: \"value\"\n     # key: \"value\"\n  #git-credential-helper: yes\n\nphases:\n  install:\n    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.\n    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.\n    runtime-versions:\n       nodejs: 10\n       docker: 18 \n  #pre_build:\n    #commands:\n      # - command\n      # - command\n  build:\n    commands:\n       - docker ps\n       - node -v\n  #post_build:\n    #commands:\n      # - command\n      # - command\n#artifacts:\n  #files:\n    # - location\n    # - location\n  #name: $(date +%Y-%m-%d)\n  #discard-paths: yes\n  #base-directory: location\n#cache:\n  #paths:\n    # - paths",
                "insecureSsl": false
            },
            "secondarySources": [],
            "secondarySourceVersions": [],
            "artifacts": {
                "type": "NO_ARTIFACTS"
            },
            "secondaryArtifacts": [],
            "cache": {
                "type": "NO_CACHE"
            },
            "environment": {
                "type": "LINUX_CONTAINER",
                "image": "aws/codebuild/standard:2.0",
                "computeType": "BUILD_GENERAL1_SMALL",
                "environmentVariables": [],
                "privilegedMode": true,
                "imagePullCredentialsType": "CODEBUILD"
            },
            "serviceRole": "arn:aws:iam::123458690:role/service-role/joe-codebuild-test",
            "timeoutInMinutes": 60,
            "queuedTimeoutInMinutes": 480,
            "encryptionKey": "arn:aws:kms:us-east-1:123458690:alias/aws/s3",
            "tags": [],
            "created": 1565269797.545,
            "lastModified": 1565269958.454,
            "badge": {
                "badgeEnabled": false
            },
            "logsConfig": {
                "cloudWatchLogs": {
                    "status": "ENABLED"
                },
                "s3Logs": {
                    "status": "DISABLED",
                    "encryptionDisabled": false
                }
            }
        }
    ],
    "projectsNotFound": []
}
```

When I disabled privilegedMode, the error returned. I'd check your settings of the project.

The mode setting is somewhat hidden in the options. Under "Edit Environment" you have to click Override Image.

![image](https://user-images.githubusercontent.com/1022919/62706540-c1a0a900-b9bd-11e9-93ff-70d33d2131c7.png)

and then make sure the box is checked:

![image](https://user-images.githubusercontent.com/1022919/62706567-d1b88880-b9bd-11e9-8644-0dd009f96cd1.png)


Otherwise try making sure via the cli ` aws codebuild batch-get-projects --names <build-name>` to confirm your settings.

Also in the future, you should probably start a new issue instead of commenting on one that was closed three months ago.

![image](https://user-images.githubusercontent.com/1022919/62706592-dda44a80-b9bd-11e9-98a8-d096734d136c.png)

![image](https://user-images.githubusercontent.com/1022919/62706588-dc731d80-b9bd-11e9-9f12-313e5a72ad0f.png)

**Comment by AlexCromer** [comment]
Fair point about starting new thread, sorry. Would you like me to do so? Also here is the below output of the same command you ran above.
```
~/aws_proj$ aws codebuild batch-get-projects --names infra-node-ecs-sample
{
    "projects": [
        {
            "name": "infra-node-ecs-sample",
            "arn": "<redacted>",
            "source": {
                "type": "GITHUB_ENTERPRISE",
                "location": "<redacted>",
                "gitCloneDepth": 1,
                "buildspec": "buildspec.yaml",
                "reportBuildStatus": true,
                "insecureSsl": false
            },
            "artifacts": {
                "type": "NO_ARTIFACTS"
            },
            "cache": {
                "type": "NO_CACHE"
            },
            "environment": {
                "type": "LINUX_CONTAINER",
                "image": "aws/codebuild/standard:2.0",
                "computeType": "BUILD_GENERAL1_SMALL",
                "environmentVariables": [
                    {
                        "name": "REPO_NAME",
                        "value": "infra-node-ecs-sample",
                        "type": "PLAINTEXT"
                    }
                ],
                "privilegedMode": true,
                "imagePullCredentialsType": "CODEBUILD"
            },
```

![image](https://user-images.githubusercontent.com/8886301/62709085-b2702a00-b9c2-11e9-8d2f-731784b1627c.png)

**Comment by subinataws** [comment]
@AlexCromer - could you please post this question on CodeBuild's forums @ https://forums.aws.amazon.com/forum.jspa?forumID=230. We'll need your buildARN, to look into this further, which we will request you to send as a personal message on the forum. This repo is meant more for CodeBuild's docker images and local-agent. Issues with CodeBuild on AWS cloud will need to be on the forums for better traction. We will look into this.
