### ISSUE TITLE
docker image for 16.04

### ISSUE THREAD

**Issue by Ahmedshabaz06** [aws/aws-codebuild-docker-images#207]
as the eol for 14.04 has been past, can you guys be able to provide a 16.04 image for codebuild?

**Comment by subinataws** [comment]
@Ahmedshabaz06 - CodeBuild supports Ubuntu 18.04 based images. Dockerfile @ https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/2.0/Dockerfile.

You will need to select aws/codebuild/standard:2.0 as the image and specify a runtime-version for the programming language runtime.
