### ISSUE TITLE
Node 11 support

### ISSUE THREAD

**Issue by jpike88** [aws/aws-codebuild-docker-images#208]
Node 11 has been out since last October. There should have been a version for that by now.

**Comment by subinataws** [comment]
We'll only be supporting LTS versions in CodeBuild provided images. Node 11 will be EOL in June 2019 as per https://nodejs.org/en/about/releases/. Node 8.x and 10.x are supported. Once 12.x reaches LTS we'll add support for that as well. 

You may consider using a custom image for node 11.x in your CodeBuild project.

**Comment by bensooraj** [comment]
@subinataws Apologies for commenting on a closed issue. However, `12.4.1` is the current Node.js LTS. Is this supported yet?

Or do you still recommend using a custom image?
