### ISSUE TITLE
Update Docker version to >= 17.05 to support multi-stage builds

### ISSUE THREAD

**Issue by djwhitt** [aws/aws-codebuild-docker-images#21]
I'm working on a project using [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/). Unfortunately CodeBuild seems to only support Docker 12.1. Is there a timeline for upgrade to a newer version (>= 17.05) of Docker that supports multi-stage builds?

**Comment by rubyisbeautiful** [comment]
I [took a stab at it](https://github.com/aws/aws-codebuild-docker-images/pull/22), and as far as I can tell, it won't work until they allow the containers to run with privileges.  I suspect that's one of the main reasons it hasn't been upgraded.

**Comment by rubyisbeautiful** [comment]
dups #6 btw

**Comment by subinataws** [comment]
CodeBuild now has a Docker 17 image. We have a sample that uses "aws/codebuild/docker:17.09.0" @ http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html

Marking this resolving
