### ISSUE TITLE
codebuild_build.sh: Unable to write artifacts to $TMPDIR on OSX

### ISSUE THREAD

**Issue by mconigliaro** [aws/aws-codebuild-docker-images#213]
If you set `-a "$TMPDIR"` on OSX, the artifacts never show up, even though the agent says `UPLOAD_ARTIFACTS State: SUCCEEDED`. My current workaround is to use `-a /tmp` instead.

**Comment by awszhen** [comment]
Hi @mconigliaro , the `/var` is not a shared directory. By default, the shared directories are `/Users`, `/Volumes`, `/private` and `/tmp`.
