### ISSUE TITLE
.NET Core 2.1 support in Ubuntu/Standard 2.0

### ISSUE THREAD

**Issue by amgrice** [aws/aws-codebuild-docker-images#217]
I understand many folks wanted 2.2 and that's great, but perhaps it was a bit premature to drop an LTS release from the image? I have one CodeBuild job that I created a few weeks ago that uses the 2.1 image, but when trying to create another job today, I can not.

Any plans to bring back 2.1 support?

Cheers,

**Comment by subinataws** [comment]
Unfortunately, we don't have plans to go back from .NET Core 2.2 to 2.1 at this time. We typically try to only support LTS versions in CodeBuild managed images. However, it looks like based on the PRs and issues submitted for .NET Core 2.2, we ended up moving to 2.2 without realizing it wasn't an LTS version.

Your best bet at this time is to use a custom Docker image or installing the required .net core version in the image.

While aws/codebuild/dot-net:core-2.1 is still available, when creating a CodeBuild project via AWS CLI. We do not recommend it, as it is based on Ubuntu 14.04, which was EOL in April 2019.
