### ISSUE TITLE
Building Standard 2.0 Codebuild with Java Runtime takes too long

### ISSUE THREAD

**Issue by Joel-fogue** [aws/aws-codebuild-docker-images#226]
I understand there's an initial Cold start on codebuild containers when it first startsup and setups up the build environment with the various runtine versions. 
But I have noticed a painful delay in Codebuild at the PROVISIONING step, about 4 to 5mins and then after the java runtime is setup it takes another 3mins for our actual build which 3mins is not bad.
Why is the PROVISIONING step taking noticeably longer than usual?
1. Could it be related to the underlying docker layers expiring too soon?
2. Cold start time? But I don't think so because subsequent code checkins experience similar delays
3. Could it be possibly the size of the standard image being too large delaying when codebuild tries to pull it down? Our codebuild environments are using BUILD_GENERAL1_SMALL compute type although I upgraded a few to BUILD_GENERAL1_MEDIUM and noticed a tiny improvement 
Anyone else observing a similar behavior with their build taking too long at the provisioning step?

Thank you,
Joel

**Comment by subinataws** [comment]
@Joel-fogue - could you please post your question on the AWS CodeBuild forum? https://forums.aws.amazon.com/forum.jspa?forumID=230. We will need your buildARN for the oncalls to take a look at it. Posting on the forums will allow us to look up your build or follow up with specific questions via personal message.

**Comment by subinataws** [comment]
Resolving this issue on GitHub. For support with AWS CodeBuild on AWS Cloud, please post your query on the AWS forums. Like I mentioned in my earlier comment, we will need more information about your build to assist.
