### ISSUE TITLE
Standard 2.0 error installing Python

### ISSUE THREAD

**Issue by gitorrin** [aws/aws-codebuild-docker-images#228]
Hi, 

There's another issue on the same topic, with status = Closed. 

I am using CodeBuild, to build a docker image and still get an error while installing Python:
`cannot remove '/tmp/tmp.PKnPnQjq8z/S.gpg-agent.extra': No such file or directory`

PS: I'm simply building the official Standard 2.0 image published on github.

**Comment by subinataws** [comment]
Keyserver is likely timing out for you. If you look at a few lines above this error message, you will see that keyserver timed out. You may try a different keyserver than what's listed in https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/2.0/Dockerfile#L151-L153. If this is still failing you may also skip the verification @ https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/2.0/Dockerfile#L154.

The Dockerfiles provided in this repository are the same ones are used on CodeBuild's build fleet. CodeBuild uses the Docker image built from these images and hosted in Amazon ECR for its fleet.

We are not able to distribute the current version of the Docker images on DockerHub. However, we will be adding an Amazon Linux 2 version of these images, at which time they will be available on DockerHub and hopefully doesn't need you to build these Dockerfile.
