### ISSUE TITLE
Standard:2.0 build failing

### ISSUE THREAD

**Issue by DevBOFH** [aws/aws-codebuild-docker-images#231]
Similar to #228 and #201 I'm reporting that the standard:2.0 build is failing. #228 states that it's probably the key server timing out and the issue was closed and thread locked. However that's not the problem. #201 was also closed and thread locked because it "worked after retrying". While that may be the case for some, it's not for others.

The failure is:

```
#16 9.457 2019-07-03 21:06:54 (45.2 MB/s) - ‘python.tar.xz’ saved [17108364/17108364]
#16 9.457
#16 9.463 --2019-07-03 21:06:54--  https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz.asc
#16 9.463 Resolving www.python.org (www.python.org)... 151.101.0.223, 151.101.64.223, 151.101.128.223, ...
#16 9.465 Connecting to www.python.org (www.python.org)|151.101.0.223|:443... connected.
#16 9.486 HTTP request sent, awaiting response... 200 OK
#16 9.501 Length: 833 [application/octet-stream]
#16 9.501 Saving to: ‘python.tar.xz.asc’
#16 9.501
#16 9.501      0K                                                       100% 42.3M=0s
#16 9.501
#16 9.501 2019-07-03 21:06:54 (42.3 MB/s) - ‘python.tar.xz.asc’ saved [833/833]
#16 9.501
#16 9.512 gpg: keybox '/tmp/tmp.ZNeJMgXOB2/pubring.kbx' created
#16 10.09 gpg: key 2D347EA6AA65421D: 18 signatures not checked due to missing keys
#16 10.09 gpg: /tmp/tmp.ZNeJMgXOB2/trustdb.gpg: trustdb created
#16 10.09 gpg: key 2D347EA6AA65421D: public key "Ned Deily (Python release signing key) <nad@python.org>" imported
#16 10.10 gpg: no ultimately trusted keys found
#16 10.10 gpg: Total number processed: 1
#16 10.10 gpg:               imported: 1
#16 10.17 gpg: Signature made Mon Mar 25 21:00:43 2019 UTC
#16 10.17 gpg:                using RSA key 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
#16 10.17 gpg: Good signature from "Ned Deily (Python release signing key) <nad@python.org>" [unknown]
#16 10.17 gpg:                 aka "Ned Deily <nad@baybryj.net>" [unknown]
#16 10.17 gpg:                 aka "keybase.io/nad <nad@keybase.io>" [unknown]
#16 10.17 gpg:                 aka "Ned Deily (Python release signing key) <nad@acm.org>" [unknown]
#16 10.17 gpg: WARNING: This key is not certified with a trusted signature!
#16 10.17 gpg:          There is no indication that the signature belongs to the owner.
#16 10.17 Primary key fingerprint: 0D96 DF4D 4110 E5C4 3FBF  B17F 2D34 7EA6 AA65 421D
#16 10.18 rm: cannot remove '/tmp/tmp.ZNeJMgXOB2/S.gpg-agent.extra': No such file or directory
#16 10.18 rm: cannot remove '/tmp/tmp.ZNeJMgXOB2/S.gpg-agent.ssh': No such file or directory
```

**Comment by DevBOFH** [comment]
Removing lines 154 and 155 fixed this and the container built successfully. https://github.com/aws/aws-codebuild-docker-images/blob/95cc995faed25051fba1b8ac5b3400b3783fb4af/ubuntu/standard/2.0/Dockerfile#L154

**Comment by derwasp** [comment]
I had the same issue multiple times before. After a bunch of re-runs it would finally work. The image is pretty unstable, that's the impression I have.

What I did to work this around in case I need to debug something is I created this repo:
https://github.com/derwasp/aws-codebuild-official-images
I want to state this to avoid confusion: **this repo is not created by Amazon, it's just my playground**

What this repo does is it goes through all the `Dockerfile`s from `aws-codebuild-docker-images` and pushes them to docker hub to build.
I run the bodge-script from master once a day to check if we have any updates in the original repo. And if we do, I will take the latest version and rebuild it again.

For what it's worth, I managed to build both [standard-2.0](https://cloud.docker.com/repository/docker/derwasp/aws-codebuild-official-images/builds/9bf48d25-28ed-48aa-ab19-66c721a1e094) and standard-1.0 there.

**Comment by joekiller** [comment]
I think gpg was suffering from DOS attacks last month. So this is kinda a non-issue:

https://forums.solydxk.com/viewtopic.php?t=7570&p=70464

**Comment by subinataws** [comment]
Removed keyserver calls from Dockerfile to let it build reliably. CodeBuild's internal build process would still continue to use it as part of the verification. Marking resolved.

**Comment by the-vampiire** [comment]
@derwasp thanks man. i could not get it to build locally. it kept hanging up on installing ruby. your images work great.

as an aside do you know if its necessary to install all those runtimes? it would be nice to specify that i only need nodejs to speed up the build
