### ISSUE TITLE
MAVEN_CONFIG variable breaks the mvn builds in standard image

### ISSUE THREAD

**Issue by michalvanco** [aws/aws-codebuild-docker-images#237]
See https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/2.0/Dockerfile#L330:
```
MAVEN_CONFIG="/root/.m2" (set in image ENV)
```

Having this set breaks all `mvn` builds inside the image because the variable is used in apache maven codebase before the tasks being executed which leads to:
```
[INFO] BUILD FAILURE 
[INFO] ------------------------------------------------------------------------ 
[INFO] Total time:  3.698 s 
[INFO] Finished at: 2019-07-29T13:35:38Z 
[INFO] ------------------------------------------------------------------------ 
[ERROR] Unknown lifecycle phase "/root/.m2".
```
Which is actually caused by MAVEN_CONFIG being included in tasks section:
```
[DEBUG] === REACTOR BUILD PLAN ================================================ 
[DEBUG] Project: com.example.test:0.0.1-SNAPSHOT 
[DEBUG] Tasks:   [/root/.m2, clean, package] 
[DEBUG] Style:   Regular 
```

Related code is here - https://github.com/apache/maven/blob/master/apache-maven/src/bin/mvn#L188

I would prefer if the variable is unset in ENV after the directory is created.

I'll be happy to send a PR.

Current workaround in my `buildspec.yml`:
```
  build:
    commands:
      # MAVEN_CONFIG is set to /root/.m2 is CodeBuild Dockerfile which breaks the mvn usage
      # see https://github.com/apache/maven/blob/master/apache-maven/src/bin/mvn#L188
      - export MAVEN_CONFIG=''
      ...
```

**Comment by subinataws** [comment]
Thanks for reporting the issue. We are looking into it and will batch the fix for it with a future release.

**Comment by subinataws** [comment]
This bug is fixed in aws/codebuild/amazonlinux2-x86_64-standard:3.0 and aws/codebuild/standard:4.0, released as part of https://github.com/aws/aws-codebuild-docker-images/tree/20.03.13
