### ISSUE TITLE
Output results from codebuild_build.sh into PowerShell window

### ISSUE THREAD

**Issue by robertlarkins** [aws/aws-codebuild-docker-images#239]
When I run codebuild_build.sh in a PowerShell window using the following
```
.\codebuild_build.sh -i dockerimage -a artefactDirectory
```
it opens a cmd.exe windows, runs the script, then promptly closes the window before I can read through the output. Is it possible to get the script to put its output directly into the PowerShell window rather than opening this separate window?

**Comment by awszhen** [comment]
Hi, it is not possible. Closing this in favor of #252.
