### ISSUE TITLE
Source path doesn't seem to handle spaces for codebuild_build

### ISSUE THREAD

**Issue by robertlarkins** [aws/aws-codebuild-docker-images#240]
I'm running the script codebuild_build.sh in a directory whose path has a space in it (D:\Project Workspace\path\to\directory). The output in the cmd.exe window or the Git Bash windows produces
```
docker run -it -v //var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=awscodebuilddotnet" -e "ARTIFACTS=//Ymldist" -e "SOURCE=//D/Project" -e "INITIATOR=somename" amazon/aws-codebuild-local:latest
```
which has `SOURCE=//D/Project` rather than the whole path. Is it possible to get the script to support source paths that have spaces in them?

**Comment by awszhen** [comment]
Hi @robertlarkins , please use the latest `codebuild_build.sh`. Thanks!
