### ISSUE TITLE
Running cloudformation template fails when using custom Transform

### ISSUE THREAD

**Issue by psmith6** [aws/aws-codebuild-docker-images#246]
One of my build steps runs a cloudformation template which has a custom transform. The transform is available in us-east-1 which is the same region in which code build is running. This same cloudformation template works when I run it with my local cli. Could you provide how to get this transform working in the code build container.

My local cli is `aws-cli/1.16.223 Python/3.6.0 Windows/10 botocore/1.12.213`

```
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.6/dist-packages/awscli/clidriver.py", line 207, in main 
    return command_table[parsed_args.command](remaining, parsed_args) 
  File "/usr/local/lib/python3.6/dist-packages/awscli/clidriver.py", line 348, in __call__ 
    return command_table[parsed_args.operation](remaining, parsed_globals) 

  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/commands.py", line 187, in __call__ 
    return self._run_main(parsed_args, parsed_globals) 
  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/cloudformation/deploy.py", line 295, in _run_main 
    parsed_args.fail_on_empty_changeset) 
  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/cloudformation/deploy.py", line 310, in deploy 
    tags=tags 
  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/cloudformation/deployer.py", line 227, in create_and_wait_for_changeset 
    self.wait_for_changeset(result.changeset_id, stack_name) 
  File "/usr/local/lib/python3.6/dist-packages/awscli/customizations/cloudformation/deployer.py", line 178, in wait_for_changeset 
    .format(ex, status, reason)) 
RuntimeError: Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Failed to execute transform REDACTED::ALKSify 
2019-08-21 17:03:42,717 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255 
 
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Failed to execute transform REDACTED::ALKSify 
```

**Comment by subinataws** [comment]
@psmith6 - Apologies for the delayed response. Can you share more context? Which environment in CodeBuild did you use? Is it Linux or Windows? Also, what was the Docker image that you used (CodeBuild provided one or a custom one)?

Did you try updating the AWS CLI inside the build container?

**Comment by psmith6** [comment]
This issue is on Linux using image `aws/codebuild/standard:2.0`. I am using a custom macro to transform the cloudformation template. When running this same template from my local CLI or local code build using the `aws/codebuild/standard:2.0` image, it works. When hosted code build runs the same buildspec, it fails to run the transform with the error `Failed to execute transform`

**Comment by subinataws** [comment]
Could you please share your buildspec (redact any sensitive information)? Also, did you already try updating the AWS CLI within the build container and see if the version is same or higher than what you have locally?

**Comment by subinataws** [comment]
There still isn't enough info on this issue to help you. Please open an AWS support ticket to get the needed help from the service that you are having issue with (I assume this is CloudFormation here). One thing I did confirm is that CodeBuild environment has an older version of the aws cli. AWSCLI releases on a near daily basis, so CodeBuild's awscli version will always be a few days older. 

CodeBuild: ```aws-cli/1.16.204 Python/3.6.8 Linux/4.14.138-89.102.amzn1.x86_64 exec-env/AWS_ECS_EC2 botocore/1.12.194```. This is slightly older than the 1.16.223 you have on your local machine.

You can update the awscli by running ```pip3 install awscli``` in your buildspec. This will give you the latest version of awscli that's available.
