### ISSUE TITLE
Ruby 2.6.4

### ISSUE THREAD

**Issue by ybiquitous** [aws/aws-codebuild-docker-images#248]
Hi, Ruby 2.6.4 has been released on August 28, 2019. So, could you please consider the upgrade?

This version includes security fixes. For details, please see the release note below:
https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/

Thanks.

**Comment by subinataws** [comment]
yes, we'll add this update in our next update.

**Comment by subinataws** [comment]
This version is available on CodeBuild now.
