### ISSUE TITLE
Support for Go 1.13

### ISSUE THREAD

**Issue by msiuts** [aws/aws-codebuild-docker-images#249]
Please support [Go 1.13](https://golang.org/doc/go1.13) in the Codebuild images.

**Comment by subinataws** [comment]
Thanks. We'll add support for it in an upcoming release.

**Comment by subinataws** [comment]
go 1.13 is now available on CodeBuild. https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
