### ISSUE TITLE
Guide on how to run Docker-in-Docker images locally?

### ISSUE THREAD

**Issue by nathanielks** [aws/aws-codebuild-docker-images#25]
Hi, team!

Thanks so much for making the Dockerfiles accessible! I was wondering if it's possible to do a write up on how to run the docker in docker images locally? This would be very useful for debugging purposes!

**Comment by ivan-pinatti** [comment]
@nathanielks,

It is quite simple actually, try this on your local machine with docker service installed and running

```
docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -it docker:17.12.0-ce \
  /bin/sh
```

And then inside the container you can spin-up another container by simply

```
docker run hello-world
```

Cheers!

**Comment by nathanielks** [comment]
Heya, @ivan-pinatti! Forgive me, I failed to include some important context. I was thinking about how to test locally on a mac. As I understand it, the docker socket isn't reachable because it's inside the docker virtual machine. Are you familiar with a way to expose it? I'll keep searching!

**Comment by ivan-pinatti** [comment]
@nathanielks,

Sorry but I do not use Mac OS, however, I think this question is more appropriate in the Docker forum.
If you search there you will find some posts related to what you are looking for, check the link below;

[https://forums.docker.com/t/how-to-run-docker-inside-a-container-running-on-docker-for-mac/16268](https://forums.docker.com/t/how-to-run-docker-inside-a-container-running-on-docker-for-mac/16268)

**Comment by nathanielks** [comment]
I'll keep searching. Thanks, @ivan-pinatti! I'll report back here when I find a solution.
