### ISSUE TITLE
$AWS_SHARED_CREDENTIALS_FILE and $AWS_CONFIG_FILE environment variables in codebuild_build.sh

### ISSUE THREAD

**Issue by ducmthai** [aws/aws-codebuild-docker-images#250]
Hi,

I set these variables and they works in my host environment. However, whenever I specify the "-c" option to codebuild_build.sh it passes the variables to the agent but the agent did not get the credentials correctly:

Build command:
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=aws/codebuild/amazonlinux2-x86_64-standard:1.0" -e "ARTIFACTS=/home/me/project/out" -e "SOURCE=/home/me/project/" -e "BUILDSPEC=/home/me/project/buildspec-local.yml" -e "AWS_CONFIGURATION=/home/me/project/.aws" -e "AWS_CONFIG_FILE=/new/.aws/config" -e "AWS_SHARED_CREDENTIALS_FILE=/new/.aws/credentials" -e "INITIATOR=me" amazon/aws-codebuild-local:latest`

What I got:
`agent_1  | 2019/09/10 16:13:32 [Customer Config] Couldn't open specified customer config file: open /root/.aws/config: no such file or directory                                              agent_1  | 2019/09/10 16:13:32 [Customer Config] Error parsing supplied customer config file: invalid argument` 

I have removed '~/.aws' directory but the "AWS_CONFIG_FILE=NONE" was used and the execution result is the same.

Thanks

**Comment by subinataws** [comment]
Thanks for the feature request. We don't support these today, but will add this it in a future release.

**Comment by awszhen** [comment]
@ducmthai , please use latest version of the local agent. SHA: bd69dbcdc9b3da66fd93de0b6d45534086367d6b48d3536d0248a01a459fb7e4
