### ISSUE TITLE
url for centos package is broken.

### ISSUE THREAD

**Issue by tee33** [aws/aws-codebuild-docker-images#256]
ENV LIBGIT2_PKG="https://rpmfind.net/linux/centos/7.6.1810/extras/x86_64/Packages/libgit2-0.26.6-1.el7.x86_64.rpm"  is broken.

Readme suggest, we use /7 instead of the 7.6.1810. 

![image](https://user-images.githubusercontent.com/11220623/65935998-ddc63280-e3cf-11e9-961f-981b62baa9e8.png)

**Comment by subinataws** [comment]
Thanks for reporting this issue. This has been fixed.
