### ISSUE TITLE
Where is MOUNT_SOURCE_DIRECTORY used?

### ISSUE THREAD

**Issue by rainkinz** [aws/aws-codebuild-docker-images#257]
Hi All,

I'm trying to debug an 'issue' with the `-m` flag, I see supplying it ultimately leads to `MOUNT_SOURCE_DIRECTORY` being set to `TRUE`, but where is this used?

https://github.com/aws/aws-codebuild-docker-images/blob/710fe96286cfd9b60df33e935dbc1446bd30e3e5/local_builds/codebuild_build.sh#L160

Thank you

**Comment by awszhen** [comment]
Hi @rainkinz , `MOUNT_SOURCE_DIRECTORY` will mount the source directory to the customer build container directly instead of copying source directory to a volume at first.

**Comment by rainkinz** [comment]
Hi, thanks for the reply. Sorry I should have clarified. I read that it should mount the source directory to the customer build container directly. However, when I search the repo I couldn't find any reference to `MOUNT_SOURCE_DIRECTORY` except in the line linked above.

**Comment by awszhen** [comment]
Hi @rainkinz , `MOUNT_SOURCE_DIRECTORY` environment variable is used internally in our agent image.

**Comment by rainkinz** [comment]
Aha, thanks for the reply. It's clear now.
