### ISSUE TITLE
Support for Node 12

### ISSUE THREAD

**Issue by GaryGSC** [aws/aws-codebuild-docker-images#260]
Node 12 ([12.13.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.13.0)) now has [LTS status](https://nodejs.org/en/about/releases/).

**Comment by RoyHP** [comment]
Yes, this would be great. It's now LTS and 10 is now longer directly offered for download. [https://nodejs.org/en/](https://nodejs.org/en/)

**Comment by subinataws** [comment]
We are working on this and expect to have these out by mid-November.

**Comment by enrolyMike** [comment]
It's pretty much Mid-November do we have a release date? Thanks.

**Comment by subinataws** [comment]
Thanks for your patience. We make this live only when the new version can be accessed in all CodeBuild regions.

**Comment by naga-aws** [comment]
node:12 is supported on our new codebuild images(AL2 2.0 & Standard 3.0).
Ref : https://github.com/aws/aws-codebuild-docker-images/releases/tag/19.11.26
