### ISSUE TITLE
Add pwgen utility to the images

### ISSUE THREAD

**Issue by vibhuyadav** [aws/aws-codebuild-docker-images#261]
I think pwgen is a versatile tool and is used by us to generate random passwords during the builds. I was hoping it could become part of the standard image.

**Comment by subinataws** [comment]
Thanks for submitting the request. What is the license for this utility? This appears to be GPLv3. In which case, we won't be adding it to the images. However, you are free to install this package in your buildspec.

**Comment by subinataws** [comment]
Confirmed that this is GPLv2. We won't adding to CodeBuild's images, but you are free to install inline in your buildspec.
