### ISSUE TITLE
Support for go 1.13.1 (or 1.13.2 ideally) and 1.12.10 on AL2

### ISSUE THREAD

**Issue by chr1sbest** [aws/aws-codebuild-docker-images#263]
Request smuggling vulnerability in existing go versions announced in September:
https://groups.google.com/forum/#!msg/golang-announce/cszieYyuL9Q/g4Z7pKaqAgAJ
https://github.com/golang/go/issues/34540

**Comment by naga-aws** [comment]
Security patches are added into our new codebuild images(AL2 2.0 & Standard 3.0).
Ref : https://github.com/aws/aws-codebuild-docker-images/releases/tag/19.11.26
