### ISSUE TITLE
Add GD Extension to PHP?

### ISSUE THREAD

**Issue by Krobar** [aws/aws-codebuild-docker-images#267]
This is needed to build artifacts with composer for packages such as Drupal. It would be nice not to have to run our own container build just for this. All that is needed is:
libpng-devel added to the yum install packages
--with-gd added to the PHP configure line

**Comment by naga-aws** [comment]
Added support in aws/codebuild/amazonlinux2-x86_64-standard:3.0 and aws/codebuild/standard:4.0, as part of https://github.com/aws/aws-codebuild-docker-images/tree/20.03.13
