### ISSUE TITLE
Error building the image locally

### ISSUE THREAD

**Issue by taruntmr** [aws/aws-codebuild-docker-images#271]
Hi Team,

While trying to build the image locally, I receive the following error:

Cannot add PPA: 'ppa:~git-core/ubuntu/ppa'.
ERROR: '~git-core' user or team does not exist.
The command '/bin/sh -c set -ex     && echo 'Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/99use-gzip-compression     && apt-get update     && apt install -y apt-transport-https gnupg ca-certificates     && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF     && echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list     && apt-get update     && apt-get install software-properties-common -y --no-install-recommends     && apt-add-repository -y ppa:git-core/ppa     && apt-get update     && apt-get install git=1:2.* -y --no-install-recommends     && git version     && apt-get install -y --no-install-recommends openssh-client     && mkdir ~/.ssh     && touch ~/.ssh/known_hosts     && ssh-keyscan -t rsa,dsa -H github.com >> ~/.ssh/known_hosts     && ssh-keyscan -t rsa,dsa -H bitbucket.org >> ~/.ssh/known_hosts     && chmod 600 ~/.ssh/known_hosts     && apt-get install -y --no-install-recommends        wget python3 python3-dev python3-pip python3-setuptools fakeroot jq        netbase dirmngr bzr mercurial procps        tar gzip zip autoconf automake        bzip2 file g++ gcc imagemagick        libbz2-dev libc6-dev libcurl4-openssl-dev libdb-dev        libevent-dev libffi-dev libgeoip-dev libglib2.0-dev        libjpeg-dev libkrb5-dev liblzma-dev        libmagickcore-dev libmagickwand-dev libmysqlclient-dev        libncurses5-dev libpq-dev libreadline-dev        libsqlite3-dev libssl-dev libtool libwebp-dev        libxml2-dev libxslt1-dev libyaml-dev make        patch xz-utils zlib1g-dev unzip curl        e2fsprogs iptables xfsprogs        mono-devel less groff liberror-perl        asciidoc build-essential bzr cvs cvsps docbook-xml docbook-xsl dpkg-dev        libdbd-sqlite3-perl libdbi-perl libdpkg-perl libhttp-date-perl        libio-pty-perl libserf-1-1 libsvn-perl libsvn1 libtcl8.6 libtimedate-perl        libxml2-utils libyaml-perl python-bzrlib python-configobj        sgml-base sgml-data subversion tcl tcl8.6 xml-core xmlto xsltproc        tk gettext gettext-base libapr1 libaprutil1 xvfb expect parallel        locales rsync     && rm -rf /var/lib/apt/lists/*     && apt-get clean' returned a non-zero code: 1

I am running Docker Desktop (version 2.1.0.5) on MacOs Mojave (10.14.6)

**Comment by naga-aws** [comment]
Are your trying to build Standard:2.0 image? We are not able to simulate this issue. Please retry.

**Comment by subinataws** [comment]
@taruntmr - Is this transient issue? Did you retry you build and was the successful? We are not able to recreate this on our end. If we don't hear back from you, we'll need to close this issue and revisit once we have more information.

**Comment by lawrenceong** [comment]
For those who stumbled on this, the issue that I had is that we have a DLP solution (aka man-in-the-middle proxy) and it was interfering with the traffic.
