### ISSUE TITLE
Provide a Python3.8 image

### ISSUE THREAD

**Issue by luzfcb** [aws/aws-codebuild-docker-images#272]
AWS officially launched support for Python3.8 on AWS Lambda. 
Since the official support is launched the support to Python3.8 should be included in Codebuild images as well.

https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-now-supports-python-3-8/

https://docs.aws.amazon.com/lambda/latest/dg/python-programming-model.html

**Comment by naga-aws** [comment]
Python3.8 is supported on our new codebuild images(AL2 2.0 & Standard 3.0). 
 Ref : https://github.com/aws/aws-codebuild-docker-images/releases/tag/19.11.26

**Comment by luzfcb** [comment]
I'm curious to find out why I can't have python3.7 and python3.8 in the same docker image.

**Comment by luzfcb** [comment]
Fixed in https://github.com/aws/aws-codebuild-docker-images/pull/275

**Comment by luzfcb** [comment]
I'm curious to find out why I can't have python3.7 and python3.8 in the same docker image.
In my crazy dreams, I would like Codebuild to work similarly to Travis-ci/Gitlab-Ci/Circle-ci and have multiple versions of the Python available at the same time.

**Comment by subinataws** [comment]
@luzfcb - we did make an attempt for having the minor version side by side, but introduced regression for certain customers for specific tooling. We will get to that model in one of our next batch of releases. Although, we need to introduce certain new concepts within the runtime-versions before we can do this.
