### ISSUE TITLE
codebuild_build.sh script not working with -b option (Mac OS)

### ISSUE THREAD

**Issue by ntt2k** [aws/aws-codebuild-docker-images#276]
Please re-investigate this error, I still see this issue today using the latest version of codebuild_build.sh script, screenshot:

<img width="347" alt="Screen Shot 2019-12-03 at 3 53 41 PM" src="https://user-images.githubusercontent.com/4227421/70094179-93d41580-15e7-11ea-8694-996c934a58a5.png">

<img width="1246" alt="Screen Shot 2019-12-03 at 3 47 42 PM" src="https://user-images.githubusercontent.com/4227421/70094184-96cf0600-15e7-11ea-8840-8dec0e9fb5f7.png">

Ref old closed issue: https://github.com/aws/aws-codebuild-docker-images/issues/105

**Comment by yeuem1vannam** [comment]
It looks like this path is not correct
https://github.com/aws/aws-codebuild-docker-images/blob/413f77ee5474b3219eff86962dddf07e284c9f5b/local_builds/codebuild_build.sh#L122-L125

I manually edit as below to make it works again.
```sh
 if [ -n "$buildspec" ] 
 then 
     docker_command+=" -e \"BUILDSPEC=$buildspec\"" 
 fi
```

**Comment by ntt2k** [comment]
@yeuem1vannam Great! ... If you don't mind please make a PR for that? I'm sure AWS team will appreciate that :D

**Comment by awszhen** [comment]
Hi @ntt2k , we can not reproduce this error. Please share your `docker run` command if this issue still exists. Thanks!

**Comment by yeuem1vannam** [comment]
@awszhen 
Here is my command (which is failed with the original `code_build.sh`
```bash
#!/bin/bash

codebuild_build.sh -i amazon/aws-codebuild-local:latest \
  -a /tmp/OutputArtifact \
  -s . \
  -b buildspec.yml

```

**Comment by awszhen** [comment]
@yeuem1vannam ,
In your case, you do not need to provide source directory parameter as it will default to the current working directory:
```
codebuild_build.sh -i amazon/aws-codebuild-local:latest -a /tmp/OutputArtifact -b buildspec.yml
```

Or you can specify absolute path of the source directory:
```
codebuild_build.sh -i amazon/aws-codebuild-local:latest -s /Users/me/Workspace/my-project/ -a /tmp/OutputArtifact -b buildspec.yml
```

**Comment by ntt2k** [comment]
@awszhen 

I think the problem is not with -s option to the source directory,
but the problem is -b option if buildspec.yml file not at the top level of the source directory. 
User may want to put "buildspec.yml" file in another folder of the source directory. 
Please refer to the screenshot, also I think @yeuem1vannam already suggested how to fix it ... asking if he/she can put in the PR ... 

Hope these comments make it clear.

Thanks,

**Comment by awszhen** [comment]
@ntt2k , my local build succeeds with buildspec.yml file not at the top level of the source directory.
Can you share your docker run command? Thanks.

**Comment by ntt2k** [comment]
@awszhen I think there is a misunderstanding here. I didn't run the "docker run" command. But instead using the codebuild_build.sh script with the separate instruction here -->

https://github.com/aws/aws-codebuild-docker-images/blob/master/local_builds/README.md

**Comment by subinataws** [comment]
@ntt2k - please paste the docker run command that you see in the terminal, when you run codebuild_build.sh. Your initial screenshot had that blurred out and @awszhen is asking for that to troubleshoot better.

**Comment by subinataws** [comment]
We'll reopen if we get more info from @ntt2k.

**Comment by jhaoheng** [comment]
got the same issue.
- FAIL
    - `codebuild_build -i aws/codebuild/standard:4.0 -a artifacts -s $Source_Folder -c -b deploy/buildspec.yml`
    - `codebuild_build -i aws/codebuild/standard:4.0 -a artifacts -s $Source_Folder -c -b /deploy/buildspec.yml`
    - `codebuild_build -i aws/codebuild/standard:4.0 -a artifacts -s $Source_Folder -c -b ./deploy/buildspec.yml`
    - `codebuild_build -i aws/codebuild/standard:4.0 -a artifacts -s $Source_Folder -c -b $CODEBUILD_SRC_DIR/deploy/buildspec.yml`


- Success
    - `codebuild_build -i aws/codebuild/standard:4.0 -a artifacts -s $Source_Folder -c -b /codebuild/output/srcDownload/src/deploy/buildspec.yml`
