### ISSUE TITLE
Update Version of AWS SAM CLI to v0.32.0 or later

### ISSUE THREAD

**Issue by MattGirolami** [aws/aws-codebuild-docker-images#280]
aws/codebuild/amazonlinux2-x86_64-standard:2.0 installs the AWS SAM CLI tool at version 0.31.1 .

Version 0.32.0 of the SAM CLI introduces support for lambdas running NodeJS 12 and Python 3.8

Running a Codebuild project using aws/codebuild/amazonlinux2-x86_64-standard:2.0 on a SAM project using NodeJS 12 results in an error:

> 2019/12/06 19:47:41 Running command sam build 
>  
> Building resource 'MyLambda' 
>  
> Build Failed 
> Error: 'nodejs12.x' runtime is not supported

**Comment by subinataws** [comment]
@MattGirolami - Latest version of sam cli will be picked up when we publish a new CodeBuild image. We should have a release before the EOY, which will address this. Thanks for reporting this.

**Comment by shanhyland** [comment]
Any update on this issue?
thanks

**Comment by mahernoz-d** [comment]
Error: 'nodejs12.x' runtime is not supported

I am still getting this error with Sam v0.41

**Comment by subinataws** [comment]
@mahernoz-d - can you provide more details? Were you using a CodeBuild provided image? If so, which one? Was this on running the CodeBuild locally or was this on AWS CodeBuild?

**Comment by shanhyland** [comment]
Hello,
I was using the CodeBuild image: aws/codebuild/amazonlinux2-x86_64-standard:2.0.
It was running on AWS CodeBuild.
Thanks

**Comment by BenICE** [comment]
Same applies for aws-cli with 1.16.284, which came out in November... :-(
Would be cool to use the new features

**Comment by subinataws** [comment]
Added support in aws/codebuild/amazonlinux2-x86_64-standard:3.0 and aws/codebuild/standard:4.0, as part of https://github.com/aws/aws-codebuild-docker-images/tree/20.03.13
