### ISSUE TITLE
Lambda runs on Ruby 2.5, the "standard" images should support a runtime-version of 2.5.x

### ISSUE THREAD

**Issue by komealy** [aws/aws-codebuild-docker-images#281]
Lambda Functions in AWS currently run with a ruby runtime of 2.5.x.
Building lambda function packages that need gems need to also be built with ruby 2.5 so that the gem versions match what is required.

By pre-installing a 2.5 version, people can just set ruby: 2.5 in the runtime-version section of their buildspec and be able to build happy Ruby lambda functions. 🎉

#274  Has the fix for this and should be re-opened and included in the base image. Since AWS provides Lambda running version 2.5, having that available in the "standard" image should be required.

**Comment by subinataws** [comment]
Now that both AWS [Lambda](https://aws.amazon.com/about-aws/whats-new/2020/02/aws-lambda-supports-ruby-2-7/) and [CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html) supports Ruby 2.7, there is a version that can be used across both these services. Unfortunately, we are not able to offer Ruby 2.5 on standard images, which only offers Ruby 2.6+. If you do need to use Ruby 2.5, please consider using a custom Docker image instead.
