### ISSUE TITLE
aws/codebuild/amazonlinux2-x86_64-standard:2.0 misleading build log for docker runtime version

### ISSUE THREAD

**Issue by philn5d-ar** [aws/aws-codebuild-docker-images#283]
From the following file:
https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/2.0/runtimes.yml

the following line:
`- echo "Specifying docker version in buildspec is deprecated. Using docker $DOCKER_VERSION ."`

causes confusion when reviewing the build output, especially of a failed build.

Repro:

Make a buildspec that includes this runtime version:
```
phases:
  install:
    runtime-versions:
      docker: 18
```
Run a build that uses this buildspec and aws/codebuild/amazonlinux2-x86_64-standard:2.0.

Check the build logs, it'll have the confusing message.

**Comment by subinataws** [comment]
@philn5d-ar - Thanks for calling that out. This will be addressed in the next few days. Once that update is in place, you shouldn't need to specify the docker version in the "runtime-versions". We'll implicitly picking up the latest available version of docker for your builds.

**Comment by philn5d-ar** [comment]
@subinataws I wondered about that. It'll make the buildspec simpler for sure, although ours is already fairly simple as it is. Thanks!

**Comment by zygimantas** [comment]
No, that does not make it simple:

[Container] 2020/01/06 16:32:14 Phase context status code: YAML_FILE_ERROR Message: This build image requires selecting at least one runtime version. 

What if docker is the only runtime I need?

**Comment by subinataws** [comment]
@zygimantas - We are adding an implicit runtime version selection in buildspec, which would be the new default. If you specify a runtime-version, that version will be picked up. If you do not specify a specific runtime-version, then the latest version for the runtime will be selected by default. 

For Docker, you will only need to select the "privileged" mode in the Project setting, once the updates fully roll out.

**Comment by zygimantas** [comment]
I have priviledged mode enabled and I get an error, mentioned in a previous post, if I omit runtime setting in buildspec

**Comment by subinataws** [comment]
@zygimantas - The update hasn't rolled out yet. I'm explaining the future state. For now, you will need to use "docker: 18" and privileged mode, until this bug is fixed.

**Comment by zygimantas** [comment]
thanks

**Comment by elonderin** [comment]
plz be sure to update also the docs: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

**Comment by aditynar** [comment]
Hi there, this is Aditya from AWS CodeBuild. This update has been rolled out. You can now leave the "runtime-versions" section empty and have latest runtime versions selected by default. You shouldn't encounter the following error anymore:

`[Container] 2020/01/06 16:32:14 Phase context status code: YAML_FILE_ERROR Message: This build image requires selecting at least one runtime version.`
