### ISSUE TITLE
Support CodeBuild local on Arm

### ISSUE THREAD

**Issue by canada4663** [aws/aws-codebuild-docker-images#284]
Hello - I am getting an error when running codebuild_build.sh:

```
./codebuild_build.sh -i aws/codebuild/amazonlinux2-aarch64-standard:1.0 -a /tmp -s /home/ubuntu/jetsonNanoBuilder
Build Command:

docker run -it --privileged -v /var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=aws/codebuild/amazonlinux2-aarch64-standard:1.0" -e "ARTIFACTS=/tmp" -e "SOURCE=/home/ubuntu/jetsonNanoBuilder" -e "INITIATOR=ubuntu" amazon/aws-codebuild-local:latest

standard_init_linux.go:211: exec user process caused "no such file or directory"
```

I am able to verify that I can launch the locally build Codebuild container and poke around, I also removed the entry point step per the instructions.

Environment: Ubuntu 18 running on AWS a1 instance

**Comment by kitkit201** [comment]
+1 for this feature request . I am still seeing a problem trying to build locally on ARM so i can test

**Comment by jasonrandrews** [comment]
Now that Graviton2 supports CodeBuild I recommend to get an Arm version of amazon/aws-codebuild-local:latest on Docker Hub. I found the best way to do a local CodeBuild test is using a Mac with M1 and install Docker Desktop for M1. It has the ability to run the x86 aws-codebuild-local and then I specify an Arm container using the -i option to codebuild_build.sh

**Comment by subinataws** [comment]
Supported by https://github.com/aws/aws-codebuild-docker-images/pull/441.
