### ISSUE TITLE
Ability to alter docker daemon options?

### ISSUE THREAD

**Issue by brianbianco** [aws/aws-codebuild-docker-images#29]
We run our own docker registry in our VPC.  Unfortunately in order to push and pull images to it from codebuild we need to add the --insecure-registry flag to docker daemon.  It would be great if somehow you could pass along options to the docker daemon.

I've tried killing all running docker and containerd instances and restarting them with new options.  It's not going well so far.

**Comment by clareliguori** [comment]
What is the reason for turning on --insecure-registry?  Self-signed certificate?

CodeBuild supports installing self-signed certs into the build environment for you.  The feature was originally intended for git repos with self-signed certs, but it should also work for Docker pulls if Docker picks up the installed certs (I haven't tested this).
https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-self-signed-certificate

Instructions for how to grab the public cert from your server are on this page:
https://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-enterprise.html

**Comment by brianbianco** [comment]
The reason was self signed certs :)

I was able to do some wonderful voodoo to kill docker and restart it with the docker daemon options I wanted.  It just seems to me like maybe the ability to alter the docker daemon start up options could be pretty useful when using dind to build images.

Thanks, I'll look into just installing self signed certs into codebuilds build env though.  That solves my immediate problem quicker than killing docker and restarting it with my desired options.

**Comment by brianbianco** [comment]
Closing this ticket as I've bypassed my issue for the time being. I still think this functionality would be useful
