### ISSUE TITLE
Image fails

### ISSUE THREAD

**Issue by vmurillo** [aws/aws-codebuild-docker-images#290]
By building image ubuntu/standard/2.0 using the command:

`> docker build -t aws/codebuild/standard:2.0 .`

This command ends with the following error:

`
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Makefile:761: recipe for target 'ext/fileinfo/libmagic/apprentice.lo' failed
make: *** [ext/fileinfo/libmagic/apprentice.lo] Error 1
`

**Comment by subinataws** [comment]
@vmurillo - Can't reproduce this issue. Please provide more details. I assume you retried and this error persists? What OS, Docker version are you using?
