### ISSUE TITLE
Feature Request: Addition of sonar-scanner

### ISSUE THREAD

**Issue by vibhuyadav** [aws/aws-codebuild-docker-images#293]
The addition of sonar-scanner in the cli can cut down a lot of lines in the buildspecs. Adding env var can supplement it. Example CODEBUILD_SONAR_HOST_URL && CODEBUILD_SONAR_LOGIN

**Comment by subinataws** [comment]
Thanks for the feature request. Sonar-scanner is GPL v3: https://github.com/SonarSource/sonar-scanner-cli/blob/master/LICENSE.txt. Unfortunately, this isn't something we can add to our vended image.
