### ISSUE TITLE
Ruby 2.6.5

### ISSUE THREAD

**Issue by thomasvds** [aws/aws-codebuild-docker-images#295]
Hello, 

Ruby 2.6.5 has been released since Oct 1, 2019. Could you have it included in the images?

https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/

Thanks!

**Comment by thomasvds** [comment]
If anyone is faced with the same issue: I ended up using a Docker image with the right Ruby version instead.

**Comment by subinataws** [comment]
Added support in aws/codebuild/amazonlinux2-x86_64-standard:3.0 and aws/codebuild/standard:4.0, as part of https://github.com/aws/aws-codebuild-docker-images/tree/20.03.13
