### ISSUE TITLE
Long Provisioning Times on aws/codebuild/amazonlinux2-x86_64-standard:1.0

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-codebuild-docker-images#296]
We are experiencing long provisioning times using the image aws/codebuild/amazonlinux2-x86_64-standard:1.0

I opened a support ticket and was told I "that CodeBuild service team confirmed that builds using image "aws/codebuild/amazonlinux2-x86_64-standard:1.0" can cause significant increase in the build time due to an internal change (they are in process of deprecating the image "aws/codebuild/amazonlinux2-x86_64-standard:1.0"). "

I am compiling .netcore2.1 for aws lambda (does not support 3.x yet).

I changed to "aws/codebuild/amazonlinux2-x86_64-standard:2.0" but that does not support the "    runtime-versions" in the buildspec (specifically dotnet: 2.2).

It does seem to have .net core 3.x installed, but even with some trials of trying to build and test with "--framework netcoreapp2.1", I seemed to get painted into different corners.

Additionally I was told "One of the most common ways that the provisioning stage of a CodeBuild execution can be sped up is to enable Docker layer caching".

I don't see how using a Docker Layer Cache will speed up the PROVISIONING time and am hestitant to try to make this change as it would require quite a bit of change.

Once the build is "Provisioned" everything is very fast.  But some of the Provisioning is taking 3-5 minutes whilst the rest of the phases are cumulative less than 90 seconds. 

Can anyone confirmation or advise on the above?

**Comment by subinataws** [comment]
@hounddog22030 - The issue that you were facing was due to standard:1.0 image no longer being cached on the build fleet for a few hours. When possible, please use the latest version of the CodeBuild provided image[1], which are the only ones guaranteed to be cached on the build fleet and lower the provisioning time.

[1]: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

**Comment by asmontas-i** [comment]
Hi, I haven't used CodePipeline/CodeBuild much, however I'm constantly experiencing long provisioning times (around 5-6mins) with latest images:
- aws/codebuild/amazonlinux2-x86_64-standard:3.0
- aws/codebuild/standard:4.0

Is this caused by some kind of a misconfiguration on my side or this is normal behaviour  ?

**Comment by subinataws** [comment]
@asmontas-i - which compute type and AWS Region did you experience 5-6 mins provisioning delay when using the CodeBuild provided image?

**Comment by asmontas-i** [comment]
eu-central-1 region and build.general1.small compute type. 

However, when switched to use aws/codebuild/standard:3.0 instead of latest standard:4.0, provisioning phase time got significantly reduced from 5-6min to around 30s.

**Comment by subinataws** [comment]
@asmontas-i - could you please send me the buildARN for slow provisioning to subinm@amazon.com? Using the latest CodeBuild provided images should have been 15 secs or lower for provisioning.

**Comment by hounddog22030** [comment]
> @nickfreemandesign - Some of the docker layers for the new standard:6.0 and the latest AL2 image isn't cached yet, leading to the provisioning delays. Team is working on a fix for the regression identified and will roll that forward the fix, after this is tested.

When you say "isn't cached yet", I envision that there are physical machines that haven't yet seen/used the "new standard:6.0 and the latest AL2 image".  I find that difficult to swallow.  If "isn't cached yet" because some scripts/process haven't been run to explicitly bring them down, that I can consider a possibility.  Are they "isn't cached yet" because some scripts/process haven't been run yet?  It doesn't seem like some software change would need to be deployed in order to make the servers cache a new version of the layers/image.

**Comment by jakubadamw** [comment]
> @nickfreemandesign - Some of the docker layers for the new standard:6.0 and the latest AL2 image isn't cached yet, leading to the provisioning delays. Team is working on a fix for the regression identified and will roll that forward the fix, after this is tested.

Is there an ETA for this, please?

**Comment by hounddog22030** [comment]
Holy Cow...

![image](https://user-images.githubusercontent.com/2836974/179523045-287768ee-3be5-4287-b3e0-5102c063f3ac.png)

**Comment by NinoMaj** [comment]
> @nickfreemandesign - Some of the docker layers for the new standard:6.0 and the latest AL2 image isn't cached yet, leading to the provisioning delays. Team is working on a fix for the regression identified and will roll that forward the fix, after this is tested.

@subinataws any updates on this? We are still seeing long provision times for ~50% of the builds.

**Comment by hounddog22030** [comment]
We switched to GitHub actions. We reduced our build and deployment time from 26 minutes on CodePipeline/CodeBuild to 8 minutes on GitHub .  It’s way faster, there’s very little latency between steps and there’s a ton of reusable components. We’re still deploying to AWS.
