### ISSUE TITLE
Docker build failing for /ubuntu/standard/3.0

### ISSUE THREAD

**Issue by eric-davis** [aws/aws-codebuild-docker-images#298]
I have cloned the repo and attempted to build the ubuntu/standard/3.0 image via the following:

`docker build -t aws/codebuild/standard:3.0 .`

The build process fails during the `Install Android SDK manager` portion of the Dockerfile script with a "no such file or directory" error at approximately line 370.

Any insights or workarounds? I am running this build on Windows with Docker Desktop version 2.1.0.5 running in Linux mode.

**Comment by subinataws** [comment]
@eric-davis - I couldn't reproduce this error. Was this a transient error that you got? Have you tried it since and did that succeed?
