### ISSUE TITLE
Standard image that supports Python 3.6 in addition to later versions

### ISSUE THREAD

**Issue by dcanfield40** [aws/aws-codebuild-docker-images#299]
I'm working for a client where we need support of Python 3.6 and forward (3.7 and 3.8) but also Node 10 & 12 and Java 8 & 11 in a single managed image.

So, it really could be al2:aarch64:standard:1.0 but with 3.6 also.

**Comment by subinataws** [comment]
@dcanfield40 - our goal is to support the tip version of the runtimes that are available, when we are building these images. At this time, we are not considering supporting older versions. You may consider modifying [runtimes.yml](https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/aarch64/standard/1.0/runtimes.yml) and adding an entry for python 3.6 and have it installed inline. This is something that some of our customers are already doing to extend the specific runtimes or tools that they would like to have in the CodeBuild provided images.
