### ISSUE TITLE
Add eksctl to the images

### ISSUE THREAD

**Issue by vkoukoutsas** [aws/aws-codebuild-docker-images#300]
It would be great if **eksctl** was also added in the images and we could use it out of the box during our build executions in CodeBuild.

Is there a plan to add it in future versions?

**Comment by subinataws** [comment]
Thanks for the feature request. We'll consider this in a future release.

**Comment by awszhen** [comment]
This is now supported in the latest version of the images in CodeBuild. For example: https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile#L124
