### ISSUE TITLE
Go 1.14 Support

### ISSUE THREAD

**Issue by nc-wittj** [aws/aws-codebuild-docker-images#304]
Go 1.14 has [been released](https://twitter.com/golang/status/1232421783548067840)! 🎉

**Comment by subinataws** [comment]
Added support in aws/codebuild/amazonlinux2-x86_64-standard:3.0 and aws/codebuild/standard:4.0, as part of https://github.com/aws/aws-codebuild-docker-images/tree/20.03.13
