### ISSUE TITLE
AWS Documentation Outdated

### ISSUE THREAD

**Issue by DanRoestorf** [aws/aws-codebuild-docker-images#305]
The instructions on first page most users looking to use this solution land on is outdated.

https://aws.amazon.com/blogs/devops/announcing-local-build-support-for-aws-codebuild/

After cloning
```
git clone https://github.com/aws/aws-codebuild-docker-images.git
```

The first step in the guide does not work anymore.
```
cd aws-codebuild-docker-images
cd ubuntu/java/openjdk-8
docker build -t aws/codebuild/java:openjdk-8 .
```

These docs should be updated, or at least link to updated documentation to simplify the experience for first time users.

**Comment by subinataws** [comment]
This is fixed now. Thanks for reporting it.
