### ISSUE TITLE
Local build with multiple input sources

### ISSUE THREAD

**Issue by gandroz** [aws/aws-codebuild-docker-images#309]
I would like to run tests on a python project, first locally. My tests need some test files to run but they are not directly in the source. I managed to add a secondary source in the command 

`./codebuild_build.sh -i aws/codebuild/standard:3.0 -a ./artifacts -s ~/src/python_project -s source_1:~/testdata/python_project_test_files`

which translates into a command

`docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=aws/codebuild/standard:3.0" -e "ARTIFACTS=/home/me/src/aws_local_build/artifacts" -e "SOURCE=/home/me/src/python_project" -e "SECONDARY_SOURCE_1=source_1:/home/me/testdata/python_project_test_files" -e "INITIATOR=me" amazon/aws-codebuild-local:latest`

how to do the same but with an S3 bucket as a secondary source ?

**Comment by awszhen** [comment]
Hi @gandroz , local build agent is designed to test and debug locally on desktop. Downloading sources from S3/GitHub is out of the scope of our local build agent support.
