### ISSUE TITLE
Support for Latest Ruby - 2.7.0

### ISSUE THREAD

**Issue by whithajess** [aws/aws-codebuild-docker-images#310]
[Ruby 2.7.0 was released in December](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/)

Would be good to have an idea of how far away in the pipeline this is, for our tests we run with the official container for speed reasons and if `aws-codebuild-docker-images` is to far behind we will have to start using custom containers reducing the speed of our builds.

What would help get these to move faster in the future?

Few options I would be happy to do:
- Start up an issue as the version comes out
- PR the change
- Put pressure on our TAM

I note 2.6.5 - #295 is also still waiting

**Comment by subinataws** [comment]
Added support in aws/codebuild/amazonlinux2-x86_64-standard:3.0 and aws/codebuild/standard:4.0, as part of https://github.com/aws/aws-codebuild-docker-images/tree/20.03.13
