### ISSUE TITLE
Readme improvement propositions

### ISSUE THREAD

**Issue by cyrilhamidechi** [aws/aws-codebuild-docker-images#312]
Hello,

First of all thanks for this very useful tool.

As user of this tool since few weeks now I'd like to submit few improvements about the readme:
- `-c` option [is required](https://github.com/aws/aws-codebuild-docker-images/blob/master/local_builds/codebuild_build.sh#L140) for the `-p` option to work
- `env > secrets-manager > key` requires ARN instead of also supporting name (as in-cloud CodeBuild)
- Maybe a scripted quick install?

Quick install proposal
```
	git clone https://github.com/aws/aws-codebuild-docker-images.git
	cd aws-codebuild-docker-images/ubuntu/standard/3.0/
	docker build ./ -t aws/codebuild/standard:3.0
	docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false
	cp codebuild_build.sh /usr/local/bin/codebuild_build
```

**Comment by awszhen** [comment]
Hi @cyrilhamidechi , these suggestions look good to me. Please submit pull request. Thanks!

**Comment by subinataws** [comment]
Closing this in favor of https://github.com/aws/aws-codebuild-docker-images/issues/252, which lists broader set of improvements. Feel free to submit a PR for this specific call out.
