### ISSUE TITLE
Update PowerShell Core version to 7.x+

### ISSUE THREAD

**Issue by LawrenceHwang** [aws/aws-codebuild-docker-images#314]
Hello team,

Please kindly update Update PowerShell Core in the ubuntu images from 6.2.1 to 6.2.4.

You can find the PowerShell Core 6.2.4 release on their page: https://github.com/PowerShell/PowerShell/releases/tag/v6.2.4

Thank you,

Lawerence

**Comment by subinataws** [comment]
@LawrenceHwang - Thanks for submitting the request. What was the specific improvement between 6.2.1 and 6.2.4 that you were interested in? We currently have a release in flight, but that will not be updating powershell version. We generally bias towards major and minor version updates, unless the patch version had a security update.

**Comment by LawrenceHwang** [comment]
Hello @subinataws ,

Thank you for the quick response. There's only minor improvements I am looking for between 6.2.1 and 6.2.4. In fact, It'd be great for to updat the PowerShell version to the most recent version: `v7.0.0`, which was GA'd on Feb 26th, 2020.

Appendix:
- https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7
- https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0
- https://github.com/PowerShell/PowerShell/releases/tag/v6.2.2
- https://github.com/PowerShell/PowerShell/releases/tag/v6.2.3
- https://github.com/PowerShell/PowerShell/releases/tag/v6.2.4

**Comment by subinataws** [comment]
Yes, we'll pick up the new major version with the next release. Any tooling update (e.g.: powershell), will only be picked up when there is a language runtime version update (major or minor).

**Comment by LawrenceHwang** [comment]
Thank you. I will update the title of this issue as well.

**Comment by KevinMarquette** [comment]
I am also looking forward to seeing PS 7.0.0 available in the ubuntu images.

**Comment by austoonz** [comment]
Is there a scheduled release coming up for this? I'm keen to have PowerShell 7.x available without having to install it myself in the buildspec.

**Comment by subinataws** [comment]
CodeBuild's latest Windows image, based on WS2019, has powershell 7.0.2 pre-installed. Linux versions will get it with next major version bump. We aren't planning on updating 6.x to 7.x on existing versions to avoid any backwards incompatibility issues.

**Comment by subinataws** [comment]
Now [available](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile#L186) in [standard:5.0](https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.01.08).
