### ISSUE TITLE
Codebuild installing node12.x instead of 10.x

### ISSUE THREAD

**Issue by anubha16** [aws/aws-codebuild-docker-images#319]
Image
aws/codebuild/amazonlinux2-x86_64-standard:2.0

testspec.yaml

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo 'running install' 

Log output. There seems to be a typo in command n $NODE_10_VESION below in the logs

[Container] 2020/03/18 23:33:28 Waiting for agent ping
2 | [Container] 2020/03/18 23:33:30 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2020/03/18 23:33:31 Phase is DOWNLOAD_SOURCE
4 | [Container] 2020/03/18 23:33:31 CODEBUILD_SRC_DIR=/codebuild/output/src442626046/src
5 | [Container] 2020/03/18 23:33:31 YAML location is /codebuild/output/src442626046/src/testspec.yaml
6 | [Container] 2020/03/18 23:33:31 Processing environment variables
7 | [Container] 2020/03/18 23:33:31 Selecting 'nodejs' runtime version '10' based on manual selections...
8 | [Container] 2020/03/18 23:33:31 Running command echo "Installing Node.js version 10 ..."
9 | Installing Node.js version 10 ...
10 |  
11 | [Container] 2020/03/18 23:33:31 Running command n $NODE_10_VESION
12 | stty: standard input: Inappropriate ioctl for device
13 | clear: terminal attributes: No such device or address
14 |  
15 |  
16 | node/10.19.0
17 | ο node/12.16.1
18 |  
19 | Use up/down arrow keys to select a version, return key to install, d to delete, q to quitstty: standard input: Inappropriate ioctl for device
20 | installed : v12.16.1 (with npm 6.13.4)
21

**Comment by naga-aws** [comment]
Thanks for posting it. We addressed it in the latest release.
