### ISSUE TITLE
Latest standard images with .NET Core 3.1 need to set the DOTNET_ROOT environment variable

### ISSUE THREAD

**Issue by normj** [aws/aws-codebuild-docker-images#321]
In the latest ubuntu and AL2 images .NET Core installation location changed from the default `/usr/share/dotnet` to `/root/.dotnet`. Build scripts that use .NET Core Global Tools like our [Amazon.Lambda.Tools](https://github.com/aws/aws-extensions-for-dotnet-cli#aws-lambda-amazonlambdatools) will fail to run looking for the .NET runtime. Here is an example of the errors.

```
[Container] 2020/03/19 23:31:58 Running command ~/.dotnet/tools/dotnet-lambda --help
--
61 | A fatal error occurred. The required library libhostfxr.so could not be found.
62 | If this is a self-contained application, that library should exist in [/root/.dotnet/tools/.store/amazon.lambda.tools/3.3.1/amazon.lambda.tools/3.3.1/tools/netcoreapp2.1/any/].
63 | If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
64 |  
65 | The .NET Core runtime can be found at:
66 | - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.18.04-x64
67 |  
68 | [Container] 2020/03/19 23:31:58 Command did not exit successfully ~/.dotnet/tools/dotnet-lambda --help exit status 131
69 | [Container] 2020/03/19 23:31:58 Phase complete: INSTALL State: FAILED
```

If .NET Core is going to be installed in a non-default location then the `DOTNET_ROOT` environment variable needs to be set to `/root/.dotnet`. Here is the snippet I'm using to workaround in my buildspec.yml file.

```

version: 0.2

env:
    variables:
        DOTNET_ROOT: /root/.dotnet

phases:
    install:
        runtime-versions:
            dotnet: 3.1
```

**Comment by boonew2** [comment]
Also effects `standard:3.0` with dotnet `3.0`

**Comment by aditynar** [comment]
Hi, this is Aditya from CodeBuild. Could you please try to rerun the build? We've fixed the environment variable setting on our end.

**Comment by normj** [comment]
Verified it works correctly now. Awesome turnaround on getting this fixed CodeBuild team.

**Comment by candrade** [comment]
> Hi, this is Aditya from CodeBuild. Could you please try to rerun the build? We've fixed the environment variable setting on our end.

Has this been corrected for 2.1 environments?

**Comment by naga-aws** [comment]
Its corrected on all supported images.

standard 2.0
standard 3.0
standard 4.0
amazonlinux2-x86_64-standard:1.0
amazonlinux2-x86_64-standard:2.0
amazonlinux2-x86_64-standard:3.0

**Comment by Lanayx** [comment]
Just got this issue on standard 3.0 when running dotnet lambda package, fortunately found this thread and setting `DOTNET_ROOT: /root/.dotnet` helped

**Comment by scotttelle** [comment]
@naga-aws I am also seeing this error with amazonlinux2-x86_64-standard:2.0 I will try setting DOTNET_ROOT.

**Comment by scotttelle** [comment]
@naga-aws @aditynar can we have this issue reopened since it's still happening with amazonlinux2?

**Comment by naga-aws** [comment]
@scotttelle : The environment variable DOTNET_ROOT will be exported when the dotnet runtime is selected on the buildspec. Also please note that AL2:2.0 has dotnet 3.0 and AL2:3.0 has dotnet 3.1. If you still face this issue, please post the steps to simulate.

**Comment by scotttelle** [comment]
@naga-aws thank you. I am using sam to deploy, so I needed the python runtime (to run pip to update sam) and it's worked until now. Adding the dotnet runtime has resolved this issue. Thank you!

**Comment by Lanayx** [comment]
Same thing for me, I haven't specified any runtime at all, so while it was optional a week ago now has become a required option which broke the pipeline for me.
