### ISSUE TITLE
python installations do not contain shared objects

### ISSUE THREAD

**Issue by 2ps** [aws/aws-codebuild-docker-images#324]
The codebuild images do not install the python shared objects needed for libraries that require native support, such as mysqlclient.  The shared objects can be installed using `CONFIGURE_OPTS=--enable-shared`

**Comment by burritoIand** [comment]
hey I just started receiving the same error and my builds are failing. Is this something I can run or enable through my codebuild cloudformation template, or is this a bug?

**Comment by 2ps** [comment]
This is a bug--you can work around it by using pyenv to reinstall python in your buildspec.yml  I've already raised the issue with AWS support but they claim that this is a "feature-request" and not a "bug."  

The below was our workaround but it adds a couple of minutes to the build time.

```
CONFIGURE_OPTS=--enable-shared pyenv install 3.7.5
pyenv global 3.7.5
```

We got an error when trying to reinstall / install over 3.7.6, and you can replace `3.7.5` with whatever version you want to use so long as it isn't one of the default installed ones (3.7.6, 3.8.1)

**Comment by burritoIand** [comment]
@2ps thank you for this suggestion! going to try it out now. I don't see how this is a feature request when it worked as recently as a month or two ago, and one of their own projects that I also use is now failing (aws-crt-python).

**Comment by subinataws** [comment]
@2ps @burritoIand - This is a regression on our end. We'll get this fixed, but the update is likely going to take some time to reflect. In the previous version, there was https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/3.0/Dockerfile#L155-L157 and the newer version, but python versions weren't being installed side by side. In the newer version, multiple python versions are installed side by side, but the configuration option for shared was dropped (regression).

In the meantime, you can use a pinned version of the image from before the latest update which is missing this option. For example: "aws/codebuild/standard:3.0-19.11.26" instead of "aws/codebuild/standard:3.0".

**Comment by burritoIand** [comment]
@subinataws thank you! glad to know it wasn't something I accidentally changed on my end :) Appreciate the quick response.

**Comment by burritoIand** [comment]
@2ps using `aws/codebuild/standard:3.0-19.11.26` with python 3.8 resolved issue. Probably unrelated but I also had to update all my lambda function runtimes to 3.8 from 3.7 or it seemed to have same issue where [aws-crt-python](https://github.com/awslabs/aws-crt-python/issues/137) failing to build correctly.

**Comment by 2ps** [comment]
@subinataws :  have y'all already reviewed my PR for the 4.0 container (which we are already using)?

**Comment by 2ps** [comment]
@subinataws :  bump.

**Comment by subinataws** [comment]
@2ps - CodeBuild's release process doesn't get triggered from this repo. So merging your PR isn't going to fix this on CodeBuild on AWS cloud. Thanks for your contribution. Internal release process is underway which will include this change. Once the release is live in all AWS Regions, we'll push the Dockerfile update to this repo.

**Comment by burritoIand** [comment]
on the plus side, this forced me to upgrade to python 3.8, and now I can use the walrus operator := :)

**Comment by 2ps** [comment]
@subinataws :  understood.  Thank you for sharing the update--we really appreciate the communication with the community.  We'll keep an eye out here for any updates.

**Comment by subinataws** [comment]
This issue is fixed now. Resolving.
