### ISSUE TITLE
libpq-dev 9.3.20-* unavailable

### ISSUE THREAD

**Issue by SkxNMDI5** [aws/aws-codebuild-docker-images#33]
Hi,

references to libpq-dev=9.3.20-* don't work anymore as the last available package is 9.3.21-*

Sample of errors during builds :

```sh
Version '9.3.20-*' for 'libpq-dev' was not found
```

**Comment by taoyong-ty** [comment]
Hi SkxNMDI5,

Thank you for bring this to our attention. 

We will get the fix through our internal release process; and then merge the fix in.

**Comment by clareliguori** [comment]
Fixed by 47054bc
