### ISSUE TITLE
codebuild_build.sh -e does not override buildspec environment variables

### ISSUE THREAD

**Issue by dvogel** [aws/aws-codebuild-docker-images#332]
I have a buildspec file with:

```
env:
  variables:
    PUSH_TO_ARTIFACTORY: NO
```

I have an env file with:

```
PUSH_TO_ARTIFACTORY=YES
```

When I run this command:

```
./codebuild_build.sh -i aws/codebuild/standard:3.0 -b my-app/buildspec.yml -e my.env -a /tmp/ -c
```

In the build script the environment variable evaluates to `NO`. Removing that environment variable from the buildspec causes it to evaluate to `YES`. I would expect it the values in the `-e` environment variable file to override the buildspec environment variable values akin to the codebuild project variable defaults overriding the buildspec environment variable values.

**Comment by awszhen** [comment]
@dvogel , please use latest version of the local agent. SHA: bd69dbcdc9b3da66fd93de0b6d45534086367d6b48d3536d0248a01a459fb7e4
