### ISSUE TITLE
Support For Latest Ruby Patch Version - 2.7.1

### ISSUE THREAD

**Issue by whithajess** [aws/aws-codebuild-docker-images#333]
[Ruby 2.7.1 released](https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/)

Has security fixes as well as other changes.

**Comment by subinataws** [comment]
This is now supported in the latest version of the images in CodeBuild. For example: https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile#L236
