### ISSUE TITLE
Support for Windows .NET Framework build image

### ISSUE THREAD

**Issue by ryandzink** [aws/aws-codebuild-docker-images#338]
I realize this may be an outlandish request given the year we're in but wondering if there is any plan for a curated image that supports builds for legacy applications that run .NET framework (3.5/4.8). I have recently migrated a bunch of applications out of TFS to use CodeBuild with a custom docker image that rolls in the .NET framework prerequisites but the provisioning times are pretty painful (12 minutes minimum). 

There are quite a few blog posts (including this one on the AWS blog: https://aws.amazon.com/blogs/devops/extending-aws-codebuild-with-custom-build-environments-for-the-net-framework/) on how various people have accomplished this, so it does seem like a somewhat common request. I don't know if there are broader licensing issues that prevent this from happening, however.

**Comment by subinataws** [comment]
@ryandzink - Yes, we can't offer the proprietary MSBuild targets that support ASP.NET or similar. Microsoft's licensing terms do not allow for those targets to be used outside of their own ecosystem. This is unfortunately not something we can address at this time.
