### ISSUE TITLE
[feature request] pushing codebuild images to ecr

### ISSUE THREAD

**Issue by eightnoteight** [aws/aws-codebuild-docker-images#339]
currently codebuild images are not pushed to a public location, but only the code is published in this repo, 
if someone needs to extend the default codebuild but also utilize the default layer caching behaviour of the base codebuild docker image they can't do it because building from scratch using the dockerfile would build new set of layers. it would be great if these images are pushed to an ecr continously so that a custom image built by us will use the cache

a custom image would look like
```
FROM aws/codebuild/standard:3.0
RUN apt install custom-tool
```

something like that all the layers from standard:3.0 would be cached and only the custom tool layer would be downloaded, but this kind of functionality is not possible currently because the images are not being pushed to a public location

**Comment by subinataws** [comment]
Thanks for the feature request. This is duplicate o fhttps://github.com/aws/aws-codebuild-docker-images/issues/152.

**Comment by phancox** [comment]
But #152 was closed by raising this feature request.  We're going around in circles.
