### ISSUE TITLE
Local builds fail on geckodriver download

### ISSUE THREAD

**Issue by omahn** [aws/aws-codebuild-docker-images#340]
While debugging an issue with one of our customers we noticed that it wasn't currently possible to consistently build the `ubuntu/standard/2.0` container reliably.

We narrowed this down to the download of `geckodriver` failing due to some of the responses from the GitHub API getting returned in a single line of text rather than multiple lines. This caused the `RUN` command in the `Dockerfile` to fail as it uses `grep`, `cut` and `tr` to isolate the line with the correct download URL.

This is the output from a failed build:

```
Step 50/53 : RUN set -ex     && curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep browser_download_url | grep linux64.tar.gz | cut -d : -f 2,3 | tr -d ' "' | wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi -     && tar -xzf /tmp/geckodriver-latest-linux64.tar.gz -C /opt     && rm /tmp/geckodriver-latest-linux64.tar.gz     && chmod 755 /opt/geckodriver     && ln -s /opt/geckodriver /usr/bin/geckodriver     && geckodriver --version
 ---> Running in 864219e0cb7d
+ curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest
+ grep browser_download_url
+ + cutgrep linux64.tar.gz -d
 : -f 2,3
+ tr -d  "
+ wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi -
+ tar -xzf /tmp/geckodriver-latest-linux64.tar.gz -C /opt

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c set -ex     && curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep browser_download_url | grep linux64.tar.gz | cut -d : -f 2,3 | tr -d ' "' | wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi -     && tar -xzf /tmp/geckodriver-latest-linux64.tar.gz -C /opt     && rm /tmp/geckodriver-latest-linux64.tar.gz     && chmod 755 /opt/geckodriver     && ln -s /opt/geckodriver /usr/bin/geckodriver     && geckodriver --version' returned a non-zero code: 2
```

If the `curl` JSON is returned over multiple lines then it all works fine but otherwise we see this failure. I think the correct solution here is to use `jq` to isolate the JSON element with the correct download URL. I'll provide a PR shortly that makes this change.

**Comment by subinataws** [comment]
@omahn - Thanks for the contribution!
