### ISSUE TITLE
AWSCLI version 1.18 not available in Windows Base 2.0 image

### ISSUE THREAD

**Issue by ajatakia** [aws/aws-codebuild-docker-images#342]
Hello,

I need to be able to use awscli version 1.18 which would be compatible with Python3.7. Upon executing aws --version I get below output:

![image](https://user-images.githubusercontent.com/492304/80666126-56c26100-8a69-11ea-966b-0b73ed4ced1f.png).

**Comment by subinataws** [comment]
@ajatakia - Thanks for reporting this. We'll get this fixed. In the meantime, you can update the aws-cli version by specifying the following command in your buildspec. Replace to the appropriate version that you need:

choco install -fy awscli --version <version_you_need>

**Comment by subinataws** [comment]
@ajatakia - you can use Windows Server 2019 which has AWS cli v2 in it. Existing Windows 1.0 and 2.0 images that are based on WS2016 images will soon be in a "not actively maintained state".
