### ISSUE TITLE
Node 12 not available on all Ubuntu 18.04 images

### ISSUE THREAD

**Issue by mousedownmike** [aws/aws-codebuild-docker-images#343]
[The documentation says: nodejs: 12 is available on "All Ubuntu 18.04 images"](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html) but it does not appear to be available on the standard/2.0.

**Comment by subinataws** [comment]
@mousedownmike - Thanks for reporting that  It is only available in newer versions of the docker image. We'll fix the docs. We have no plans to add this to previous versions of the standard images like standard:2.0.

**Comment by mousedownmike** [comment]
That sounds totally reasonable, closing.
