### ISSUE TITLE
TOX find python3.6 when I use python 3.8

### ISSUE THREAD

**Issue by JohnPreston** [aws/aws-codebuild-docker-images#346]
For some reason, this used to pass just fine a few weeks ago but now my tests with tox just fail because it finds python3.6 but then it fails creating the virtualenv and nothing I tried helped to fix that situation, so for now I have removed my tox tests and simply run pytest.

But this didn't use to happen before.

I am using aws/codebuild/standard:3.0 (AL2). I also use the local codebuild implementation so I don't spend hours in the actual service, and it passes just fine with the locally built from source aws standard 3.0 image.

Any idea why there is a difference between local and in the service ? why is there py3.6 installed anyway when the install should only contain 3.8?

**Comment by subinataws** [comment]
@JohnPreston - Did you try setting the path for tox? Using aws/codebuild/amazonlinux2-x86_64-standard:3.0 shows python 3.8, not sure how your tox configuration is picking up py3.6. Haven't used tox much, but isn't that specified in envlist?

**Comment by JohnPreston** [comment]
Hi. Sorry I didn't respond earlier :/
I know it shows to only have python3.8 in principle, but if you run `find / -name python3.6* -type executable ` you will find a bunch of python3.6 executables which even if you unlink all these, tox still finds there are traces of python3.6
I had very short logs retention so I don't have the logs again but I will revert my buildspec.yml to run it again and show the outputs if that's of help.
