### ISSUE TITLE
build/output/tmp/script.sh: 4: /codebuild/output/tmp/script.sh: 'genhtml' not found

### ISSUE THREAD

**Issue by odedNaftali** [aws/aws-codebuild-docker-images#348]
Hello

I'm running unit tests on standard4.0 image. The unit tests run ok and produce coverage files, but when I run the command 'genhtml' I receive the error mentioned above -  'genhtml' not found

Attempts to install lcov from my yml file receive this error: 
E: Unable to locate package lcov

Is genhtml / lcov not available in this image ?

Thanks

**Comment by subinataws** [comment]
@odedNaftali - No, CodeBuild images don't have lcov in it. You can install it by invoking "apt-get update && apt-get install -y lcov" in your buildspec.

**Comment by odedNaftali** [comment]
thanks for the reply. When I call  "apt-get update && apt-get install -y lcov" from my buildspec I get "E: Unable to locate package lcov" error

**Comment by subinataws** [comment]
Don't know what's wrong in your buildspec, but this is fairly straightforward and yielded no issues on CodeBuild on AWS cloud. Where are you running this? locally or on AWS cloud?
```
version: 0.2

phases:
  build:
    commands:
      - apt-get update && apt-get install -y lcov
      - genhtml
```

**Comment by odedNaftali** [comment]
ok its working now tnx !!!
