### ISSUE TITLE
Enable experimental for docker daemon

### ISSUE THREAD

**Issue by dmarinuswoodwing** [aws/aws-codebuild-docker-images#351]
I'd like to use `--squash` to squash the layers built by docker. This requires the docker daemon to be started with experimental features enabled. This is done by adding `"experimental": true` to `/etc/docker/daemon.json` and restarting the docker daemon.

I'm using the following in my `buildspec.yml` to do this:
```yaml
      - kill $(cat /var/run/docker.pid)
      - while kill -0 $(cat /var/run/docker.pid) ; do sleep 1 ; done
      - "echo '{ \"experimental\": true }' > /etc/docker/daemon.json"
      - /usr/local/bin/dockerd-entrypoint.sh
```

Is there an easier way to accomplish this?

I can craft a PR to make `dockerd-entrypoint.sh` enable experimental when an environment variable is set or add a script to make it easier to start/stop the docker daemon. What would be preferred?

**Comment by subinataws** [comment]
Thanks for the feature request. Unfortunately, we won't be enabling Docker experimental features on CodeBuild due to stability and support concerns.

**Comment by dmarinuswoodwing** [comment]
Would a script to start/stop the docker daemon be accepted?

**Comment by zhujik** [comment]
I'm also looking for a way to configure the docker daemon in codebuild to use a different image directory. How where you able to accomplish this @dmarinuswoodwing ? calling docker-entrypoint.sh throws an error "failed to start daemon: error initializing graphdriver: backing file system is unsupported for this graph driver" after some time using your approach.

**Comment by dmarinuswoodwing** [comment]
@zhujik I think the image directory you're using is on an incompatible filesystem?

**Comment by zhujik** [comment]
@dmarinuswoodwing you are right, I discovered that EFS folders cannot be used as data-root for the docker daemon, since it uses nfs.

**Comment by niranjan94** [comment]
@dmarinuswoodwing we use docker-in-docker to workaround this and enable experimental support for docker within codebuild. Perhaps this could work for you too ? (We also needed the experimental flag to be turned on to use the `squash` command)

```bash
docker run -d --privileged -p 2376:2376 -v "$(pwd):/code" "docker:$(docker version -f '{{.Server.Version}}')-dind" dockerd --host=tcp://0.0.0.0:2376 --experimental
export DOCKER_HOST=tcp://127.0.0.1:2376
```

**Comment by vjp23** [comment]
@niranjan94 Thanks for sharing this, and great idea! I'm also looking to run a `squash` in CodeBuild; was this used in your pre-build?

**Comment by tobewisebeforeiamold** [comment]
FWIW, I used bits of this to get containerd working in CodeBuild. Thanks!
```
      - kill $(cat /var/run/docker.pid)
      - while kill -0 $(cat /var/run/docker.pid) ; do sleep 1 ; done
      - mkdir -p /etc/docker
      - "echo '{ \"features\": { \"containerd-snapshotter\": true } }' > /etc/docker/daemon.json"
      - /usr/local/bin/dockerd-entrypoint.sh
```
