### ISSUE TITLE
Building aws/codebuild/standard:4.0 errors

### ISSUE THREAD

**Issue by captainrandom** [aws/aws-codebuild-docker-images#352]
when building the docker image:
`docker build -t aws/codebuild/standard:4.0 .`

under the aws-codebuild-docker-images/ubuntu/standard/4.0 directory I get an error while building. Is there a way to download a pre-build image from dockerhub for standard 4.0? If not I'd like to be able to get this build working:

![Screen Shot 2020-05-21 at 9 23 50 AM](https://user-images.githubusercontent.com/13500774/82581485-7ec35280-9b45-11ea-9076-ba06bc64c204.png)

I recognize that this image shows that I'm not at the head of master, but I get a similar error when at the head of master:

Step 61/100 : RUN echo "memory_limit = 1G;" >> "/root/.phpenv/versions/$PHP_73_VERSION/etc/conf.d/memory.ini"
 ---> Running in 718157023a09
Removing intermediate container 718157023a09
 ---> 7beb56c592f6
Step 62/100 : COPY tools/runtime_configs/php/$PHP_74_VERSION /root/.phpenv/plugins/php-build/share/php-build/definitions/$PHP_74_VERSION
 ---> 33fdb448feb2
Step 63/100 : RUN phpenv install $PHP_74_VERSION; rm -rf /tmp/*; phpenv global $PHP_74_VERSION
 ---> Running in f36a7c64a594
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 7.4.5 into /root/.phpenv/versions/7.4.5
[Downloading]: https://secure.php.net/distributions/php-7.4.5.tar.bz2

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
curl: (16) Error in the HTTP2 framing layer
-----------------------------------------

The full Log is available at '/tmp/php-build.7.4.5.20200521070420.log'.
[Warn]: Aborting build.
phpenv: version `7.4.5' not installed
The command '/bin/sh -c phpenv install $PHP_74_VERSION; rm -rf /tmp/*; phpenv global $PHP_74_VERSION' returned a non-zero code: 1

**Comment by awszhen** [comment]
@captainrandom , we do not have pre-build image from dockerhub for standard 4.0. The docker build failed because of connection issue. Retry works for me.
