### ISSUE TITLE
Feature Request: Use existing Codebuild Project's Environment Variables

### ISSUE THREAD

**Issue by ryanpodonnell1** [aws/aws-codebuild-docker-images#353]
Hi,

It would be quite useful to have an optional flag and point to an existing codebuild project for stuff like environment variables that could be autoimported for local testing vs manually creating an environment variable file. 

This would allow me to do quicker testing against multiple codebuild projects

```
codebuild_build.sh -i ubuntu:latest -a ./output -b buildspec.yml --codebuild-project <codebuild-projectname> 
```

**Comment by subinataws** [comment]
@ryanpodonnell1 - Thanks for submitting the feature request. Unfortunately, this isn't a feature we plan to support. Our intention with the CodeBuild local script is to enable local buildspec validation. We do not plan to introduce dependency on a CodeBuild project on AWS Cloud at this time.

**Comment by ryanpodonnell1** [comment]
just as a workaround for anybody who comes accross this:

```
aws codebuild batch-get-projects --names <PROJECT_NAME> | jq -r '.projects[].environment.environmentVariables[] | "\(.name)=\(.value)"' > environment.txt
```
