### ISSUE TITLE
Update .NET Core version to 3.1.4

### ISSUE THREAD

**Issue by ScottFinlaysonGMSL** [aws/aws-codebuild-docker-images#354]
This is the latest LTS version as per:
https://dotnet.microsoft.com/download/dotnet-core

In particular, I'm interested in the NuGet support for adding custom nuget sources via:

`dotnet nuget add source <URL> <PARAMS>`

**Comment by awszhen** [comment]
@ScottFinlaysonGMSL , please use the latest Linux Standard 4.0 and AL2 3.0 images.
(1) https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile#L178
(2) https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/3.0/Dockerfile#L407

**Comment by ScottFinlaysonGMSL** [comment]
@awszhen that Dockerfile states you're using .NET version `3.1.301`. Are you intending to update that soon or are you saying you wont update the version yet?

**Comment by awszhen** [comment]
@ScottFinlaysonGMSL , we have updated the .NET Core to `v3.1.5`. The SDK version of .NET Core `v3.1.5` is `3.1.301`. Please refer to https://dotnet.microsoft.com/download/dotnet-core/3.1.
