### ISSUE TITLE
support for dotnet-core 2.1 LTS matching Lambda

### ISSUE THREAD

**Issue by hauntingEcho** [aws/aws-codebuild-docker-images#362]
Currently, AWS Lambda [supports dotnet core 2.1 and 3.1](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).  However, the codebuild images support 2.2 and 3.1.  [2.1 is the LTS from the 2.x series](https://dotnet.microsoft.com/platform/support/policy/dotnet-core), and 2.2 is EOL.

Being able to use a supported image matching the dotnet core 2.1 lambda environment would be very helpful.

**Comment by subinataws** [comment]
CodeBuild managed images only support .Net core 3.x on the standard images. Unfortunately, we don't have plans to support .net core 2.1. Please consider using a custom image of you require .net core 2.1 for your use case.
