### ISSUE TITLE
bring back `parallel`

### ISSUE THREAD

**Issue by monken** [aws/aws-codebuild-docker-images#363]
`parallel` was part of the `standard:1.0` image. It would be great to have it back because it can help speed up builds.

**Comment by subinataws** [comment]
@monken - We had to remove `parallel` due to its license being GPLv3. We unfortunately won't be bringing that back in CodeBuild's pre-configured Docker images, but you may consider installing it inline in your buildspec.

**Comment by monken** [comment]
got it!
