### ISSUE TITLE
aws/codebuild/standard:2.0 no longer maintained as of June 2020?

### ISSUE THREAD

**Issue by nairb774** [aws/aws-codebuild-docker-images#369]
According to https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html it looks like the aws/codebuild/standard:2.0 image is no longer maintaine. Having this information surfaced here would also be useful. The root README still references building the standard:2.0 image as an example which might be worth updating.

I only accidentally spotted the footnote, so making such things more visible would be nice. Prevents building an image only to find out that it isn't worth using.

**Comment by subinataws** [comment]
@nairb774 - Thanks for reporting this. Updated the readme now.
