### ISSUE TITLE
"E: Version '9.3.21-*' for 'libpq-dev' was not found" when building: ubuntu-base:14.04

### ISSUE THREAD

**Issue by sirisec** [aws/aws-codebuild-docker-images#37]
Unable to build docker image after git clone of this repo, and running the following command:
`docker build -t aws/codebuild/ubuntu-base:14.04 .`

from

`aws-codebuild-docker-images\ubuntu\ubuntu-base\14.04`

Can you please see if you're seeing this issue too?  Thanks!

**Comment by clareliguori** [comment]
Fixed in #35
