### ISSUE TITLE
Build fails on step 60/98 ubuntu/standard/4.0

### ISSUE THREAD

**Issue by eq-agilkison** [aws/aws-codebuild-docker-images#372]
Attempting to build ubuntu/standard/4.0 on an Amazon 2 Workspace but keep encountering the following error.
```
Step 7/98 : RUN set -ex     && curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.assets[] | select(.browser_download_url | contains("linux64")).browser_download_url' | wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi -     && tar -xzf /tmp/geckodriver-latest-linux64.tar.gz -C /opt     && rm /tmp/geckodriver-latest-linux64.tar.gz     && chmod 755 /opt/geckodriver     && ln -s /opt/geckodriver /usr/bin/geckodriver     && geckodriver --version
 ---> Running in 1e44203707e1
+ curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest
+ wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi -
+ jq -r .assets[] | select(.browser_download_url | contains("linux64")).browser_download_url
+ tar -xzf /tmp/geckodriver-latest-linux64.tar.gz -C /opt
```
Any help on this would be greatly appreciated. 
Please let me know if you need any more information on my local box.

**Comment by eq-agilkison** [comment]
Now able to get past step 7 but failed again at step 60.
```
Step 60/98 : RUN phpenv install $PHP_73_VERSION; rm -rf /tmp/*; phpenv global $PHP_73_VERSION
 ---> Running in aa4037909814
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 7.3.19 into /root/.phpenv/versions/7.3.19
[Downloading]: https://secure.php.net/distributions/php-7.3.19.tar.bz2

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
curl: (16) Error in the HTTP2 framing layer
-----------------------------------------

The full Log is available at '/tmp/php-build.7.3.19.20200730074539.log'.
[Warn]: Aborting build.
phpenv: version `7.3.19' not installed
The command '/bin/sh -c phpenv install $PHP_73_VERSION; rm -rf /tmp/*; phpenv global $PHP_73_VERSION' returned a non-zero code: 1
```
Fix found in [issue 373](https://github.com/aws/aws-codebuild-docker-images/issues/373)
Fix for stage 7 was replacing L75 with:
`&& curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.assets[] | select(.browser_download_url | contains("linux64")) | select(.browser_download_url | contains("asc") | not).browser_download_url' | wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi - \`

**Comment by eq-agilkison** [comment]
It seems re-running the build command multiple times solved the issue.

**Comment by subinataws** [comment]
@eq-agilkison - These Dockerfiles install from source and sometimes the endpoints hosting the binaries aren't accessible leading to transient errors. The workaround is to retry, which we know is suboptimal. We ideally shouldn't need our customers to have to rebuild these images from source and consume the pre-built images from a Docker registry. We are tracking that in https://github.com/aws/aws-codebuild-docker-images/issues/152.
