### ISSUE TITLE
build fails on Step 7/98 for aws/codebuild/standard:4.0 

### ISSUE THREAD

**Issue by trivikr** [aws/aws-codebuild-docker-images#375]
Attempting to build `aws/codebuild/standard:4.0` on an AL2 fails with the following error.

```console
Step 7/98 : RUN set -ex     && curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.assets[] | select(.browser_download_url | endswith("linux64.tar.gz")).browser_download_url' | wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi -     && tar -xzf /tmp/geckodriver-latest-linux64.tar.gz -C /opt     && rm /tmp/geckodriver-latest-linux64.tar.gz     && chmod 755 /opt/geckodriver     && ln -s /opt/geckodriver /usr/bin/geckodriver     && geckodriver --version
 ---> Running in 04ed72579a0b
+ curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest
+ jq -r .assets[] | select(.browser_download_url | endswith("linux64.tar.gz")).browser_download_url
+ wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi -
jq: error (at <stdin>:1): Cannot iterate over null (null)
+ tar -xzf /tmp/geckodriver-latest-linux64.tar.gz -C /opt

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c set -ex     && curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.assets[] | select(.browser_download_url | endswith("linux64.tar.gz")).browser_download_url' | wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi -     && tar -xzf /tmp/geckodriver-latest-linux64.tar.gz -C /opt     && rm /tmp/geckodriver-latest-linux64.tar.gz     && chmod 755 /opt/geckodriver     && ln -s /opt/geckodriver /usr/bin/geckodriver     && geckodriver --version' returned a non-zero code: 2
```

The error is consistently reproducible, even after several retries.

**Comment by trivikr** [comment]
Similar issue which was fixed after retries https://github.com/aws/aws-codebuild-docker-images/issues/372

**Comment by trivikr** [comment]
A pre-built image from a public Docker registry would help in such cases.
It is being tracked in #152.

**Comment by trivikr** [comment]
This issue was originally reported in #373
It looks like the fix in #374 didn't fix it

Verified that the fix given in https://github.com/aws/aws-codebuild-docker-images/issues/373#issuecomment-666190799 works, which replaces Line 75 with:
```console
   && curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.assets[] | select(.browser_download_url | contains("linux64")) | select(.browser_download_url | contains("asc") | not).browser_download_url' | wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi - \
```

**Comment by trivikr** [comment]
Verified that the following command fails:

```console
$ curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.assets[] | select(.browser_download_url | endswith("linux64.tar.gz")).browser_download_url'
jq: error (at <stdin>:1): Cannot iterate over null (null)
```

**Comment by awszhen** [comment]
@trivikr , I can not reproduce this issue using latest ```aws/codebuild/standard:4.0``` Dockerfile on an AL2 instance.

**Comment by trivikr** [comment]
> I can not reproduce this issue using latest aws/codebuild/standard:4.0 Dockerfile on an AL2 instance.

The code from master https://github.com/aws/aws-codebuild-docker-images/blob/1889d4afd02eb0160d239fc7f6dfbf4588ead516/ubuntu/standard/4.0/Dockerfile#L75

Verified that the error documented in issue description has the fix from #374 https://github.com/aws/aws-codebuild-docker-images/issues/375#issue-673207764

Do you need more information to debug this issue?

**Comment by trivikr** [comment]
I was not able to reproduce this issue on 8/7

Probably there is some issue while downloading file `https://api.github.com/repos/mozilla/geckodriver/releases/latest`, or the API output is different.

**Comment by trivikr** [comment]
Two solutions to avoid this in future:
* Short-term: Update README (say add Troubleshooting section) to mention about such intermittent issues, and suggest users to retry.
* Long-term: Provide CodeBuild images on public Docker repository, so users don't have to build them on their own (being tracked in https://github.com/aws/aws-codebuild-docker-images/issues/152)

**Comment by jeremyj563** [comment]
Not a sustainable solution at all but I was able to get this to continue building today by hard-coding the download link to the previous version of `geckodriver` (v0.26.0) into the Dockerfile.

I just replaced this line:
```
    && curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.assets[] | select(.browser_download_url | contains("linux64")).browser_download_url' | wget -O /tmp/geckodriver-latest-linux64.tar.gz -qi - \
```

with:
```
    && wget -O /tmp/geckodriver-latest-linux64.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz \
```
