### ISSUE TITLE
Support for Golang 1.15

### ISSUE THREAD

**Issue by msiuts** [aws/aws-codebuild-docker-images#377]
Since Go 1.15 was released, I would love to have this available in the Codebuild images.

Blog Post:
https://blog.golang.org/go1.15

**Comment by asterikx** [comment]
Would also love to see this. My build just kept failing in CodeBuild environments. As it turned out it was because I was already using 1.15 locally (and implementing the SQL driver interface `driver.Validator` which was only added with 1.15)

**Comment by msiuts** [comment]
According to https://github.com/aws/aws-codebuild-docker-images/pull/383#issuecomment-684119802 this will be in the next release. Is there any ETA for this release?

**Comment by subinataws** [comment]
Go 1.15 is available with [standard:5.0](https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.01.08)
