### ISSUE TITLE
dep doesn't have execution permissions

### ISSUE THREAD

**Issue by federicojasson** [aws/aws-codebuild-docker-images#38]
I tried using `dep ensure` in one of my projects, and it failed.
So I built the Docker image locally and got this:

```
root@b58d098173b2:/go# /go/bin/dep ensure
bash: /go/bin/dep: Permission denied
root@b58d098173b2:/go# ls -l /go/bin/dep 
-rw-r--r-- 1 root root 8498976 Jan 25 00:58 /go/bin/dep
```

**Comment by kendrickkesley** [comment]
Hi, is this issue solved already? I still get permission denied when using dep ensure in aws/codebuild/golang:1.10
