### ISSUE TITLE
pyenv: version `3.7.7' not installed

### ISSUE THREAD

**Issue by rolandoldengarm** [aws/aws-codebuild-docker-images#381]
When I try to build v4.0 with: `docker build -t aws/codebuild/standard:4.0 .`
I'm getting below error:
```
Step 50/98 : RUN   pyenv global  $PYTHON_37_VERSION
 ---> Running in 1f2434d287f6
pyenv: version `3.7.7' not installed
The command '/bin/sh -c pyenv global  $PYTHON_37_VERSION' returned a non-zero code: 1
```
I'm on Windows 10.

**Comment by minasys** [comment]
I have the same issue, it worked when I put it in the default VPC, that has its subnets have internet access.
My question is what VPC endpoints needed in case I need to make that work on a private subnet?
