### ISSUE TITLE
CodeBuild doesn't honor Makefile Exit code

### ISSUE THREAD

**Issue by duganth-va** [aws/aws-codebuild-docker-images#385]
My build says success but my Makefile exited with error. 

```

Makefile:29: recipe for target 'build' failed
--
999 | make: *** [build] Error 1
1000 |  
1001 | [Container] 2020/09/01 17:38:16 Phase complete: BUILD State: SUCCEEDED
1002 | [Container] 2020/09/01 17:38:16 Phase context status code:  Message:
1003 | [Container] 2020/09/01 17:38:16 Entering phase POST_BUILD


```

**Comment by subinataws** [comment]
Note that CodeBuild's build transition is documented here: https://docs.aws.amazon.com/codebuild/latest/userguide/view-build-details.html#view-build-details-phases. 

If the "build" phase is success or failure, the build moves to post_build and executes all remaining phases.

I'm assuming that's the issue here.

**Comment by duganth-va** [comment]
Thank you for taking the time to look at my issue. The issues is not that it continues to the POST_BUILD phase. The issue is that the exit code from the Makefile is non-zero but codebuild still reports the build as a success:

```
999 | make: *** [build] Error 1
...
1001 | [Container] 2020/09/01 17:38:16 Phase complete: BUILD State: SUCCEEDED
```

**Comment by xinyu-aws** [comment]
@duganth-va Hello. I was not able to reproduce this issue. Is the reporting also wrong on AWS CodeBuild(non-local) or is it a local build only issue?

**Comment by duganth-va** [comment]
Hey @xinyu-aws. Thanks for taking a look, I was using the aws/codebuild/standard:2.0 in us-gov-west-1.

**Comment by xinyu-aws** [comment]
Hi @duganth-va. Thanks for the information. Since we were not able to reproduce the issue with the current info, could you post the problem on this forum [https://forums.aws.amazon.com/forum.jspa?forumID=230](url)? Our oncall will take a look and contact you for more details. Thanks.

**Comment by subinataws** [comment]
@duganth-va - Marking this resolved as we don't have a repro and this is mentioned as happening on CodeBuild on AWS Cloud. Please connect with us on our AWS forum, as we would need additional information from you to troubleshoot this issue.
