### ISSUE TITLE
code build error 

### ISSUE THREAD

**Issue by adnanrashidtipu74** [aws/aws-codebuild-docker-images#391]
Hi

I am getting this error when trying to run codebuild.sh which is -

%%time
!./codebuild_build.sh \
    -a "$PWD/tests/output" \
    -s "$PWD/tests" \
    -i "aws/aws-codebuild-standard:3.0" \
    -e "$PWD/tests/vars.env" \
    -c

Build Command:

docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=aws/aws-codebuild-standard:3.0" -e "ARTIFACTS=/home/ec2-user/SageMaker/tests/output" -e "SOURCE=/home/ec2-user/SageMaker/tests" -v "/home/ec2-user/SageMaker/tests:/LocalBuild/envFile/" -e "ENV_VAR_FILE=vars.env" -e "AWS_CONFIGURATION=/home/ec2-user/.aws" -e "AWS_CLOUDWATCH_HOME=/opt/aws/apitools/mon" -e "AWS_PATH=/opt/aws" -e "AWS_AUTO_SCALING_HOME=/opt/aws/apitools/as" -e "AWS_ELB_HOME=/opt/aws/apitools/elb" -e "INITIATOR=ec2-user" amazon/aws-codebuild-local:latest

Removing network agent-resources_default
WARNING: Network agent-resources_default not found.
Removing volume agent-resources_source_volume
WARNING: Volume agent-resources_source_volume not found.
Removing volume agent-resources_user_volume
WARNING: Volume agent-resources_user_volume not found.
Creating network "agent-resources_default" with the default driver
Creating volume "agent-resources_source_volume" with local driver
Creating volume "agent-resources_user_volume" with local driver
Pulling build (aws/aws-codebuild-standard:3.0)...
****ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]^C
CPU times: user 478 ms, sys: 83.3 ms, total: 561 ms**
Wall time: 37 s**

**Comment by awszhen** [comment]
@adnanrashidtipu74 , you need to have `aws/aws-codebuild-standard:3.0` image built locally.
