### ISSUE TITLE
Please upgrade libyaml(libyaml actually is from amazonlinux:2)

### ISSUE THREAD

**Issue by HasseJohansen** [aws/aws-codebuild-docker-images#394]
Hi debugging a problem where cfn-lint in codebuild containers threw a generic yaml error (E0000 found unexpected ':'
cloudformation/network/vpc.yml:566:54). This is using libyaml-0.1.4

And our local cfn-lint didn't throw any errors using libyaml-0.2.5

I have found out that libyaml in the amazonlinux:2 image is ancient. Please get it updated. Writing cloudformation which locally seems perfect and then getting the cfn-lint in the codebuild container bail on it is not really a good experience

I have reproduced in the aws/codebuild/amazonlinux2-x86_64-standard:3.0 container, but the same problem is in :2.0 and :1.0

With the old libyaml it bails on syntax like this:
`!If [IsProd, !Ref DBSubnetB, Ref: AWS::NoValue] and needs quoting of AWS::NoValue`

With libyaml-0.2.5 it works without quoting

Way to reproduce:
Download & unpack: http://pyyaml.org/download/libyaml/yaml-0.2.5.tar.gz

run:
```
$ ./configure
$ make
# make install
```

Remove/rename:
```
/usr/lib64/libyaml-0.so.2
/usr/lib64/libyaml-0.so.2.0.4
```

run cfn-lint(now without using libyaml as it doesn't exists where pyYAML looks for it). It will not complain

make symbolic links to use the newer libyaml:

```
ln -s /usr/local/lib/libyaml-0.so.2 /usr/lib64/libyaml-0.so.2
ln -s /usr/local/lib/libyaml-0.so.2.0.9 /usr/lib64/libyaml-0.so.2.0.9
```
also works

only using the ancient libyaml fails

**Comment by subinataws** [comment]
>I have found out that libyaml in the amazonlinux:2 image is ancient.

@HasseJohansen - Thanks for reporting the issue. Please submit this issue with AL repo @ https://github.com/amazonlinux/container-images. We won't be pinning the libraries in CodeBuild's docker image that are consumed from upstream baseOS layer.
