### ISSUE TITLE
Support For Latest Ruby Patch Version - 2.7.2

### ISSUE THREAD

**Issue by whithajess** [aws/aws-codebuild-docker-images#395]
[Ruby 2.7.2 Released](https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/)

Has security fixes as well as other changes.

**Comment by subinataws** [comment]
Now [available](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile#L218) in [standard:5.0](https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.01.08).
