### ISSUE TITLE
Android version 30

### ISSUE THREAD

**Issue by antkont** [aws/aws-codebuild-docker-images#398]
Android version 30 support would be greatly appreciated. Thank you!

**Comment by jakoss** [comment]
Any update on this? Version 30 will be forced on google play soon

**Comment by dicarlomagnus** [comment]
Google has announced that by August 1st that is a must to update your android app with the SDK 30, could you please add support for this version?

https://developer.android.com/distribute/best-practices/develop/target-sdk

Thanks!

**Comment by felipeloha** [comment]
+1

**Comment by budo385** [comment]
same here

**Comment by sidhuparas** [comment]
+1

**Comment by iamarjun** [comment]
+1

**Comment by amritydvdev** [comment]
+1

**Comment by laurentlr** [comment]
+1

**Comment by anilchahalaig** [comment]
+1

**Comment by yurgins** [comment]
+1

**Comment by lhincapie0** [comment]
+1

**Comment by jakoss** [comment]
At this point shouldn't we be talking about sdk 31? I doubt this will ever happen, RIP docker image

**Comment by budo385** [comment]
Made an issue with sdk 31, please upvote. 
https://github.com/aws/aws-codebuild-docker-images/issues/496#issuecomment-965220842

**Comment by subinataws** [comment]
Closing out older issue that we unfortunately never got to address. We will add an updated Android image in our next update.
