### ISSUE TITLE
Node version 10.x should be >=10.22.x. It is 10.21

### ISSUE THREAD

**Issue by alexforsyth** [aws/aws-codebuild-docker-images#399]
According to the docs aws codebuild should support the latest version of node 10.x: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

The current version 10 is at 10.21 https://github.com/aws/aws-codebuild-docker-images/blob/407e02949dd24cd14a0db830c03639f34ff46ced/ubuntu/standard/4.0/Dockerfile#L221

Node version 10.x should be >=10.23.x. It is 10.21

Per node: 10.23 is the latest release: https://nodejs.org/dist/latest-v10.x/

This is currently blocking: https://github.com/aws/aws-sdk-js-v3/pull/1673

**Comment by subinataws** [comment]
Updated in [standard:4.0](https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.01.08).
