### ISSUE TITLE
.NET 5 Release - runtime support

### ISSUE THREAD

**Issue by npetter** [aws/aws-codebuild-docker-images#401]
Hi,

I know .NET 5 is not considered a LTS release, but I believe there is pretty significant interest in this particular release to warrant supporting that as a runtime in the codebuild images.

Specifically I believe it's in AWS' interest due to the performance improvents on ARM64, which is already used by large companies running on Graviton 2.

Thoughts?

**Comment by 628426** [comment]
There is a commitment here of support soon https://aws.amazon.com/blogs/developer/net-5-on-aws/#:~:text=.NET%205%20in%20AWS%20CodeBuild%20is%20coming%20soon.

**Comment by ngz82** [comment]
+1 For .net 5 support.
Any update as to when this might be available? (or work-arounds for now - scripting the install of the sdk/runtime in the buildspec doesn't seem to work, it seems to install fine, no errors, but then it doesn't show up in the installed versions list nor does a build work.

We just updated our API to .Net 5 and now our automated code pipeline/code build/code deply process is broken

**Comment by dillon-odonovan** [comment]
An available work around is to define your CodeBuild environment as a Docker container and update your CodeBuild project to pull that container as its build environment. This is what we are doing until .NET 5 support is available.

[More on CodeBuild custom environments](https://aws.amazon.com/blogs/devops/extending-aws-codebuild-with-custom-build-environments/)

Our use case is rather simple, but here is an example Dockerfile if you need a starting point

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0
RUN curl -sL https://deb.nodesource.com/setup_15.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by vickyrathee** [comment]
+1 to support dotnet 5. 

I just ran into errors due to it's not supported - https://stackoverflow.com/questions/65546757/aws-codebuild-unknown-runtime-version-named-5-0-of-dotnet

**Comment by subinataws** [comment]
Added support in [standard:5.0](https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.01.08).

**Comment by cdonnellytx** [comment]
Would it be possible to add .NET 5.0 to the Amazon Linux x86-64 image?
