### ISSUE TITLE
standard:4.0 awscli incompatible with latest boto3

### ISSUE THREAD

**Issue by TomDufall** [aws/aws-codebuild-docker-images#402]
The standard:4.0 (and, presumably, all the others) image uses an older version of awscli which is incompatible with later versions of boto3. See this issue: [https://github.com/boto/boto3/issues/2596](https://github.com/boto/boto3/issues/2596)

This is an issue when a build script installs a newer version of boto3 (e.g. as part of testing a Python package) without also updating awscli.

It looks like awscli/boto3 isn't pinned in this repo, so all that needs to happen is for the images to be built again and pushed to wherever codebuild keeps its images.

**Comment by TomDufall** [comment]
This could be considered low priority as it's pretty easy to work around - install the latest version of awscli yourself. I think it would be good to get it resolved here, though, as I think CodeBuild should work out of the box with the latest boto3.

**Comment by subinataws** [comment]
Standard:4.0 was rebuilt with the latest release, which picks up latest aws cli V1 and its dependencies. Standard:5.0 (available now) onwards we are switching to aws cli v2, which doesn't have external dependencies that require version locking.
