### ISSUE TITLE
Support Java Corretto 15 JDK

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [aws/aws-codebuild-docker-images#403]
The new LTS version of the AWS Corretto JDK has been released in August. We've updated our usage of version 11 on our EC2 instances and local development to it, but sadly AWS CodeBuild does not support it yet. This means we can start to build code that uses methods/classes that are not yet available and the build fail. It would be great to add support for version 15.

https://docs.aws.amazon.com/corretto/latest/corretto-15-ug/what-is-corretto-15.html

**Comment by subinataws** [comment]
@FrontierPsychiatrist - you can use the AWS provided Docker image for your build environment: https://hub.docker.com/_/amazoncorretto to try corretto 15.

**Comment by FrontierPsychiatrist** [comment]
Thank you, didn't know about that! Not sure if it will help in this case though as our build also needs Docker to start some additional containers for running tests.

**Comment by FrontierPsychiatrist** [comment]
Could yuo explain why this was closed? Will there be support for AWS Corretto 15 in the `aws/codebuild/amazonlinux2-x86_64-standard:3.0` image at some point?

**Comment by mrifni** [comment]
why was this closed? I am using `aws/codebuild/standard:4.0` and it doesnt support Java 15 and my gradle build file has java 15 configured. So codebuild is failing with message `> Could not target platform: 'Java SE 15' using tool chain: 'JDK 11 (11)'.`

aws/codebuild/standard:4.0

**Comment by subinataws** [comment]
CodeBuild will only be supporting LTS versions. Corretto 15 is not LTS (it has medium term support). Next LTS version is 17, which will be supported in CodeBuild images after it launches.

If you'd like to use corretto 15 as your build environment in CodeBuild, please feel free to use the corretto 15 from DockerHub: https://hub.docker.com/_/amazoncorretto.
