### ISSUE TITLE
Configure docker layer caching for external image between builds does not work

### ISSUE THREAD

**Issue by danielleallopez** [aws/aws-codebuild-docker-images#405]
We are pulling a DynamoDB local image in our CodeBuild project to run tests over the source code, and are trying to set up cache docker layer to save time between builds.

However, we see that there is no time improvement between builds that are only seconds apart. 

We saw someone with a similar problem in another issue: is there any recommended way how to cache docker layers for more than a life span of a codebuild?
my UC - for every build I pull `mysql` image from public docker registry to execute some local integration tests. How can I cache this image between builds (Let's say I have build frequency 2 times a day)

_Originally posted by @ivanmartos in https://github.com/aws/aws-codebuild-docker-images/issues/26#issuecomment-671930234_

**Comment by subinataws** [comment]
@danielleallopez - This limitation is tracked in https://github.com/aws/aws-codebuild-docker-images/issues/194. There is a workaround mentioned there. Resolving to track under one issue.

**Comment by danielleallopez** [comment]
@subinataws Thanks for taking the time to answer. I saw that issue before creating this one, and the thing is that it mentions that cache works fine when builds are ran minutes apart, but we're not seeing that even when they are ran seconds apart.

We've been basically running one after another and see no improvement regarding time, so issue/question was about what might be wrong there.

**Comment by subinataws** [comment]
@danielleallopez - Could you tell me more about the build configuration? Which compute type is being used? Do you have privileged mode enabled?

If you have privileged mode enables, then there will be no warm node available for any period of time, unless you enable docker_layer_caching under the local cache setting.

**Comment by danielleallopez** [comment]
@subinataws Thanks for the response.

We created a simple code build project with build image `LinuxBuildImage.STANDARD_4_0`, compute type `ComputeType.SMALL` and not privileged.

The build spec installs python dependencies using pip in the _install_ phase and just runs `pytest` in the _build_ phase.

We were expecting to see a decrease in the total runtime on consecutive builds, but we don't.
