### ISSUE TITLE
Outdated Golang versions

### ISSUE THREAD

**Issue by johannes-gehrs** [aws/aws-codebuild-docker-images#409]
Golang 1.15 was released 11 August 2020. To this day Standard 4.0 does not support Go 1.15. Please try to support new versions in a timely fashion.

To give a comparison to your competition, CircleCI usually supports new major and minor versions within hours.

Please feel free to close this issue. This is just customer feedback.

**Comment by subinataws** [comment]
@johannes-gehrs - Thanks for the feedback. We'll update https://github.com/aws/aws-codebuild-docker-images/issues/377, when we have this support available in CodeBuild.
