### ISSUE TITLE
Host AWS CodeBuild Docker images on the Amazon ECR Public registry

### ISSUE THREAD

**Issue by a-h** [aws/aws-codebuild-docker-images#411]
The last time I tried to build a CodeBuild image to reproduce an issue (a couple of years ago), I searched for the images on Dockerhub to try and reproduce it only to find that the images aren't available (https://github.com/aws/aws-codebuild-docker-images/issues/152).

I then had to build locally, which wasted a lot of time. Once it had built, I was unable to reproduce the problem with the container locally (it wasn't exactly the same container as in CodeBuild after all) so I gave up on CodeBuild completely.

When I saw that Amazon Elastic Container Registry Public was released, I thought, great, that must have been what they were waiting for, but I don't see any Docker images in there... https://gallery.ecr.aws/?searchTerm=CodeBuild

Is this a planned feature, if not could this project start pushing image to AWS ECR Public please?

**Comment by deleugpn** [comment]
This would be pretty good, indeed.

**Comment by 1oglop1** [comment]
@a-h I found it here: https://gallery.ecr.aws/everest/codebuild/ubuntu/standard
are they not up to date or was the issue resolved?

**Comment by lorengordon** [comment]
@1oglop1 Looks like that is not an official build... from the link:

> These are unofficial builds of the Docker images used for AWS CodeBuild

**Comment by a-h** [comment]
I think the issue is now worse than it was because there are images that look official, like this: https://gallery.ecr.aws/e3e6e9v4/codebuild

Who created the containers, and what's in them?

**Comment by lorengordon** [comment]
Maybe let this guy know you're all interested in this feature...
 https://twitter.com/nickcoult/status/1377656269155131392?s=19

**Comment by lorengordon** [comment]
It's not the ubuntu images, but the AL2 images are now in public ECR... @leoherran-aws might be able to close this issue also?

https://github.com/aws/aws-codebuild-docker-images/issues/152#issuecomment-930398703

**Comment by mcg** [comment]
Why was this closed before Ubuntu images are available? Is there a plan for that or another ticket?

**Comment by subinataws** [comment]
@mcg - we can't host/distribute the Ubuntu based images per legal terms. So, unfortunately, only the Amazon Linux based images will be officially hosted on public ECR by AWS CodeBuild team.

**Comment by marinpurgar** [comment]
If you can't host/distribute the Ubuntu based images per legal terms how come that there are:
`codebuild/amazonlinux2-x86_64-standard:4.0`
`codebuild/amazonlinux2-x86_64-standard:4.0`
`codebuild/amazonlinux2-x86_64-standard:4.0`
on https://gallery.ecr.aws/codebuild/amazonlinux2-x86_64-standard ?
