### ISSUE TITLE
No loop device

### ISSUE THREAD

**Issue by fiLLLip** [aws/aws-codebuild-docker-images#412]
I am currently building a flashable image for Raspberry Pi, and doing that requires loop devices. I see that I get error messages on running `modprobe loop max_loop=64` and on `losetup -f`.

```
++ losetup -f
--
971 | losetup: cannot find an unused loop device: No such device
972 | + LOOPDEVICE=
```

```
+ modprobe loop max_loop=64
--
974 | modprobe: FATAL: Module loop not found in directory /lib/modules/4.14.186-146.268.amzn2.aarch64
```
(These are two separate builds)

Is there any way to embed the loop device possibility into the codebuild docker images? Specifically the ARM image (aws/codebuild/amazonlinux2-aarch64-standard:2.0)

**Comment by celtric** [comment]
We are in the same situation. Did you manage to find a working solution @fiLLLip?

**Comment by celtric** [comment]
As an update, running the build with elevated privileges fixed the issue for us. See https://stackoverflow.com/a/40360670

**Comment by fiLLLip** [comment]
> We are in the same situation. Did you manage to find a working solution @fiLLLip?

We don't build these images very often, so we opted to do it locally on a "build agent" (Raspberry Pi 3B) and publish to S3 with a script. This has worked fine for us, so I didn't want to "waste" more time getting it working inside CodeBuild.



> As an update, running the build with elevated privileges fixed the issue for us. See https://stackoverflow.com/a/40360670

Thank you for the link! Have you altered your build script after discovering this? Are you still using losetup and modprobe loop? And have you verified this to work in AWS CodeBuild?

**Comment by celtric** [comment]
> We don't build these images very often, so we opted to do it locally on a "build agent" (Raspberry Pi 3B) and publish to S3 with a script. This has worked fine for us, so I didn't want to "waste" more time getting it working inside CodeBuild.

👍 Yes, trying to fix these things is usually a time sink.

> Thank you for the link! Have you altered your build script after discovering this? Are you still using losetup and modprobe loop? And have you verified this to work in AWS CodeBuild?

Luckily no change needed to the build script, `losetup` is working fine. I haven't tried `modprobe` though.

The setting as a reference for future readers:

![image](https://user-images.githubusercontent.com/159156/107336276-31af5400-6ab9-11eb-8c54-6b5395319cb7.png)

**Comment by justin-robinson** [comment]
I'm having this same issue but privileged mode was already on


output from `aws codebuild batch-get-projects --names <PROJECT_NAME>`
```
"environment": {
  "type": "LINUX_CONTAINER",
  "image": "aws/codebuild/standard:7.0",
  "computeType": "BUILD_GENERAL1_SMALL",
  "environmentVariables": [],
  "privilegedMode": true,
  "imagePullCredentialsType": "CODEBUILD"
}
```
