### ISSUE TITLE
latest in runtime-versions does not point to the tip version

### ISSUE THREAD

**Issue by vickyrathee** [aws/aws-codebuild-docker-images#414]
I see that 5.0 is released today https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.01.08
But in codebuild the `dotnet: latest` in run-time versions it resolve to 3.1
```
install:
    runtime-versions:
      dotnet: latest
```

![image](https://user-images.githubusercontent.com/6106479/104084762-f62e2980-526f-11eb-9e77-a1b72fd83edd.png)

**Comment by subinataws** [comment]
Thanks for reporting this issue. We'll get this addressed. In the meantime, please use "dotnet: 5.0" instead of "dotnet: latest" to get the .NET 5 runtime with the standard:5.0 image.

**Comment by xgnl** [comment]
Hi vickyrathee,

I’ve ran builds on standard 5.0 with the following buildspec:
```
version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: latest
  build:
    commands:
      - dotnet --version
```
This is the console output I have:
![image](https://user-images.githubusercontent.com/23062765/104226645-231c4100-5416-11eb-8d5c-5a93749255b5.png)

It appears that `dotnet: latest` maps to 5.0, I have repeated the build in all regions that we support and got the same results. If you could provide more details on the builds we can help you debug it. Contact: xanam@amazon.com

**Comment by vickyrathee** [comment]
@xgnl please disregard, I was using Amazon Linux image instead Ubuntu.

**Comment by DevDotJoel** [comment]
> Hi vickyrathee,
> 
> I’ve ran builds on standard 5.0 with the following buildspec:
> 
> ```
> version: 0.2
> phases:
>   install:
>     runtime-versions:
>       dotnet: latest
>   build:
>     commands:
>       - dotnet --version
> ```
> 
> This is the console output I have: ![image](https://user-images.githubusercontent.com/23062765/104226645-231c4100-5416-11eb-8d5c-5a93749255b5.png)
> 
> It appears that `dotnet: latest` maps to 5.0, I have repeated the build in all regions that we support and got the same results. If you could provide more details on the builds we can help you debug it. Contact: [xanam@amazon.com](mailto:xanam@amazon.com)

So it needs to be ubuntu. but if i publish directly from visual studio it accepts on linux on .Net 5 .

**Comment by vickyrathee** [comment]
Yup, I got it working. It’s resolving to 5.0

**Comment by DevDotJoel** [comment]
> Yup, I got it working. It’s resolving to 5.0

If i publish from visual studio it's working. but my repo is on codeSource. I created a build but it's not working because amazon linux doesn't support .net 5. If i used Latest on the command it's gonna get .net core 3.1
Is there anyway to solve this ?
