### ISSUE TITLE
Ubuntu Standard 5.0 .NET Core Tools fail because DOTNET_ROOT is not configured

### ISSUE THREAD

**Issue by cristeh** [aws/aws-codebuild-docker-images#418]
Hi. We're experimenting with .NET 5 and use [GitVersion.Tool](https://www.nuget.org/packages/GitVersion.Tool/) as part of of our pipeline which is a global .NET Core executable.
Since the Standard 5.0 doesn't have a DOTNET_ROOT env var(seems like it's set as an ARG in https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile#L162) the way Standard 4.0 does(https://github.com/aws/aws-codebuild-docker-images/blob/f339f1c9f6b47b92f7b4c4358dc1c9829062d54e/ubuntu/standard/4.0/Dockerfile#L179), we get the following error:
`
A fatal error occurred. The required library libhostfxr.so could not be found.
 If this is a self-contained application, that library should exist in [/codebuild/output/src768222049/src/github.com/[...]/.store/gitversion.tool/5.6.4/gitversion.tool/5.6.4/tools/net5.0/any/].
 If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
`

An workaround is to add it by hand in the buildscript.yml file, in which case everything works:
`
env:
    variables:
        DOTNET_ROOT: /root/.dotnet
`
but this is obviously not ideal. 
Is it possible for Standard 5.0 to work like the older images in this regard?

**Comment by stage88** [comment]
I get a similar error:

```
[Container] 2021/02/08 22:18:04 Running command /root/.dotnet/tools/dotnet-lambda package-ci \
  --template my-template.yml \
  --output-template output-template.yml \
  --s3-bucket $S3_BUCKET \
  --s3-prefix builds/$ENVIRONMENT/my-template/ \
  --msbuild-parameters "$MSBUILD_PARAMETERS"

A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/codebuild/local-cache/custom/54fb85deeddd1d35f24d9e0e23e3d3f88ad0fd12071c528a6aaa623d7c5f31c7/root/.dotnet/tools/.store/amazon.lambda.tools/5.0.1/amazon.lambda.tools/5.0.1/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.20.04-x64
```

Adding this to the buildspec fixes the issue:
```
env: 
  variables: 
    DOTNET_ROOT: /root/.dotnet
```

**Comment by derwasp** [comment]
@xgnl @awszhen hey guys, any chance we can get some feedback on this ticket?
