### ISSUE TITLE
Feature Request: Amazon Linux docker images

### ISSUE THREAD

**Issue by nfisher** [aws/aws-codebuild-docker-images#42]
It would be nice if it were possible to use Amazon Linux as the base image for parity with Elastic Beanstalk and other AWS systems.

Using Ubuntu in CI and Amazon Linux for the deployment can create unexpected errors due to minor differences in the environments unless using a docker image deployment.

**Comment by clareliguori** [comment]
We do have a set of Amazon Linux images specifically for use with Elastic Beanstalk that are not listed in the AWS console:
https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
Please let us know if these don't meet your application's needs.

**Comment by nfisher** [comment]
Will take a look! Thanks. Are they available anywhere for local dev?

**Comment by clareliguori** [comment]
No, those Dockerfiles are not open sourced

**Comment by rayj-pgi** [comment]
How about these? https://hub.docker.com/_/amazonlinux/

**Comment by subinataws** [comment]
AL2 is now supported. https://github.com/aws/aws-codebuild-docker-images/releases/tag/1.12.0.
