### ISSUE TITLE
Upgrade sam-cli to v1.16.0+

### ISSUE THREAD

**Issue by aczire** [aws/aws-codebuild-docker-images#423]
Currently codebuild is failing cloudformation package due to a bug: "sam package command can't upload nested template that contain Fn::Transform"; details available here: https://github.com/aws/aws-sam-cli/issues/2501

Please upgrade SAM version to v1.16.0+

**Comment by subinataws** [comment]
SAM updates will be picked up when a new version of the CodeBuild image is released. CodeBuild images unfortunately won't be updated as frequently as the AWS CLI or SAM CLI. Please consider updating CLIs inline in your buildspec, if you need the latest version.

**Comment by uncodable** [comment]
@subinataws might be work introducing a chore to handle the aws and sam cli updates? I would prefer the latest version of the cli to be available in the latest image, too many work arounds to manually support tooling to update etc. Opinions?

**Comment by subinataws** [comment]
aws/codebuild/standard:5.0 should have sam version of 1.22. Resolving.
