### ISSUE TITLE
Add support for Go 1.16

### ISSUE THREAD

**Issue by msiuts** [aws/aws-codebuild-docker-images#425]
Since Go 1.16 was released, I would love to have this available in the Codebuild images.

Blog Post:
https://blog.golang.org/go1.16

**Comment by jpduckwo** [comment]
Would be great to see this! Thanks!

**Comment by TimoKoole** [comment]
Is there any ETA on this?

**Comment by msiuts** [comment]
The recommendation by the AWS support was to use directly use goenv which is also used internally and is provided in the images.

To manually invoke goenv from CodeBuild, see  https://github.com/syndbg/goenv/blob/master/COMMANDS.md

**Comment by jpduckwo** [comment]
@msiuts thanks for sharing that! 

FYI anyone interested - add something like this to your buildspec file command before you run any go commands:

```
      - 'goenv install 1.16.3'
      - 'goenv local 1.16.3'
      - 'go build ...something'
```

You can see available versions with `goenv install --list`. At the time of writing 1.16.4 and 1.16.5 were released but did not yet work with this method, I'm unsure on how long it usually takes for the version to become installable with goenv. Anyone know why it's not fully up to date?

**Comment by shogo82148** [comment]
Maybe, it is blocked by https://github.com/syndbg/goenv/pull/181

**Comment by jpduckwo** [comment]
Ahh here we go:
You need to pull the latest version of goenv, then you install the latest from their repo

add to buildspec commands:
```
      # Update goenv to get latest definitions of go version, see
      # https://github.com/syndbg/goenv/tree/master/plugins/go-build
      # https://github.com/syndbg/goenv/tree/master/plugins/go-build/share/go-build
      - 'cd $HOME/.goenv && git pull --ff-only && cd -'
      - 'goenv install 1.16.4'
      - 'goenv local 1.16.4'
      - 'go version'
```

**Comment by syndbg** [comment]
@shogo82148 Merged upstream 🙇

**Comment by shogo82148** [comment]
@syndbg Thanks!

@ AWS CodeBuild Team, can you re-build the images?

**Comment by jpduckwo** [comment]
@shogo82148 You don't need wait for AWS to update the images, you should be able to access 1.16.5 by using the commands in your buildspec listed above. The first command updates the goevn locally so that it can install the latest version that goenv has built and then the other commands activate it for your build.
```
      - 'cd $HOME/.goenv && git pull --ff-only && cd -'
      - 'goenv install 1.16.5'
      - 'goenv local 1.16.5'
      - 'go version'
```
This will work for whatever version goenv supports without AWS updating docker images
