### ISSUE TITLE
Install SAM CLI via native Linux installer instead of pip

### ISSUE THREAD

**Issue by CoshUS** [aws/aws-codebuild-docker-images#426]
As of [SAM CLI v1.18.1 release](https://github.com/aws/aws-sam-cli/releases/tag/v1.18.1), it can be [installed directly with native Linux binary](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html#serverless-sam-cli-install-linux-sam-cli) instead of using pip which pins down python dependencies.

**Comment by subinataws** [comment]
Thanks for highlighting this streamlined approach for x86. We prefer keeping it consistent across x86 and Arm, so will continue with the current approach for installing sam.
