### ISSUE TITLE
Add support for Ruby 2.7.2 and 3.0.0

### ISSUE THREAD

**Issue by mikelkew** [aws/aws-codebuild-docker-images#427]
It would be fantastic if we could please have runtime support for the latest Ruby versions - specifically both [`v2.7.2`](https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/) (released 2020-10-02) and [`v3.0.0`](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/) (released 2020-12-25).

**Comment by subinataws** [comment]
@mikelkew - Ruby 2.7.2 is supported in standard:5.0 https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile#L218. 

Ruby 3.0 support will be added in a future release. No ETA to share at this time though.

**Comment by mikelkew** [comment]
Thanks @subinataws. Any plans to also update the versions in [AL2 x86_64 Standard:3.0](https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/3.0/Dockerfile#L431)?

**Comment by subinataws** [comment]
@mikelkew - we won't be changing existing image, but a new version is in the works for AL2 base, which should include ruby updates.

**Comment by lmayorga1980** [comment]
Any plans to release ruby 3.x compatible runtimes?

**Comment by johnpitchko** [comment]
Also interested in ruby 3.0x runtimes for CodeBuild.

**Comment by RafaelSNascimento** [comment]
Also interested in ruby 3.0x runtimes for CodeBuild.

**Comment by subinataws** [comment]
Latest Ruby version - 3.1.x is added in https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30.
