### ISSUE TITLE
CodeBuild error

### ISSUE THREAD

**Issue by djanand2000** [aws/aws-codebuild-docker-images#432]
Hi Team, 
Until today my code build was running without any  issues  but today the builds started failing, can you please help?
ISSUE: I am running a code to install aws cli - **pip3 install --upgrade --user awscli** but it's failing with an error message.
I also tried specifying a aws cli version **pip3 install --upgrade --user awscli>=1.19.11** but it still failed.
Runtime version : aws/codebuild/nodejs:10.14.1

Downloading/unpacking PyYAML>=3.10,<5.5 from https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz#sha256=607774cbba28732bfa802b54baa7484215f530991055bb562efbed5b2f20a45e (from awscli)
  Running setup.py (path:/tmp/pip_build_root/PyYAML/setup.py) egg_info for package PyYAML
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)

-----------------------------------
Running setup.py install for PyYAML
    building 'yaml._yaml' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c yaml/_yaml.c -o build/temp.linux-x86_64-3.4/yaml/_yaml.o
    x86_64-linux-gnu-gcc: error: yaml/_yaml.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    Error compiling module, falling back to pure Python

----------------------------
aws --version
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/root/.local/lib/python3.4/site-packages/awscli/clidriver.py", line 68, in main
    driver = create_clidriver()
  File "/root/.local/lib/python3.4/site-packages/awscli/clidriver.py", line 78, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "/root/.local/lib/python3.4/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/root/.local/lib/python3.4/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/root/.local/lib/python3.4/site-packages/awscli/handlers.py", line 28, in <module>
    from awscli.customizations.cloudfront import register as register_cloudfront
  File "/root/.local/lib/python3.4/site-packages/awscli/customizations/cloudfront.py", line 17, in <module>
    import rsa
  File "/root/.local/lib/python3.4/site-packages/rsa/__init__.py", line 24, in <module>
    from rsa.key import newkeys, PrivateKey, PublicKey
  File "/root/.local/lib/python3.4/site-packages/rsa/key.py", line 36, in <module>
    import typing
ImportError: No module named 'typing'

**Comment by subinataws** [comment]
@djanand2000 - Please consider using a supported image. aws/codebuild/nodejs:10.14.1 has a base of Ubuntu 14.04, which was EOL 2 years back. These images are not maintained and will not be getting any further updates. 

If you are looking for node.js 10.x, we would recommend using standard:4.0 https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile#L221.
