### ISSUE TITLE
AWS CLI v2 support in AL2 images

### ISSUE THREAD

**Issue by fatbasstard** [aws/aws-codebuild-docker-images#433]
Hi, 

Notices the AL2 images don't contains the AWS CLI v2 yet. Based on this issue: https://github.com/aws/aws-codebuild-docker-images/issues/407 that will not be added in the "current" images.

Will there be a new `AL2` version with the V2 image coming soon? Or are these not (that) supported anymore and should we migrate to the `standard` images?

**Comment by casret** [comment]
Would love an answer to this as well, and why the aws cli (v1 or v2) is not being updated more often.  Sometimes you have to wait a quarter to get access to a feature.

**Comment by TranquilAbyss** [comment]
aws cli 1 is no longer support according to this AWS article. I hope this gets updated soon.
https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-python-3-4-and-3-5-in-the-aws-sdk-for-python-and-aws-cli-v1/

I am going to try to add an aws cli update to buildspec for now.

**Comment by subinataws** [comment]
Now supported in CodeBuild with https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30

**Comment by rob3c** [comment]
@subinataws Should this be reopened? This issue is about AL2 support, and while the ubuntu `standard:6.0` image mentioned in the link does indeed use AWS CLI v2, the AL2 `amazonlinux2-x86_64-standard:4.0` image still appears to use CLI v1.

At least, here's the output when I check the version using a recent AL2 curated image running under WSL2-based Docker Desktop in Windows 10:

```dockerfile
# dockerfile
FROM public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:4.0
```

```bash
bash-4.2# aws --version
aws-cli/1.27.64 Python/3.9.16 Linux/5.10.102.1-microsoft-standard-WSL2 botocore/1.29.64
```

**Comment by tsub** [comment]
I was having the same problem, but it seems that `public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:4.0` still has AWS CLI v1 installed and the path is preferred.

```
$ docker run -it --entrypoint=bash public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:4.0 
bash-4.2# aws --version
aws-cli/1.27.143 Python/3.9.16 Linux/6.3.9-orbstack-00173-g5c15eb5460a9 botocore/1.29.143
bash-4.2# which -a aws
/root/.pyenv/shims/aws
/usr/local/bin/aws
```

Therefore, it is possible to work around this by uninstalling AWS CLI v1.

```
bash-4.2# pip uninstall -y awscli
Found existing installation: awscli 1.27.143
Uninstalling awscli-1.27.143:
  Successfully uninstalled awscli-1.27.143
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
bash-4.2# exec $SHELL -l # Not required on CodeBuild
bash-4.2# aws --version
aws-cli/2.11.23 Python/3.11.3 Linux/6.3.9-orbstack-00173-g5c15eb5460a9 exe/x86_64.amzn.2 prompt/off
```

AWS CLI v1 has been completely removed from `public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:5.0` and AWS CLI v2 is now used by default.

```
docker run -it --entrypoint=bash public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:5.0 
bash-5.2# aws --version
aws-cli/2.11.23 Python/3.11.3 Linux/6.3.9-orbstack-00173-g5c15eb5460a9 exe/x86_64.amzn.2023 prompt/off
bash-5.2# which -a aws
/usr/local/bin/aws
```
