### ISSUE TITLE
CodeBuild [21.03.09] Dotnetcore3.1 nuget restore errors. "error NU1101: Unable to find package" 

### ISSUE THREAD

**Issue by panodk** [aws/aws-codebuild-docker-images#436]
Greetings,

I was wondering if you could help me.  Up until [21.03.09] the partial yaml snippet below executed successfully via `Codepipeline > CodeBuild`.  I successfully tested the snippet again today with build [20.09.14] and an older build.  I then switched the build to [21.03.09] and it began to throwing errors trying to restore nuget/myget packages related to the projects.

Issue appeared in `aws/codebuild/amazonlinux2-x86_64-standard:3.0-21.03.09`
Worked with `aws/codebuild/amazonlinux2-x86_64-standard:3.0-20.09.14` and older

Any suggestions if this is a bug or if this is something that can be corrected in the yaml or my solution or project?

~~~~~
version: 0.2

phases:
  install:
    commands:
      - yum install nuget -y
      - dotnet tool install -g Amazon.Lambda.Tools
      - nuget sources add -Name SomeMyGetRepoName -Source https://www.myget.org/F/SomeMyGetRepoName/auth/$MyGetAPIKey/api/v3/index.json
      - nuget restore -verbosity quiet
  build:
    commands:
      - dotnet restore

....MORE YAML...
~~~~~

## ERRORS using the latest build [21.03.09]

  | [Container] 2021/03/12 06:12:33 Running command nuget restore -verbosity quiet 
  | [Container] 2021/03/12 06:12:33 Phase complete: INSTALL State: SUCCEEDED
  | [Container] 2021/03/12 06:12:33 Phase context status code: Message:
  | [Container] 2021/03/12 06:12:33 Entering phase PRE_BUILD
  | [Container] 2021/03/12 06:12:33 Phase complete: PRE_BUILD State: SUCCEEDED
  | [Container] 2021/03/12 06:12:33 Phase context status code: Message:
  | [Container] 2021/03/12 06:12:33 Entering phase BUILD
  | [Container] 2021/03/12 06:12:33 Running command dotnet restore
  | Determining projects to restore...
  | **/codebuild/output/src087807283/src/SomeDirectory/SomeProject.csproj : error NU1101: Unable to find package SomeProject. No packages exist with this id in source(s): nuget.org [/codebuild/output/src087807283/src/SomeSolution.sln]
  | /codebuild/output/src087807283/src/SomeDirectory/SomeProject.API.csproj : error NU1101: Unable to find package SomeProject.API. No packages exist with this id in source(s): nuget.org [/codebuild/output/src087807283/src/SomeSolution.sln]
  | Failed to restore /codebuild/output/src087807283/src/SomeProject/SomeProject.csproj (in 700 ms).**
...more errors...

## SUCCESS using build [20.09.14] or prior

  | [Container] 2021/03/12 06:07:42 Running command nuget restore -verbosity quiet
  | [Container] 2021/03/12 06:07:57 Phase complete: INSTALL State: SUCCEEDED
  | [Container] 2021/03/12 06:07:57 Phase context status code: Message:
  | [Container] 2021/03/12 06:07:57 Entering phase PRE_BUILD
  | [Container] 2021/03/12 06:07:57 Phase complete: PRE_BUILD State: SUCCEEDED
  | [Container] 2021/03/12 06:07:57 Phase context status code: Message:
  | [Container] 2021/03/12 06:07:57 Entering phase BUILD
  | [Container] 2021/03/12 06:07:57 Running command dotnet restore
  | Determining projects to restore...
  | Restored /codebuild/output/src754395137/src/SomeProject/SomeProject.csproj (in 323 ms).
  | Restored /codebuild/output/src754395137/src/SomeProjectWeb/SomeProjectWeb.csproj (in 380 ms).
  | Restored /codebuild/output/src754395137/src/SomeProject.API/SomeProject.API.csproj (in 380 ms).
  | Restored /codebuild/output/src754395137/src/SomeProject.Tests/SomeProject.Tests.csproj (in 397 ms).
  |  
  | [Container] 2021/03/12 06:07:59 Phase complete: BUILD State: SUCCEEDED

Thanks in advance!

**Comment by subinataws** [comment]
Doesn't seem related to CodeBuild update. If possible, could you please try with the latest .net version instead? .net 6 is now supported in CodeBuild. Please reopen if you still face issues with the supported latest version of runtimes in CodeBuild.
