### ISSUE TITLE
Are the tools installed in the docker image guaranteed to be available? 

### ISSUE THREAD

**Issue by kreempuff** [aws/aws-codebuild-docker-images#438]
Looking at `Dockerfile` for the standard images there are several tools that are potentially useful to engineers in their builds like `pyenv`. 

Are there any guarantees that those tools will remain available across versions?

**Comment by subinataws** [comment]
As long as the tooling is maintained and has appropriate license that is acceptable (typically MIT, Apache), we plan to have them available in the Dockerfile.

**Comment by kreempuff** [comment]
Thanks!
