### ISSUE TITLE
Docker support for Ubuntu/standard/5.0

### ISSUE THREAD

**Issue by hao4** [aws/aws-codebuild-docker-images#440]
We are trying to upgrade our CodeBuild projects to Node 14. We need both nodejs and docker runtime. We notice that Ubuntu/standard/5.0 is the only image that supports Node 14, but it doesn't specify and docker runtime: https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/runtimes.yml.

Can we use docker in it? If so, which version does it support?

**Comment by subinataws** [comment]
@hao4 - Docker runtime does not need to be specified in the buildspec.yaml anymore. You can simply select the privileged mode on the CodeBuild Project to have access to docker in your build container. The version of Docker will be the tip version when the image was built. In standard:5.0 case, it is https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile#L401.
