### ISSUE TITLE
[Deadline April 30th] Standard:1.0-5.0 - apt-get update fails at https://dl.bintray.com/sbt/debian 403 

### ISSUE THREAD

**Issue by fsc-itd** [aws/aws-codebuild-docker-images#449]
Running
`apt-get update`
on `aws/codebuild/standard:5.0` results in the following error:
`
Err:2 https://dl.bintray.com/sbt/debian  InRelease
403  Forbidden [IP: 35.156.125.116 443]

...

E: Failed to fetch https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 35.156.125.116 443]
E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is not signed.
`

This seems to be a scheduled downtime of bintray and is a "Scheduled brown-out session to warn users about May 1st as sunset date for Bintray." as can be seen on [the bintray status page](https://status.bintray.com/incidents/4mzph0y8l6hk) and will last from "April 12th 6AM to 2PM Pacific Daylight Time".

**Comment by joschi** [comment]
Related issue at the SBT project:
https://github.com/sbt/sbt/issues/6294

**Comment by adriantodt** [comment]
Just a note: this breaks ALL CodeBuild images, both AL2 and Ubuntu, all versions, from 1.0 to 5.0

**Comment by m4h3** [comment]
workaround:
`rm -f /etc/apt/sources.list.d/sbt.list`

**Comment by laradji** [comment]
its the same for the version 4.0

**Comment by galenhuntington** [comment]
Is JFrog doing this just to make a point?  https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by solarmosaic-kflorence** [comment]
@galenhuntington it's a blunt instrument, but this is their way of warning people they need to migrate before bintray disappears completely.

**Comment by BlakeMStewart** [comment]
Building the image as instructed by the README:

- Run `docker build -t aws/codebuild/standard:4.0 .` to build Docker image locally

also fails with the same error

**Comment by kimberlyamandalu** [comment]
I am getting the same issue when building ubuntu standard images:
I have attached the full output of my docker build command

```
#56 49.22 + echo deb https://dl.bintray.com/sbt/debian /
#56 49.22 + tee -a /etc/apt/sources.list.d/sbt.list
#56 49.23 + apt-get install -y --no-install-recommends apt-transport-https
#56 50.52 + apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
#56 50.57 Warning: apt-key output should not be parsed (stdout is not a terminal)
#56 51.44 gpg: key 99E82A75642AC823: public key "sbt build tool <scalasbt@gmail.com>" imported
#56 51.45 gpg: Total number processed: 1
#56 51.45 gpg:               imported: 1
#56 51.64 + apt-get update
#56 53.92 E: Failed to fetch https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 34.215.63.224 443]
#56 53.92 E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is not signed.
------
executor failed running [/bin/sh -c set -ex     && mkdir -p $MAVEN_HOME     && curl -LSso /var/tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz https://apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz     && echo "$MAVEN_DOWNLOAD_SHA512 /var/tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz" | sha512sum -c -     && tar xzvf /var/tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz -C $MAVEN_HOME --strip-components=1     && rm /var/tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz     && update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 10000     && mkdir -p $MAVEN_CONFIG_HOME     && mkdir -p $GRADLE_PATH     && for version in $INSTALLED_GRADLE_VERSIONS; do {        wget -nv "https://services.gradle.org/distributions/gradle-$version-all.zip" -O "$GRADLE_PATH/gradle-$version-all.zip"        && unzip "$GRADLE_PATH/gradle-$version-all.zip" -d /usr/local        && echo "$GRADLE_DOWNLOADS_SHA256" | grep "$version" | sed "s|$version|$GRADLE_PATH/gradle-$version-all.zip|" | sha256sum -c -        && rm "$GRADLE_PATH/gradle-$version-all.zip"        && mkdir "/tmp/gradle-$version"        && "/usr/local/gradle-$version/bin/gradle" -p "/tmp/gradle-$version" wrapper        && perl -pi -e "s/gradle-$version-bin.zip/gradle-$version-all.zip/" "/tmp/gradle-$version/gradle/wrapper/gradle-wrapper.properties"        && "/tmp/gradle-$version/gradlew" -p "/tmp/gradle-$version" init        && rm -rf "/tmp/gradle-$version"        && if [ "$version" != "$GRADLE_VERSION" ]; then rm -rf "/usr/local/gradle-$version"; fi;      }; done     && ln -s /usr/local/gradle-$GRADLE_VERSION/bin/gradle /usr/bin/gradle     && rm -rf $GRADLE_PATH     && echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list     && apt-get install -y --no-install-recommends apt-transport-https     && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823     && apt-get update     && apt-get install -y --no-install-recommends sbt=$SBT_VERSION     && rm -fr /var/lib/apt/lists/* /tmp/* /var/tmp/*     && apt-get clean]: exit code: 100
[ubuntu_standard_5_build.log](https://github.com/aws/aws-codebuild-docker-images/files/6380131/ubuntu_standard_5_build.log)

```

**Comment by joschi** [comment]
@kimberlyamandalu @BlakeMStewart There was another brown-out session of JCenter yesterday.
https://status.bintray.com/incidents/kh3zbvqkvj2c

**Comment by fsc-itd** [comment]
"May 1st as sunset date for Bintray"
4 days left until all CodeBuilds using the _standard_ or _amazonlinux2-x86_64-standard_ will fail at the `apt-get update` step.

**Comment by kimberlyamandalu** [comment]
> @kimberlyamandalu @BlakeMStewart There was another brown-out session of JCenter yesterday.
> https://status.bintray.com/incidents/kh3zbvqkvj2c

@joschi thanks for the info. I can confirm that the image can be built successfully as of today 4/27/2021.

**Comment by solarmosaic-kflorence** [comment]
@fsc-itd note that the failures only occur during the building of the image, so in general CodeBuild will not be impacted unless you are referencing these images as base images in your Dockerfile builds.

**Comment by solarmosaic-kflorence** [comment]
@xgnl I see you cut the last several releases -- could you have someone look at this?

**Comment by solarmosaic-kflorence** [comment]
The latest from https://github.com/sbt/sbt/issues/6294

```
echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
sudo apt-get update
sudo apt-get install sbt
```

See: https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1

**Comment by xgnl** [comment]
> @xgnl I see you cut the last several releases -- could you have someone look at this?

Hi,

We've actually updated our images recently to address this issue, though only the maintained images are updated. Deprecated images, like Standard 1.0, were not updated. The new image release 21.04.23 is available on the console, and the release/changes will be synced to github soon.

**Comment by subinataws** [comment]
Addressed in https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.04.23
