### ISSUE TITLE
Feature request: Python 3.9 support in Amazon Linux 2 standard images

### ISSUE THREAD

**Issue by jakob-keller** [aws/aws-codebuild-docker-images#450]
Hello,

can we expect support for [Python 3.9](https://www.python.org/downloads/release/python-390/) in Amazon Linux 2 standard images any time soon? That would be really helpful, especially for aarch64.

Thanks!

**Comment by leandrorebelo** [comment]
Hey @leoherran-aws, How are you?

I saw you merged the PR and released a new version, I'm trying to use amazonlinux:2 image but I found only version 3.8 of Python.

![python38](https://user-images.githubusercontent.com/5497621/142901157-4dd4f463-6dab-4207-b5a9-140c7c60cf9e.png)

Did I make some mistake?

**Comment by jakob-keller** [comment]
> Hey @leoherran-aws, How are you?
> 
> I saw you merged the PR and released a new version, I'm trying to use amazonlinux:2 image but I found only version 3.8 of Python.
> 
> ![python38](https://user-images.githubusercontent.com/5497621/142901157-4dd4f463-6dab-4207-b5a9-140c7c60cf9e.png)
> 
> Did I make some mistake?

Hi Leandro,

this repo provides standard images to be used in AWS CodeBuild projects. If that's what you are looking for, kindly [check the documentation](https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html) on how to get started with any supported runtime, including Python 3.9.

Otherwise, you are probably looking for general guidance on how to install Python 3.9 on Amazon Linux 2 instances. A [web search](https://www.google.com/search?q=amazon+linux+2+python+3.9) yields instructions on how to achieve that.

Regards

Jakob
