### ISSUE TITLE
How to use Java8 Enviroment?

### ISSUE THREAD

**Issue by miltonhit** [aws/aws-codebuild-docker-images#458]
Is there any way to build this docker to use the java8 environment?

The default comes java11 installed

**Comment by miltonhit** [comment]
I found how to do that:

phases:
 install:
  runtime-versions:
   java: corretto8

**Comment by josephvusich** [comment]
For future reference, the entire set of supported runtime-versions can be found here: https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
