### ISSUE TITLE
Error installing python

### ISSUE THREAD

**Issue by lbolanos** [aws/aws-codebuild-docker-images#460]
I am using cloud9
The error received:

Step 49/98 : RUN   env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_37_VERSION; rm -rf /tmp/*
 ---> Running in 3a22e89c171a
Downloading Python-3.7.10.tar.xz...
-> https://www.python.org/ftp/python/3.7.10/Python-3.7.10.tar.xz
Installing Python-3.7.10...
/root/.pyenv/plugins/python-build/bin/python-build: line 715: build_package_ldflags_dirs: command not found

BUILD FAILED (Ubuntu 18.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20210522181651.52
Results logged to /tmp/python-build.20210522181651.52.log

Last 10 log lines:
/tmp/python-build.20210522181651.52 /
/tmp/python-build.20210522181651.52/Python-3.7.10 /tmp/python-build.20210522181651.52 /
Removing intermediate container 3a22e89c171a
 ---> 471624bdc9eb
Step 50/98 : RUN   pyenv global  $PYTHON_37_VERSION
 ---> Running in da1db325f112
pyenv: version `3.7.10' not installed
The command '/bin/sh -c pyenv global  $PYTHON_37_VERSION' returned a non-zero code: 1

**Comment by skwashd** [comment]
I am experiencing the same issue when trying to build the following images on amd64:

* standard 4.0
* standard 5.0
* amazonlinux2-x86_64-standard:2.0
* amazonlinux2-x86_64-standard:3.0

The [pyenv chanagelog entry for the 2.0.0 release](https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md#release-200) has an entry "ldflags_dirs is not needed for Python and causes failures". 

I did some digging and found vanilla AL2 and ubuntu:20.04 docker images worked fine with ` curl https://pyenv.run | bash` once all the documented dependencies were installed. I tracked the problem down to the `tools/runtime_configs/python/[version]` files for each of the images. They include the old ldflags_dirs step. 

Once my local builds finish I'll submit a pull request.
