### ISSUE TITLE
AWS Codebuild - sonarqube issue

### ISSUE THREAD

**Issue by AaushiMankar** [aws/aws-codebuild-docker-images#462]
/codebuild/output/tmp/script.sh: 4: /codebuild/output/tmp/script.sh: sonar-scanner: not found
[Container] 2021/05/25 06:20:57 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sonar-scanner \ -Dsonar.projectKey=****** \ -Dsonar.sources=. \ -Dsonar.host.url=http://*******:9000 \ -Dsonar.login=****** Reason: exit status 127
(Instead of astricts there are actual values in the build) 

I am getting above error while running sonarqube in AWS Codebuild. I have installed the sonar scanner and sonarqube instance in ec2 instance. PATh is also set for sonar scanner. The code repo is python in aws code commit. 
Please help.

**Comment by joschi** [comment]
It looks like `sonar-scanner` is not installed in a location which is part of the `$PATH` environment variable.

**Comment by subinataws** [comment]
@AaushiMankar - please make sure that you are not using buildspec v0.1, which doesn't persist between commands. If you are already using v0.2, this look like an issue with setting the PATH as @joschi pointed out. Resolving this, as this repo is for sharing the docker images used by CodeBuild. For any CodeBuild service issue that you are encountering, please open a support case with the relevant buildARN provided.
