### ISSUE TITLE
Cannot build ubuntu/java/openjdk-8

### ISSUE THREAD

**Issue by kaitea** [aws/aws-codebuild-docker-images#47]
When attempting to build ubuntu/java/openjdk-8, it returns the following error:

E: Version '8u141-b15-3~14.04' for 'openjdk-8-jdk' was not found

**Comment by statik** [comment]
This is affecting me as well. It looks like the version of openjdk-8-jdk was updated 11 days ago to 8u162-b12-1~14.04, see https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa

**Comment by kaitea** [comment]
awesome, verified fix works for me as well, thanks!
