### ISSUE TITLE
support Java 17 runtime

### ISSUE THREAD

**Issue by kwonglau** [aws/aws-codebuild-docker-images#482]
could we add support for Java 17 runtime

**Comment by DaanVleugels** [comment]
Is there some way to use corretto 17 while waiting for this version to be supported?

**Comment by joschi** [comment]
@DaanVleugels You could install Corretto 17 and activate it in your `buildspec.yml` similar to how it's done for Corretto 8 and 11.

Example:
https://github.com/aws/aws-codebuild-docker-images/blob/9282872af78aeb1b5df3010ed3872c40f3d0f056/ubuntu/standard/5.0/Dockerfile#L344-L359

https://github.com/aws/aws-codebuild-docker-images/blob/9282872af78aeb1b5df3010ed3872c40f3d0f056/ubuntu/standard/5.0/runtimes.yml#L25-L43

**Comment by MattFellows** [comment]
Just FYI - because I followed this advice - doing so seems to break docker in docker capability, or, more specifically, using any non-managed image seems to prevent using docker in docker currently...

**Comment by joschi** [comment]
@MattFellows How exactly did you build your custom image? I built one based on `ubuntu/standard:5.0` some time ago and I don't remember it breaking DinD.

**Comment by DaanVleugels** [comment]
@joschi, do you still have your version? I have been trying a little, but bumped against upgrading the Gradle version without breaking the old versions’ builds.

**Comment by kevintweber** [comment]
There is a PR for this request: https://github.com/aws/aws-codebuild-docker-images/pull/495

**Comment by rnferreira** [comment]
Any update about this?

**Comment by rasensio** [comment]
Looks like is stuck. So, for now, installing manually

**Comment by joschi** [comment]
@rasensio Depending on your build process, looking into [Maven Toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html) (see also [Introduction to Maven Toolchains](https://foojay.io/today/introduction-to-maven-toolchains/)) or [Gradle Toolchains](https://docs.gradle.org/7.3/userguide/toolchains.html) might be preferable since they also work on local developer machines and that way you don't need to manage JDKs on AWS CodeBuild differently.

**Comment by rasensio** [comment]
Thanks @joschi . I fixed it just with this in the buildspec.yml 

`  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - yum install java-17-amazon-corretto-devel -y
      - alternatives --set java /usr/lib/jvm/java-17-amazon-corretto.aarch64/bin/java
`

**Comment by braek** [comment]
@rasensio Which environment are you using in AWS to make this work?

**Comment by rasensio** [comment]
> @rasensio Which environment are you using in AWS to make this work?

latest amazon linux

**Comment by braek** [comment]
> > @rasensio Which environment are you using in AWS to make this work?
> 
> latest amazon linux

Thanks for the tip! Managed to get my pipeline completely running now for a project using Java 17.

I still hope Amazon will add a managed image for Java 17 in the near future though.

**Comment by AdamBien** [comment]
Corretto 17 on AWS CodeBuild and maven are working, but have to be setup manually: https://adambien.blog/roller/abien/entry/installing_java_17_amazon_corretto

However: Corretto 17 installation slows down the build pipeline and is a waste of resources.

Please support Corretto 17 in e.g. aws/codebuild/standard:6.0 to avoid the "Undifferentiated Heavy Lifting" :-)

**Comment by gyokutoku** [comment]
Here is buildspec I used for "aws/codebuild/amazonlinux2-x86_64-standard:3.0" and maven build( requires JDK environment, not JRE). Thanks @AdamBien

> env:
>   variables:
>      JAVA_HOME: "/usr/lib/jvm/java-17-amazon-corretto.x86_64/"
>   install:
>     commands:
>       - java -version
>       - yum -y install java-17-amazon-corretto
>       - update-alternatives --auto javac
>       - update-alternatives --auto java
>       - java -version

Of course you can determine the exact path by the checking the result of `ls -l /usr/lib/jvm/`

**Comment by stnor** [comment]
JDK17 has been out 6 months now. Are there any plans to roll 6.0 with coretto-17 please? I'd like a timeline and would rather not roll my own image.

**Comment by subinataws** [comment]
Addressed in https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30

**Comment by fliedonion** [comment]
Why was this issue closed ?
How about ARM ?

**Comment by MuhammadBilalYar01** [comment]
Seems like still this is an issue

**Comment by RafaJMoraes** [comment]
> Obrigado@joschi. Eu consertei apenas com isso no buildspec.yml
> 
> ` pre_build:` ` commands:` ` - echo Nothing to do in the pre_build phase...` ` - yum install java-17-amazon-corretto-devel -y` ` - alternatives --set java /usr/lib/jvm/java-17-amazon-corretto.aarch64/bin/java`

E como fica o phases?
phases:
  install:
    runtime-versions:
       java: corretto??
