### ISSUE TITLE
Input device is not a TTY, if you are using mintyy, try fixing the command with winpty

### ISSUE THREAD

**Issue by abhishek0603** [aws/aws-codebuild-docker-images#487]
Machine OS : Windows 10 pro
I have succesfully exceuted all the commands , chmod is not recognised in windows but when tried using git bash it worked well.

But while executing : 
./codebuild_build.sh -i aws/codebuild/standard:3.0 -a /home/ec2-user/environment/artifacts -s /home/ec2-user/environment/sample-web-app

it is not generating any artifacts folder.

![image](https://user-images.githubusercontent.com/84580625/138473491-b492bdd0-b64f-4f98-b834-cdaae2b49edc.png)

After this, it displays, input device is not a TTY, if you are using mintyy then try prefixing the command using winpty.

Any help would be appreciated. Thanks !

**Comment by subinataws** [comment]
Resolving in favor of https://github.com/aws/aws-codebuild-docker-images/issues/328, which is to better support the local agent in Windows.
