### ISSUE TITLE
Open to adding registry and buildkit?

### ISSUE THREAD

**Issue by rchernobelskiy** [aws/aws-codebuild-docker-images#492]
Hello,

Would you be open to adding these two, either in binary, or in docker image form?
1) registry [github](https://github.com/distribution/distribution/releases/tag/v2.7.1), [dockerhub](https://hub.docker.com/_/registry)
2) buildkit [github](https://github.com/moby/buildkit/releases/tag/v0.9.1), [dockerhub](https://hub.docker.com/r/moby/buildkit)

**Comment by subinataws** [comment]
Potentially, if that is useful for majority of the customers. Our images has grown in size and with more utilities being packaged in, it becomes a bit difficult to get timely version updates for changes that we actually want to get out sooner - security and runtime version updates. It is likely that we will trim down the list of utilities in our next major version update, with the goal on reducing the layers and overall size. Thanks for the suggestion.

**Comment by subinataws** [comment]
We are unlikely to add this in the CodeBuild images. Please feel to use custom docker image, if these utilities are important for your use case.
