### ISSUE TITLE
Underlying EC2 environment information

### ISSUE THREAD

**Issue by seangreathouse** [aws/aws-codebuild-docker-images#5]
I would like to run these images on EC2 to accelerate development against CodeBuild.
Could you document the underlying EC2 environment for CodeBuild so we can build an accurate test environment on EC2?

**Comment by dhilsand** [comment]
CodeBuild docker images should be self-contained and represent the build environment in which your builds run on the service. You should be able to run a container and download source inside it and run your build commands against it.
