### ISSUE TITLE
Feature request: Python 3.10 support

### ISSUE THREAD

**Issue by jeremypleb** [aws/aws-codebuild-docker-images#501]
Hello,

Are there plans to add support for python 3.10 in the near future? I am most interested in python 3.10 support for `aws/codebuild/standard:4.0` and/or `aws/codebuild/standard:5.0`.

Thanks!

**Comment by jakob-keller** [comment]
Support for Python 3.10 runtimes will arrive eventually, but I would not count on that happening in the near future.

Having waited for many months, I submitted #455 which added support for Python 3.9 for several standard images.

I would be glad to prepare a similar PR for Python 3.10 as soon as time permits. Most likely that won't be before the end of the year. Anyone else able to step up? Looking at AWS, too ;-)

**Comment by michael-k** [comment]
I've opened a PR.  Now it's up to AWS to review and hopefully merge.

**Comment by mberchon** [comment]
+1 ;-)

**Comment by subinataws** [comment]
Support added for Python 3.10 in the latest Ubuntu image in CodeBuild. https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30

AL2 images will get this update in the next release.
