### ISSUE TITLE
Why is PHP locked at 8.0.0? Please add more minor versions 

### ISSUE THREAD

**Issue by abbluiz** [aws/aws-codebuild-docker-images#506]
There are no available PHP runtimes for PHP 8.0.2 (PHP is 8.0.14 at the time of creation of this issue). There is also no available runtimes for PHP 8.1.

**Comment by neerajklite** [comment]
+1

**Comment by MitchellBarker** [comment]
Any updates on this? Driving me crazy

**Comment by mohammad-pouri** [comment]
This is funny!, runtimes for 7.3 and 7.4 are depricated and the only supported version is 8 which is locked to 8.0.0!
if you are not planning to release 8.1 at least include minor releases for 8. right now 8.0.16 is available. we have lot of trouble with locking the release to 8.0.0 because a big bunch of packages need at least 8.0.2

**Comment by neerajklite** [comment]
This is so careless of AWS Beanstalk team. Shame

**Comment by abbluiz** [comment]
I have stopped using PHP runtimes altogether. Now I build things inside docker. However I am still letting this issue opened, since I still think AWS should add more versions.

**Comment by AdamWills** [comment]
```
Your Composer dependencies require a PHP version ">= 8.0.2". You are running 8.0.0.
```
Would appreciate a more up to date version of PHP 8.0 available....

**Comment by AdamWills** [comment]
I've made a PR to (hopefully) help fix this.

Not sure who can take a look at it. @leoherran-aws?

**Comment by jvdven** [comment]
+1

**Comment by MajorasJack** [comment]
Please can this be addressed?

**Comment by AshrafAkon** [comment]
@abbluiz any update on this?

**Comment by abbluiz** [comment]
@AshrafAkon I stopped using the PHP runtime. During CodeBuild, I build a docker image that has the latest PHP version, though. And some steps that I were doing outside the docker image build (in the CodeBuild machine/runtime itself), I included them in the Dockerfile.

**Comment by AshrafAkon** [comment]
@abbluiz I am also thinking about doing something same. My main issue was composer. Some package uses  minimum php 8.0.2. So I am thinking about using the latest composer image and run "composer install" from there.

**Comment by edward-aslin** [comment]
I stopped using the AWS Codebuild image and switched to using the Bitnami Laravel Image.

The only other change I had to make to the build process, was to manually install the AWS Cli.

**Comment by Tarhex** [comment]
@edward-aslin care sharing a tutorial?

cause am getting this error currently:
`symfony/css-selector v6.0.3 requires php >=8.0.2 -> your php version (8.0.0) does not satisfy that requirement.`

**Comment by edward-aslin** [comment]
@Tarhex 

It will vary depending on your VPC setup etc. But essentially

1) Rather than using the Codebuild Image, switch it to the Bitnami Image. You do this in environment settings, you may have to select 'override current image' button, choose custom image and specify 'bitnami/laravel'

2) Update your build file to install the AWS Cli on the Bitnami image

```
build:
    commands:
      - echo Build started on `date`
      - echo Update package list
      - sudo apt-get update
      - echo Install AWSCLI
      - sudo apt-get -y install awscli
```

**Comment by coreykck** [comment]
+1

**Comment by Dylan-AWS** [comment]
We have updated the PHP 8.0 minor versions in #535. Going to leave open for PHP 8.1 support.

**Comment by subinataws** [comment]
Addressed in https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30
