### ISSUE TITLE
AWS standard:5.0 JDK17 custom

### ISSUE THREAD

**Issue by parriagadau7** [aws/aws-codebuild-docker-images#507]
I have a buildspec.yml when running maven wrapper get error build

phases:
  install:
    commands:
      - wget -O- https://apt.corretto.aws/corretto.key | apt-key add -
      - add-apt-repository 'deb https://apt.corretto.aws stable main'
      - apt install -y java-17-amazon-corretto-jdk
      - update-java-alternatives -s java-17-amazon-corretto
      - JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
  build:
    commands:
      - ./mvnw -v

I'm seeing these logs when running maven commands in AWS CodeBuild:

Picked up JAVA_TOOL_OPTIONS: -javaagent:/opt/tools/Log4jHotPatch_jdk8.jar=log4jFixerVerbose=false
--
  | 2022-01-06T19:39:44.178-03:00 | Exception in thread "main" java.lang.reflect.InvocationTargetException
  | 2022-01-06T19:39:44.178-03:00 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | 2022-01-06T19:39:44.178-03:00 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  | 2022-01-06T19:39:44.178-03:00 | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | 2022-01-06T19:39:44.178-03:00 | at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  | 2022-01-06T19:39:44.178-03:00 | at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
  | 2022-01-06T19:39:44.178-03:00 | at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
  | 2022-01-06T19:39:44.178-03:00 | Caused by: java.lang.IllegalAccessError: class Log4jHotPatch (in unnamed module @0x5451c3a8) cannot access class jdk.internal.org.objectweb.asm.Opcodes (in module java.base) because module java.base does not export jdk.internal.org.objectweb.asm to unnamed module @0x5451c3a8
  | 2022-01-06T19:39:44.178-03:00 | at Log4jHotPatch.asmVersion(Log4jHotPatch.java:80)
  | 2022-01-06T19:39:44.178-03:00 | at Log4jHotPatch.agentmain(Log4jHotPatch.java:102)
  | 2022-01-06T19:39:44.178-03:00 | at Log4jHotPatch.premain(Log4jHotPatch.java:157)
  | 2022-01-06T19:39:44.178-03:00 | ... 6 more
  | 2022-01-06T19:39:44.178-03:00 | *** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
  | 2022-01-06T19:39:44.178-03:00 | FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
  | 2022-01-06T19:39:46.958-03:00 | Aborted (core dumped)

**Comment by subinataws** [comment]
@parriagadau7 - Thanks for reporting the issue. Could you please retry and let us know if the issue persists?

**Comment by subinataws** [comment]
This issue should have been resolved. Let us know if you are still facing any issues.

**Comment by parriagadau7** [comment]
I have tested and success build. thanks
