### ISSUE TITLE
 AWS CodeBuild curated image aws/codebuild/standard:4:0 is not supported for projects with environment type LINUX_CONTAINER and compute type BUILD_GENERAL1_LARGE

### ISSUE THREAD

**Issue by sergioal12** [aws/aws-codebuild-docker-images#509]
**Describe the bug**
when I try create a codeBuild project with cloudformation, fails with the error:
" AWS CodeBuild curated image aws/codebuild/standard:4:0 is not supported for projects with environment type LINUX_CONTAINER and compute type BUILD_GENERAL1_LARGE"

next is the cloudformation:

salesforceBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: XXX_Salesforce_Integration
      Description: proyecto de integracion de servicios api fundacion - salesforce
      ServiceRole: !GetAtt ServiceRole.Arn
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/standard:5:0
      Source:
        Location: https://git-codecommit.${self:provider.region}.amazonaws.com/v1/repos/${self:custom.projectName}
        Type: CODECOMMIT
      TimeoutInMinutes: 10
I'm using serverless framework

**Comment by leoherran-aws** [comment]
It looks like you might have a typo in the image name. Can you update it to `aws/codebuild/standard:5.0`? 

Documentation of CodeBuild curated image names for reference: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
