### ISSUE TITLE
ubuntu/5.0 docker build failing due to typo in Dockerfile 

### ISSUE THREAD

**Issue by estebane-frb** [aws/aws-codebuild-docker-images#515]
**Describe the bug**
Line 332 in your ubuntu/5.0 Dockerfile has an extra "/" at the end that is causing docker build to fail with an ARG error.

**To Reproduce**
1. Go to aws-codebuild-docker-images/ubuntu/standard/5.0
2. Run docker build -t aws/codebuild/standard:5.0 .
3. You'll see error "Error response from daemon: Dockerfile parse error line 332: ARG requires exactly one argument"

**Expected behavior**
Build of image should run without issue

**Logs**
"Error response from daemon: Dockerfile parse error line 332: ARG requires exactly one argument"

**Platform (please complete the following information):**
 - Mac x86

**Additional context**
N/A

**Comment by Dylan-AWS** [comment]
Thanks for reporting this was removed in latest release
