### ISSUE TITLE
Add support for Go 1.18 and update other versions to latest security patches

### ISSUE THREAD

**Issue by friimaind** [aws/aws-codebuild-docker-images#518]
Following the problems born on Bitbucket (reference: https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-Bitbucket-API-Requires-Latest-Version-of-Go/ba-p/1975819) in the future it will probably be problematic (or impossible) to build with the current versions of Go.

it is necessary to update the versions of Go to the latest patches (1.16.15, 1.17.8)

It would also be very useful to integrate golang 1.18 support

**Comment by joekendal** [comment]
We're also waiting for Go 1.17

**Comment by Dylan-AWS** [comment]
We have updated the versions for go 14, 15 and 16 in #535. Leaving this issue open to support Go 17 and Go 18

**Comment by subinataws** [comment]
Addressed in https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30
