### ISSUE TITLE
not able to build the with gradle 7

### ISSUE THREAD

**Issue by naresh-nakireddi** [aws/aws-codebuild-docker-images#520]
I am getting this error: while requires Gradle 6.8.x, 6.9.x, or 7.x. The current version is Gradle 5.6.
How can i get the latest version of gradle

**Comment by subinataws** [comment]
Gradle 7 is available in the latest CodeBuild images in https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30. Let us know if you face any more issues. Thanks.
