### ISSUE TITLE
Could not build NodeJS code as usual

### ISSUE THREAD

**Issue by mvn-bachhuynh-dn** [aws/aws-codebuild-docker-images#521]
Hi there,
Is there any updates on 
ubuntu standard 5.0
runtime-versions:
      nodejs: 14

My build were failed today, but already success yesterday.

I don't know why, I tried o build with the same source code (with the success previous) but still failed.

Thank you!

**Comment by subinataws** [comment]
@mvn-bachhuynh-dn - If the issue persists, could you please post on AWS forums @ https://repost.aws/tags/TA3PlC5MYDQLSIC8057qi90w ? You would want to provide the build command that is failing.
