### ISSUE TITLE
Please Update Node 14

### ISSUE THREAD

**Issue by wilhen01** [aws/aws-codebuild-docker-images#525]
Current images bundle Node `v14.17.2` but the latest is `v4.19.1`. Some packages (e.g. `pnpm` require a newer Node version than the images support. Any chance of updating this?

Node 16 support would also be nice but that's covered in https://github.com/aws/aws-codebuild-docker-images/issues/490

**Comment by Dylan-AWS** [comment]
This has been addressed in #535. Closing this issue
