### ISSUE TITLE
AWS CodeBuild [request] - Make it possible to create a hot standby Codebuild instance to reduce PROVISIONING time

### ISSUE THREAD

**Issue by xXPOLYGONXx** [aws/aws-codebuild-docker-images#526]
Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Tell us about your request

Since CodeBuild executes builds in containers which run on single-tenanted Amazon EC2 instances within a service-managed VPC and these instances will always be newly provisioned before running codebuild the provisioning times exceed 90 seconds per run. This may not be problematic for a single Codebuild Project, but when using Codepipeline, exspecially CDK Pipelines with self mutation, there are possibly many Codebuild-Steps in a single Pipeline. So the provisioning times add up rather quickly.

The proposal is to implement a way for creating dedicated Codebuild instances for your own VPC (for example on ec2) which can be used as a kind of hot-standby for your own Codebuild Projects. Because these will not be deleted after running and are already configured in your VPC it should be possible to reduce the provisioning time by a good amount. The only drawback would be extra cost for reserving more resources, but that could be price some people are willing to pay for faster builds. Maybe this could be implemented similar to the local build Feature of Codebuild.

**Comment by MacHu-GWU** [comment]
yeah, the codebuild provisioning time is super unstable, even with latest curated image. Sometimes 5 sec, sometimes 240 seconds. I guess AWS randomly pick EC2 to run the job, and if the EC2 happen to be the first time using the image, it takes long.

**Comment by prashantb1980** [comment]
I second this. This feature needs to be implemented

**Comment by prashantb1980** [comment]
+1

**Comment by cobar79** [comment]
+1

**Comment by taoyong-ty** [comment]
Please check out the Reserved Capacity feature to see if it could benefit your use case. https://aws.amazon.com/about-aws/whats-new/2024/01/aws-codebuild-reserved-capacity/#:~:text=AWS%20CodeBuild%20now%20supports%20reserved,%2Dto%2Ddeploy%20software%20packages.

**Comment by subinataws** [comment]
CodeBuild's reserved capacity is launched as linked above. It doesn't support VPC yet, but that's planned in the upcoming weeks. Resolving.

**Comment by CYWong-Nick** [comment]
> CodeBuild's reserved capacity is launched as linked above. It doesn't support VPC yet, but that's planned in the upcoming weeks. Resolving.

When will VPC connectivity be added? VPC is the core of enterprise architecture, reserved capacity is merely useful without VPC.

**Comment by subinataws** [comment]
VPC connectivity is now supported for Reserved capacity feature in CodeBuild: https://aws.amazon.com/about-aws/whats-new/2024/05/aws-codebuild-connecting-vpc-reserved-capacity/.

**Comment by rgoltz** [comment]
Thanks a lot for providing reserved capacity fleets with VPC-support capability in AWS CodeBuild 🥇 

Getting Support in CloudFormation/CDK to define such configuration in IaC is addressed here: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/2047 - You are welcome to upvote 👍 the linked issue in CFN repo.

**Comment by rgoltz** [comment]
@subinataws - Any chance to implement the property [ScalingConfiguration](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_Fleet.html#CodeBuild-Type-Fleet-scalingConfiguration) in CloudFormation? It's already addressed here: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1998 and it's blocking us to get the CDK L2 construct for CodeBuild Fleet Feature (which is based on CloudFormation) ready.
