### ISSUE TITLE
Add suport for PHP 7.1 and 7.2

### ISSUE THREAD

**Issue by rdehnhardt** [aws/aws-codebuild-docker-images#53]
To build some projects in php, some framewors are already requesting version 7.1 or version 7.2 of PHP

**Comment by rdehnhardt** [comment]
I create this PR #54 and I work on PHP 7.2

**Comment by amorphic** [comment]
@rdehnhardt sorry to bother you, I just answered my own question by reading [the docs](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref.html)...

>When you provide information to AWS CodeBuild about the build environment, you specify the identifier of a Docker image in a supported repository type. These include the AWS CodeBuild Docker image repository, publicly available images in Docker Hub, and Amazon Elastic Container Registry (Amazon ECR) repositories in your AWS account.

**Comment by kwhat** [comment]
This codebuild process is a total dumpster fire as far as PHP is concerned.  What genius over there decided that PHP 7.3 was a good idea for Ubuntu 18.04?  It's not supported by upstream and you numb-skulls didn't include the majority of extensions with it!  For example, where is php7.3-zip? To add insult to injury, the same idiot(s) made sure that a run-time environment is required to spin up one of these images so trying to create an empty image and installing PHP 7.2 is not possible! Great Job!  So now I need to sit down and spend even more time trying to figure out how to create a custom docker image to work in your shit-tastic environment just so I can build code against PHP 7.2 with the required extensions just to turn around and deploy to EC2.  Does anyone over there think about the problem at hand, or do you just code up a half-baked solution and then say its worth $500 million?
