### ISSUE TITLE
Add support for Docker runtime 20

### ISSUE THREAD

**Issue by Andykmcc** [aws/aws-codebuild-docker-images#531]
**Describe the bug**
When trying to use docker version 20 to build an image with amazon linux 2 it fails with the error `Phase context status code: YAML_FILE_ERROR Message: Unknown runtime version named '20' of docker. This build image has the following versions: 18, 19`. Is adding support for docker 20 on a roadmap? If so, what is the expected timeframe for support?

**To Reproduce**
1. Make a new buildspec. 
2. include the following phase 
```
phases:
  install:
    runtime-versions:
      docker: 20
...
```
**Expected behavior**
The build should succeed using docker 20

**Logs**
`Phase context status code: YAML_FILE_ERROR Message: Unknown runtime version named '20' of docker. This build image has the following versions: 18, 19`

**Platform (please complete the following information):**
- aws/codebuild/amazonlinux2-x86_64-standard:3.0

**Comment by subinataws** [comment]
Addressed in https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30

**Comment by rahulpatil118** [comment]
<img width="994" alt="Screenshot 2022-11-25 at 12 25 54 AM" src="https://user-images.githubusercontent.com/51319757/203850707-c2767a17-7e45-4584-b098-a02359df8ca4.png">

**Comment by rahulpatil118** [comment]
you have to enable privileged for this to run docker
