### ISSUE TITLE
Yum Not found

### ISSUE THREAD

**Issue by umesh2611** [aws/aws-codebuild-docker-images#536]
We are using  the public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:3.0  as the base image to creat an image which would package all the build libraries.

Since yestarday, when we try to build the docker image , it complains of Yum not found.
****

8dc3e265e99c: Pull complete
--
1973 | Digest: sha256:3864e804495a46ef6b57ddd49381e938f454e46747f6013a732b1e1444a52f29
1974 | Status: Downloaded newer image for public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:3.0
1975 | ---> 6c9d62d9d1ab
1976 | Step 2/16 : RUN yum update -y
1977 | ---> Running in 95fc43009d3a
1978 | time="2022-06-10T08:15:15.439293147Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/95fc43009d3adde85010c849c52911945846ee0399994f57d4920e0ffef59bea pid=1538
1979 | /bin/sh: 1: yum: not found
1980 | time="2022-06-10T08:15:15.775051324Z" level=info msg="ignoring event" container=95fc43009d3adde85010c849c52911945846ee0399994f57d4920e0ffef59bea module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
1981 | time="2022-06-10T08:15:15.775144695Z" level=info msg="shim disconnected" id=95fc43009d3adde85010c849c52911945846ee0399994f57d4920e0ffef59bea
1982 | time="2022-06-10T08:15:15.776368546Z" level=error msg="copy shim log" error="read /proc/self/fd/14: file already closed"
1983 | The command '/bin/sh -c yum update -y' returned a non-zero code: 127
1984 | [100%] fail: docker build --tag cdkasset-08f2c91b56b86aaf4d405187597fa6b80249485eba6ae7209612eae00a75f6d7 . exited with error code 127: The command '/bin/sh -c yum update -y' returned a non-zero code: 127
********************

Any help is highly appreciated.

**Comment by mkillik-nextgen** [comment]
Same, it looks like the Ubuntu based standard image was pushed to the amazonlinux2 public ECR repo.

**Comment by nbaillie** [comment]
Im seeing this also. is there expected time to resolve or should we look to pin to the last good tag? (3.0-22.03.15, was working)

**Comment by alistairfay** [comment]
I'm seeing this too, any update would be appreicated

**Comment by umesh2611** [comment]
I close the issue as it has been fixed with the latest image.
