### ISSUE TITLE
Recent version release 22.06.09 removes PHP sodium support that was previously added to Ubuntu 5.0

### ISSUE THREAD

**Issue by theschoolmaster** [aws/aws-codebuild-docker-images#538]
More of a regression than a bug.  Commit 2dea17b411022d9847c6abda34ff6f9c07287982 removes the libsodium support added by PR #464 somewhat silently.  

I request it be re-added.

Let me know if you'd like me to build the PR to re-add, or if there is some other reason it's been removed that I've missed.  Thanks.

**Comment by jmonte-sph** [comment]
+1 on this, we needed libsodium for PHP 8 in our current project

**Comment by chunyang-sph** [comment]
+2, need libsodium for 8.0.18, and if possible upgrade to 8.0.20

**Comment by Dylan-AWS** [comment]
[23.02.16](https://github.com/aws/aws-codebuild-docker-images/tree/23.02.16) libsodium was added to standard 6.0 as part of latest release
