### ISSUE TITLE
Typo in runtypes.yaml?

### ISSUE THREAD

**Issue by arnaslu** [aws/aws-codebuild-docker-images#541]
**Describe the bug**
While looking at available Docker runtimes, I found that both versions 18 and 19 echoing that they are running version 19 - https://github.com/aws/aws-codebuild-docker-images/blob/2dea17b411022d9847c6abda34ff6f9c07287982/al2/x86_64/standard/3.0/runtimes.yml#L118

**To Reproduce**
1. Go to https://github.com/aws/aws-codebuild-docker-images/blob/2dea17b411022d9847c6abda34ff6f9c07287982/al2/x86_64/standard/3.0/runtimes.yml#L118

**Expected behavior**
Expected version 18 to echo "Using Docker 18"

**Comment by subinataws** [comment]
Thanks for highlighting. This is not a typo, regardless of selecting any version of docker the latest available on the image will be used.
