### ISSUE TITLE
AWS CLI v2 support in all aarch64 (Graviton) images

### ISSUE THREAD

**Issue by otterley** [aws/aws-codebuild-docker-images#547]
AWS CLI v2 support was added per #433 but this was not complete - it needs to be done for aarch64 (Graviton) as well.

**Comment by mspinelli23** [comment]
Bumping this issue, we really need an updated aarch64 image. Including the aws-cli, these older images cannot support the newest versions of node.

**Comment by ybron** [comment]
It's 2023 now, and we're still waiting on AWS to support AWS CLI v2 on the images that run on the platform that they're pushing (Graviton).

For all of the incentives that AWS is providing to use Graviton, the amount of support to make it a first-class development and runtime environment is severely lacking and suggests that Intel will be the primary platform going forward.
