### ISSUE TITLE
[Feature Request] Add support for ENTRYPOINTs in custom Codebuild Images

### ISSUE THREAD

**Issue by cbrgm** [aws/aws-codebuild-docker-images#551]
**Describe the bug**

Hello all. Almost 3 years ago there was a similar ticket where it was found that CodeBuild overwrites `ENTRYPOINT` statements in custom Codebuild images.

Since the discussion was closed and it was announced that this feature will be added in the future, I would like to reopen the discussion and ask about the status. 

Unfortunately, I can't find any details anywhere about why the entry point is overwritten and what exactly is done instead. We would love to provide our developers with custom images to set runtime versions as environment variables instead of executing the statements every time in Codebuild after container startup. Unfortunately, this is not possible because our entrypoint script is not taken into account.

Related: https://github.com/aws/aws-codebuild-docker-images/issues/254

**Expected behavior**

`ENTRYPOINT` statement in [OCI-spec compliant](https://github.com/opencontainers/image-spec) container images works as expected and is not overwritten.

**Platform (please complete the following information):**
 - OS: Any

**Comment by subinataws** [comment]
Let's please track this in the original feature request in https://github.com/aws/aws-codebuild-docker-images/issues/254. The status is unfortunately still the same and this ask continues to be on the team's backlog.
