### ISSUE TITLE
Possibility to add custom runtime-versions

### ISSUE THREAD

**Issue by pnomolos** [aws/aws-codebuild-docker-images#556]
I was unable to find any documentation on this, but based on my testing the assumption is that this isn't currently supported.

We utilize Ruby and during testing it would be useful to be able to test against future versions of Ruby - I was hoping to extend the base codebuild image and expand the versions of Ruby that are installed, and likewise customize the `runtimes.yml` file to expose the other versions of Ruby that were installed.  However, it doesn't appear to work that way (looks like the runtime versions available to the AWS-provided images are also coded elsewhere).

Has any thought been given to making this a possibility?  I'm aware that i could do some trickery in `docker-entrypoint.sh` to make this happen but was hoping to piggyback off the work already done by the CodeBuild team.

**Comment by marcoreni** [comment]
I was able to add custom runtimes for NodeJ by extending the base image and overwriting the runtimes.yml file. Obviously my CodeBuild jobs will need to use the custom built image.

What errors are you encountering with Ruby? By looking at how it is done I think it should be similar to NodeJS.

**Comment by pnomolos** [comment]
@marcoreni I was getting a "this runtime does not exist" error, even though it was listed in `runtimes.yml`.  My use-case may be a little more in-depth, though.  The image that is being used on CodeBuild is based off of our root image, which is in turn basically a copy of the AWS CodeBuild image (with some tools removed, and the additional Ruby versions added).  I wonder if that has anything to do with the issue.

**Comment by pnomolos** [comment]
Closing this - turns out my build process was messed up and images weren't being pushed to the container registry, which is why it wasn't picking up the custom runtimes.
