### ISSUE TITLE
Consider supporting the last two versions of each runtime in the latest images

### ISSUE THREAD

**Issue by dls314** [aws/aws-codebuild-docker-images#559]
**Describe the bug**
The `aws/codebuild/standard:6.0` image only supports the latest version of each runtime; this means that upgrading a CodeBuild job to this image version has to be done in lock-step with upgrading the project buildspec.yml files and project source files. It would be far nicer to have support that overlaps older images so that upgrades can be staggered and don't have to be done in lock-step.

**Additional context**
The lock-step hits me when asking infrastructure teams to maintain CodeBuild/CodePipeline definitions used by development teams. Development teams using NodeJS 14 have to plan closely coordinated work with infrastructure teams who can't upgrade infrastructure to enable NodeJS 16 without breaking development because there is only one version of the runtime supported in the image.

**Comment by lorengordon** [comment]
This would be amazing. Python 3.10 isn't even available for Lambda functions. So if I'm using `aws/codebuild/standard:6.0`, and I want to ensure the lambda is packaged with the same runtime that is going to execute it (to avoid issues with package versions), I have to install the correct python version first. Means the builds are much slower, and its a pretty frustrating user experience overall.

**Comment by subinataws** [comment]
AWS CodeBuild team member here. Supporting multiple runtime versions within an image led to several sharp edges for our customers. Going forward, we unfortunately can only support a single version of each language runtime in the combined image, which will be the latest supported version at the time of the image release.

**Comment by dls314** [comment]
@subinataws, Any chance that you could describe some of these sharp edges? We found the lack of multiple versions to be quite a problem, honestly.

**Comment by dls314** [comment]
Related (essentially duplicate) - https://github.com/aws/aws-codebuild-docker-images/issues/608
