### ISSUE TITLE
Feature request: include CloudFormation helper scripts in the image

### ISSUE THREAD

**Issue by moltar** [aws/aws-codebuild-docker-images#572]
Use case: ability to use `cfn-signal` from CodeBuild during CF deployment.

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-signal.html

**Comment by subinataws** [comment]
@moltar - Thanks for requesting the feature. CodeBuild images are extremely large at this point and we are not looking to add any more utilities, outside of core language runtimes and build tools associated with those languages are. We unfortunately will not be able to add these CFN utilities in our image at this time.
