### ISSUE TITLE
Feature request: Python 3.11 support

### ISSUE THREAD

**Issue by michael-k** [aws/aws-codebuild-docker-images#573]
Please add support for Python 3.11 to the next `aws/codebuild/standard` image.

Python 3.11 has been released on 2022-10-24, see https://pythoninsider.blogspot.com/2022/10/python-3110-is-now-available.html

**Comment by joshuabaird** [comment]
Are there any plans to introduce support for Python 3.11 (and even 3.10) in the AL2 images?

**Comment by Dylan-AWS** [comment]
Added python 11 support to Ubuntu 7.0 #621
