### ISSUE TITLE
Add support for Java 17 to aarch64 AL2 images

### ISSUE THREAD

**Issue by peter-thomas-mgd** [aws/aws-codebuild-docker-images#586]
Please add support for corretto-17 to the official Amazon Linux 2 images for ARM. Java 17 is now the minimum to build the current version of Spring Boot. Currently to target our application on ARM, we must add this dependency manually. Since this was recently added to the x86_64 images, it should be relatively straightforward to publish an ARM image with the same.

**Comment by rafal-what2do** [comment]
Hi guys! I confirm @peter-thomas-mgd words. Will you implement it?

**Comment by Dylan-AWS** [comment]
This is now installed on ARM 3.0 #627
