### ISSUE TITLE
Upgrade docker-compose to 2.13.0 at least from docker-compose 2.6.0

### ISSUE THREAD

**Issue by debraj-manna** [aws/aws-codebuild-docker-images#588]
docker-compose 2.6.0 present in `aws/codebuild/standard:6.0` has a bug which does not allow `ps` filter to work properly. The issue has been discussed in 

1. [Stackoverflow](https://stackoverflow.com/questions/74855696/docker-compose-displaying-all-services-not-the-one-defined-in-docker-compose-yml)
2. [Docker community](https://forums.docker.com/t/docker-compose-displaying-all-services-not-the-one-defined-in-docker-compose-yml/133157)

The fix for the issue has been added in docker-compose 2.13.0 as confirmed [here](https://forums.docker.com/t/docker-compose-displaying-all-services-not-the-one-defined-in-docker-compose-yml/133157/6?u=debrajmanna).

**Comment by subinataws** [comment]
Updated docker compose is available in aws/codebuild/standard:7.0. https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/7.0/Dockerfile#L329. Resolving.
