### ISSUE TITLE
Add browsers to standard 6.0

### ISSUE THREAD

**Issue by rameshkumarj** [aws/aws-codebuild-docker-images#593]
Describe the bug:
Add chrome and other browsers to the docker image as similar to standard 5.0

Expected behaviour:
Latest stable version of chrome and other browsers to be available in the docker image

**Comment by masukkazi1-nhs** [comment]
Is there a timeframe for this being picked up for development?

**Comment by jwalsh2me** [comment]
Any update on this?

**Comment by jiang-gao** [comment]
Any update on this? will 6.0 support chrome driver? or it is meant to be removed forever?

**Comment by aqsyed** [comment]
I was wondering if there was an update to this issue ? will the chrome binaries be added soon ?

**Comment by subinataws** [comment]
Lets track in https://github.com/aws/aws-codebuild-docker-images/issues/562
