### ISSUE TITLE
aws/codebuild/standard:5.0 (6.0) apt-get update -y fails reason: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid

### ISSUE THREAD

**Issue by IharKotau** [aws/aws-codebuild-docker-images#594]
**Describe the bug**
We are using the aws/codebuild/standard:5.0 in a  CodeBuild. The build fails at apt-get update -y exit status 100

Reason:
Err:2 https://dl.yarnpkg.com/debian stable InRelease
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>

**To Reproduce**
1. Run Codebuild based on aws/codebuild/standard:5.0
2. apt-get update

**Expected behavior**
No errors, exit code 0

**Logs**
Reading package lists...
W: https://dl.yarnpkg.com/debian/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
W: https://apt.corretto.aws/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Platform (please complete the following information):**
 - OS:  aws/codebuild/standard:5.0 and 6.0

**Additional context**

**Comment by michielvermeir** [comment]
This issue is easy enough to solve by adding a step to refresh the GPG keys, but would be grand if the CodeBuild team could release updates of `aws/codebuild/standard:5.0` and `6.0` with the updated signatures baked in.

**Comment by IharKotau** [comment]
Yes, you need to add this to build spec to fix temporarily:

```
    commands:
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - apt-get update
```

**Comment by fouadchamoun** [comment]
same issue on  aws/codebuild/standard:4.0

**Comment by ebarault** [comment]
according to AWS support team, "This fix will be propagated to all CodeBuild images by 1/31/2023." :-/

**Comment by awszhen** [comment]
CodeBuild team here, we will be patching the Ubuntu standard images today.

**Comment by aahung** [comment]
related: https://github.com/yarnpkg/yarn/issues/7866

**Comment by awszhen** [comment]
Hi, the Ubuntu standard images have been patched. Please retry, thanks.
