### ISSUE TITLE
Feature request: Golang 1.19 support 

### ISSUE THREAD

**Issue by Igor-ozerskii** [aws/aws-codebuild-docker-images#598]
Please add support for Golang 1.19 to the next aws/codebuild/standard image.

Golang 1.19  has been released on 2022-08-02, see https://go.dev/doc/devel/release#go1.19

**Comment by atkinsjb** [comment]
Go 1.20 is already out. When can we expect support for go 1.19?

**Comment by adnanataws** [comment]
We are planning to release Go 1.20 in couple of weeks time for Ubuntu based images. 

Amazon Linux base image is being updated to AL2023 and will get Go 1.20 support a few weeks after that, likely by mid-May.

**Comment by Dylan-AWS** [comment]
Added node18 support to Ubuntu 7.0 #621
