### ISSUE TITLE
Broken AWS CLI in standard:4.0

### ISSUE THREAD

**Issue by plumdog** [aws/aws-codebuild-docker-images#601]
**Describe the bug**

The AWS CLI in standard:4.0 is broken:
```
[Container] 2023/02/20 09:26:25 Running command aws --version
pyenv: version `3.7.13' is not installed (set by /codebuild/output/src113788041/src/.python-version)
```

**To Reproduce**
Run any `aws` command on a standard:4.0 image.

**Expected behavior**
AWS CLI should work without error.

**Additional context**
Seeing this in both eu-west-1 and eu-west-2.

Unable to find the images published anywhere, which makes debugging hard. Am building locally to try to debug.

**Comment by plumdog** [comment]
Think this is almost certainly caused by https://github.com/aws/aws-codebuild-docker-images/commit/432c1eac56f5dffcc07e3e8df6ba2278c04ba040#diff-e05d963f6ff2d3808c812b5f9b77e501059cbfdc7c24cb579188ce1ceb932fceL243-R245

**Comment by plumdog** [comment]
Workaround: run `echo 3.7.16 > .python-version` before any AWS CLI commands.

**Comment by Dylan-AWS** [comment]
Hi, I was not able to reproduce the error. Can you open a ticket with AWS Support and provide a build arn?

**Comment by subinataws** [comment]
We can't reproduce this in the standard 4.0 images that CodeBuild provides that are based on Ubuntu or AL2 in the region that were called out. Marking this resolved. However, feel free to comment on this issue, if you continue to see an issue. Do mention the specific image, including any tag version that you may be using.

**Comment by plumdog** [comment]
I have found that this is because my source project has a `.python-version` in the root of the repo. This happened to be 3.7.13, so matched with the version in Codebuild previously.

So I guess there's some set of files in the initial working directory for one of these images, and if your project has a file that collides with it, you're going to get some odd behaviour. (Again, not being able to just `docker run ...` this image makes finding this a real pain.)

How can I workaround this?
