### ISSUE TITLE
Add Java corretto 8 and 11 to Ubuntu Standard 6.0

### ISSUE THREAD

**Issue by kimmoahokas** [aws/aws-codebuild-docker-images#604]
We received communication from AWS that the `Ubuntu Standard 4.0` and `Ubuntu Standard 5.0` images will be deprecated at the end of March 2023. For various reasons we still depend on AWS Java corretto JVM versions 8 and 11 that are LTS supported until April 2026 and July 2029 respectively. (see https://aws.amazon.com/corretto/faqs/).

Please add these long-term supported Frameworks to the latest supported `Ubuntu Standard 6.0` image.

At the same time it would be great to have these on `Amazon Linux 2 standard 4.0` and `Amazon Linux 2 ARM standard 2.0` images.

**Comment by charlie-harvey** [comment]
https://github.com/aws/aws-lambda-base-images/issues/29

With Java17 on Lambda still not really ready for prime time, this really puts a squeeze on us. I have to move to Ubuntu Standard 6, but if I do, I can't have Java11 anymore.
Now, I can use a Java17 build and target Java11. But come on.

**Comment by kimmoahokas** [comment]
I'll also elaborate a bit: We are using [Play Framework](https://www.playframework.com/) which currently does not build with Java 17. Java 17 support is coming and we are planning to migrate to new version as soon as possible, but at the moment Java 11 is a hard requirement.

Sure, we can still use `Ubuntu Standard 5.0` but having unpatched vulnerabilities in the build image is not good either. Especially having the Corretto JVM up-to-date is crucial as it can affect the JVM bytecode generation.

**Comment by kimmoahokas** [comment]
Thank you for the information @subinataws
