### ISSUE TITLE
Add Node 18 to current image variants.

### ISSUE THREAD

**Issue by kimmoahokas** [aws/aws-codebuild-docker-images#607]
The [LTS support for Node 16 is ending 2023-09-11](https://github.com/nodejs/Release). Please add support for the next LTS release, Node 18 as soon as possible. We need to start migrating our workloads soon, but can't really do that without CodeBuild support.

**Comment by JoeFirebaugh** [comment]
For what it's worth, this is how our team uses NodeJS 18 in our builds.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/930703/224806586-77014eee-a00b-401f-9a21-7e470cb5ee83.png">

**Comment by kimmoahokas** [comment]
Yes, I'm aware of that and have been using it as well in some less-critical builds. But in the longer run I'm rather hesitant to use a feature that is not documented and officially supported.

**Comment by subinataws** [comment]
Node 18 should be support on Ubuntu based image in a couple of weeks from now. Amazon Linux image will be updated to AL2023 base and support Node 18 by mid-May.

**Comment by Dylan-AWS** [comment]
Added node18 support to Ubuntu 7.0 #621

**Comment by mfittko** [comment]
Can we also get this for the AMAZON_LINUX2 based images? What about AARCH/ARM? It would be really odd if we couldn't use codebuild for our project since we're on graviton2 (ARM), ruby 3.1 and node LTS (18)...

**Comment by subinataws** [comment]
Arm images will get an update next week. AL2023 updates by mid-May.

**Comment by mfittko** [comment]
> Arm images will get an update next week. AL2023 updates by mid-May.

Sounds great 👍 Will the ARM images also be not deprecated then? I just saw that these images are like 3gb so it's really not an option for us if they won't be cached.

**Comment by subinataws** [comment]
Older images will need to be dropped from cache, so as to make space for the newer versions. Customers will get heads up before they are dropped from cache. All the supported versions will still be cached on the build server's AMI, which is typically the latest version (say, n) and the just prior version (n-1).

We will look into re-introducing per language runtimes to avoid long provisioning times when images are no longer cached. Offering multiple version of runtimes on the same image makes these images quite big unfortunately.

**Comment by mfittko** [comment]
yeah, thanks for the insights @subinataws . to me, as building  long time CircleCI customer, it is also a bit odd, not to be able to build your own image on top of the base. so why not just provide barebone base images like https://github.com/CircleCI-Public/cimg-base where we could add whatever lib or binary we would need to, so basically only our additional layers would not be cached on the runners if we'd provide these on ECR for ourselves?

**Comment by subinataws** [comment]
@mfittko - Thanks for bringing that up. We certainly can host the CodeBuild images that are based on Amazon Linux (unfortunately not for Ubuntu) on https://gallery.ecr.aws/codebuild. We have the x86 version there and I see that we never published the Arm ones. We'll get that published on there as well. You can derive from those public images to extend your custom images.

**Comment by mfittko** [comment]
That would be super awesome. I just hope that given the huge size of these images, that also the layers of these ECR hosted images will be cached on the build hosts? Are the build hosts picked based on the architecture of the image or will they all be ran (emulated on an AMD64 host)?

**Comment by subinataws** [comment]
Build instances are picked based on the architecture selected in the CodeBuild project.

**Comment by vitorhnn** [comment]
Any update on the new ARM images? This is blocking us from upgrading to Node 18 for our builds.

**Comment by Dylan-AWS** [comment]
Noe8 is supported on ARM #627

**Comment by walkerchiu** [comment]
I'm using AWS Copilot to build a Fargate-based ECS, and I get the following error during the CodeBuild stage:

[Container] 2023/05/11 15:08:29 Running command n 18.16.0
--
74 | installing : node-v18.16.0
75 | mkdir : /usr/local/n/versions/node/18.16.0
76 | fetch : https://nodejs.org/dist/v18.16.0/node-v18.16.0-linux-x64.tar.xz
77 | copying : node/18.16.0
78 | node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
79 | node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
80 | /usr/local/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/bin/node)
81 | /usr/local/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/node)
82 | installed :  (with npm )
83 |  
84 | [Container] 2023/05/11 15:08:45 Running command npm config set @fortawesome:registry https://npm.fontawesome.com/
85 | node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
86 | node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
87 |  
88 | [Container] 2023/05/11 15:08:45 Command did not exit successfully npm config set @fortawesome:registry https://npm.fontawesome.com/ exit status 1
89 | [Container] 2023/05/11 15:08:45 Phase complete: BUILD State: FAILED
90 | [Container] 2023/05/11 15:08:45 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm config set @fortawesome:registry https://npm.fontawesome.com/. Reason: exit status 1
91 | [Container] 2023/05/11 15:08:45 Entering phase POST_BUILD
92 | [Container] 2023/05/11 15:08:45 Running command ls -l
93 | total 42712
94 | -rw-r--r-- 1 r

But using the 16.16 version is no problem.

**Comment by subinataws** [comment]
Node 18 is now supported in amazonlinux2-x86_64-standard:5.0 https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/5.0/runtimes.yml#L51
