### ISSUE TITLE
Create new images for Amazon Linux 2023

### ISSUE THREAD

**Issue by chasegarner** [aws/aws-codebuild-docker-images#613]
Is there an ETA for new images that use Amazon Linux 2023?

They’d solve most of the known issues with the existing images (eg: old GLIBC, having to manually install new runtimes, etc).

**Comment by nyashamk** [comment]
ETA has been shared in a related issue  #599 

> This will be supported in Ubuntu based images in a couple of weeks. Amazon Linux base image is being updated to AL2023 and will get this support a few weeks after that, likely by mid-May.

**Comment by subinataws** [comment]
This is available now in amazonlinux2-x86_64-standard:5.0.
