### ISSUE TITLE
Add PHP 8.2 Support 

### ISSUE THREAD

**Issue by likeadeckofcards** [aws/aws-codebuild-docker-images#614]
There is an open request for adding [PHP 8.2 to Elastic Beanstalk](https://github.com/aws/elastic-beanstalk-roadmap/issues/250). In order to use Code Build with Elastic Beanstalk, PHP 8.2 needs to be offered as a supported version of Code Build.

**Comment by subinataws** [comment]
This will be supported in Ubuntu based images in a couple of weeks. Amazon Linux base image is being updated to AL2023 and will get this support a few weeks after that, likely by mid-May.

**Comment by Dylan-AWS** [comment]
Added php 8.2 support to ubuntu 7.0

**Comment by darylteo** [comment]
Hi team, this doesn't seem to be working on the official images.

![CodeBuild - AWS Developer Tools (2)](https://user-images.githubusercontent.com/1226920/235573882-2c36fa28-799c-4bd5-83d1-84054ca4c56e.png)
![CodeBuild - AWS Developer Tools (3)](https://user-images.githubusercontent.com/1226920/235573869-411cda8c-8db2-419e-8102-a3ef403d94fa.png)
![CodeBuild - AWS Developer Tools (1)](https://user-images.githubusercontent.com/1226920/235573909-1bce8c38-b7b8-4fd1-b06e-49ea90924ef7.png)

**Comment by Dylan-AWS** [comment]
Hi @darylteo thanks for reporting this we will address this in next release, for now you can run a build without specifying the php version and you will be able to use php 8.2 within the build.

**Comment by Dylan-AWS** [comment]
This issue is resolved, 8.2 is also supported in al2 5.0 #639
