### ISSUE TITLE
Local build log verbosity

### ISSUE THREAD

**Issue by jrowen** [aws/aws-codebuild-docker-images#62]
How can one control the logging verbosity for local builds?  Currently, only the `[Container]` messages are being shown, which makes it difficult to debug build issues.

**Comment by jamesh38** [comment]
Is there really no way for me to see whats going on when my build crashes? This becomes useless :( Have you figured anything out @jrowen ?

**Comment by StefanSmith** [comment]
Post-build, log can be read by executing `docker exec agentresources_build_1 cat /codebuild/output/log`

**Comment by la-jamesh** [comment]
@StefanSmith my hero.

**Comment by StefanSmith** [comment]
This also means you can watch the detailed build logs live with: `docker exec -it agentresources_build_1 tail -F /codebuild/output/log`

**Comment by subinataws** [comment]
Fixed with latest agent release. Get the latest version from DockerHub. docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false

SHA: 138c94d4663b9e813005d043e27004c5af189bf5903205444b2a431df3c1be1b
