### ISSUE TITLE
Add support for Nodejs v18 in AWS codebuild

### ISSUE THREAD

**Issue by adeel20202** [aws/aws-codebuild-docker-images#620]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add log output to help explain your problem.

**Platform (please complete the following information):**
 - OS: [e.g. Linux x86, Linux ARM, Mac x86, Mac M1, Windows]

**Additional context**

**Comment by subinataws** [comment]
Please track this request in https://github.com/aws/aws-codebuild-docker-images/issues/580. Resolving.
