### ISSUE TITLE
yarn missing from the aws/codebuild/standard:7.0 image

### ISSUE THREAD

**Issue by juliannicholson** [aws/aws-codebuild-docker-images#622]
The aws/codebuild/standard:6.0 image contained yarn. However the aws/codebuild/standard:7.0 does not. This is causing our codebuild's to fail as we rely on the yarn executable.

I can see lines in the aws/codebuild/standard:6.0 dockerfile installing yarn but these aren't in aws/codebuild/standard:7.0. Please could these lines be added back in so that the container image contains yarn.

**Comment by hoegertn** [comment]
Yes, this is a big breaking change and given that e.g. AWS CDK with projen uses yarn by default this is not a great idea.

**Comment by applerom** [comment]
The same (yarn is missing) is for `aws/codebuild/amazonlinux2-aarch64-standard:3.0`. It was in the previous version as well.

**Comment by ChronosMasterOfAllTime** [comment]
Yarn is also missing from the AL2 x86_64:5.0 repo. I manually had to copy the 4.0 yarn installation lines into our buildspec in order for it to work.

**Comment by ChronosMasterOfAllTime** [comment]
#657 Should resolve this.

**Comment by leoherran-aws** [comment]
Fixed in the latest release https://github.com/aws/aws-codebuild-docker-images/commit/3228c52ba08b814ed435c4f4a514513b72b0d03b#diff-c1ea454e65b48efad7d52406144e50f8459244517f0eb25a5ec3da4f865a3129

**Comment by ChronosMasterOfAllTime** [comment]
> Fixed in the latest release [3228c52#diff-c1ea454e65b48efad7d52406144e50f8459244517f0eb25a5ec3da4f865a3129](https://github.com/aws/aws-codebuild-docker-images/commit/3228c52ba08b814ed435c4f4a514513b72b0d03b#diff-c1ea454e65b48efad7d52406144e50f8459244517f0eb25a5ec3da4f865a3129)

@leoherran-aws my proposed solution in #657 is much simpler and doesn't require yum and/or GPG key pulls. It also is the recommended method to install per the [Yarn V1 docs](https://classic.yarnpkg.com/lang/en/docs/install).
