### ISSUE TITLE
Recent update to standard 7.0 image did not install latest ruby 3.2 

### ISSUE THREAD

**Issue by mfittko** [aws/aws-codebuild-docker-images#623]
I wonder how this could be missed, [ruby 3.2.2 already had been released on 30th of March](
https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-2-2-released/). Could you please update again? Meanwhile we'll be going down to 3.2.1 then.

https://github.com/aws/aws-codebuild-docker-images/blob/dbe76f895120fbe14a817df041dd3e21a737621f/ubuntu/standard/7.0/Dockerfile#L191

**Comment by subinataws** [comment]
CodeBuild image building process picks up the latest available patch version, when the release starts. It may not always be the latest, by the time the release completes. We'll get the patch version updated in an upcoming release, but you are welcome to try ruby 3.2.2 in the Amazon Linux Docker image https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/5.0/Dockerfile#L265.

**Comment by mfittko** [comment]
Cool, will wait for its release into CDK then, but happy to try amazon linux if it works. Guess we should just remove the ruby version from the Gemfile.
