### ISSUE TITLE
Feature request: Python 3.10 support For AL2 Images

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [aws/aws-codebuild-docker-images#633]
Hi Team,

Are there plans to add support for Python 3.10 in `Amazon Linux 2` images?

**Comment by subinataws** [comment]
CodeBuild images today only support the latest version for a language runtime. We have an open issue to support the every version that AWS Lambda supports. Let's track this ask in https://github.com/aws/aws-codebuild-docker-images/issues/608.
