### ISSUE TITLE
Question: Image used to build Android project 

### ISSUE THREAD

**Issue by Omar-Bishtawi** [aws/aws-codebuild-docker-images#669]
## Description
the `aws/codebuild/amazonlinux2-x86_64-standard:3.0` which is now deprecated used to have android-tools installed in it but as of `aws/codebuild/amazonlinux2-x86_64-standard:4.0` this support seems to be dropped. 

So I just want to confirm is there any alternative from codebuild-docker-images that is still supported and can be used to build android projects directly ? or is there any plan to support it in any image?

**Comment by niCSan** [comment]
You can try the Workaround on [this answer](https://github.com/aws/aws-codebuild-docker-images/issues/537#issuecomment-1209863613) with **aws/codebuild/standard:7.0** Image

**Comment by Omar-Bishtawi** [comment]
thanks for the recommendation @niCSan , I think it will work that way . 
Closing this issue as the other one has already answered the question and have similar context.
