### ISSUE TITLE
[Feature request] Ability to customise buildspec file name

### ISSUE THREAD

**Issue by BrianFarnhill** [aws/aws-codebuild-docker-images#67]
I had a look over this and couldn't see a way to do it right now, but it would be great if we could specify the name of the buildspec file as an environment variable as well when you call the build and pass the source and artifact paths. You can choose the filename in the CodeBuild UI so doing it locally would be a nice feature as well. Thanks!

**Comment by johnhanks1** [comment]
Thanks for the feedback, we will look into adding this as a feature request.

**Comment by subinataws** [comment]
This feature is now supported. Download the latest agent from DockerHub. docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false

SHA: 2fe3f77c8b580b82709e7f5f576313418eac2e5217a1da130ab1a8fb396f3ab2

**Comment by BrianFarnhill** [comment]
@subinataws Can we get the [instructions](https://github.com/aws/aws-codebuild-docker-images/blob/master/local_builds/README.md) updated with the extra parameter name now that this is supported?
