### ISSUE TITLE
Feature request: Python 3.12 support

### ISSUE THREAD

**Issue by michael-k** [aws/aws-codebuild-docker-images#677]
Please add support for Python 3.12 to the next `aws/codebuild/standard` image.

Python 3.12 was released on 2023-10-02, see
- https://pythoninsider.blogspot.com/2023/10/python-3120-final-now-available.html
- https://www.python.org/downloads/release/python-3120/

**Comment by Dylan-AWS** [comment]
We released Python 3.12 in the AL:5.0 image and Ubuntu 7.0 (https://github.com/aws/aws-codebuild-docker-images/pull/689).

**Comment by mdgm88** [comment]
Will aws-sam-cli be updated this month for the ARM image as well to support python 3.12? The one included in the image at the moment doesn't support python 3.11 let alone python 3.12.

**Comment by Dylan-AWS** [comment]
CodeBuild released Python 3.12 for ARM (#697)
