### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by yumo-mt** [aws/aws-codebuild-docker-images#678]
I need to deploy a front-end project on aws. In my front-end react project, pnpm is used to install the npm package, so I need a pnpm environment on aws, but the Docker image provided by CodeBuild on aws (aws/codebuild/amazonlinux2-x86_64 -standard:5.0) there is no pnpm environment, I need the pnpm environment. what should I do?

**Comment by subinataws** [comment]
@yumo-mt - As suggested by @mbacchi you can install any custom tooling in your buildspec. CodeBuild doesn't plan to include pnpm support in its managed images.
