### ISSUE TITLE
No longer able to use "n 18.16.0" in build using aws/codebuild/amazonlinux2-x86_64-standard:5.0

### ISSUE THREAD

**Issue by neueda-randerson** [aws/aws-codebuild-docker-images#682]
**Describe the bug**
Since the latest release we now get an error with aws/codebuild/amazonlinux2-x86_64-standard:5.0, whereby "n 18.16.0" no longer works

**To Reproduce**
Run the build.

Get this error:

[Container] 2023/11/14 12:35:59.822533 Running command node --version
 v18.18.2
  
 [Container] 2023/11/14 12:35:59.849093 Running command n 18.16.0
**/codebuild/output/tmp/script.sh: line 4: n: command not found**

**Expected behavior**
Node should switch to v18.16.0 as previously:

[Container] 2023/11/10 11:23:52.445996 Running command node --version
v18.16.0

[Container] 2023/11/10 11:23:52.456745 Running command n 18.16.0
     copying : node/18.16.0
   installed : v18.16.0 (with npm 9.5.1)

**Logs**
As above

**Platform (please complete the following information):**
 amazonlinux2-x86_64-standard:5.0
 
**Additional context**

**Comment by joshlang** [comment]
Unable to use `n 18` or `n 16` or any `n` command any longer.

It broke randomly without any changes yesterday.

Rerunning a previously succeeded pipeline now fails.

```
[Container] 2023/11/14 15:25:46.342564 Entering phase BUILD
--
32 | [Container] 2023/11/14 15:25:46.343123 Running command n 18
33 | /codebuild/output/tmp/script.sh: line 4: n: command not found
34 |  
35 | [Container] 2023/11/14 15:25:46.349184 Command did not exit successfully n 18 exit status 127
36 | [Container] 2023/11/14 15:25:46.353527 Phase complete: BUILD State: FAILED
```

**Comment by jamieavins** [comment]
We are in the same boat...

`<html>
<body>


[Container] 2023/11/14 15:16:10.200455 Running command n 18.16.0
--
24 | /codebuild/output/tmp/script.sh: line 4: n: command not found
25 |  
26 | [Container] 2023/11/14 15:16:10.282668 Command did not exit successfully n 18.16.0 exit status 127
27 | [Container] 2023/11/14 15:16:10.286950 Phase complete: INSTALL State: FAILED


</body>
</html>`

**Comment by jonnysooter** [comment]
This is an unexpected issue from CodeBuild and we are reverting the change that caused the issue.

**Comment by jonnysooter** [comment]
Thank you for opening this issue, it is resolved now. Please try running your builds again. 

![Screenshot 2023-11-14 at 9 24 39 AM](https://github.com/aws/aws-codebuild-docker-images/assets/1653474/080446f0-a759-4322-8994-f648e6f4bff3)

**Comment by tgpfeiffer** [comment]
Thanks for taking care of this, @jonnysooter

I am wondering,
- according to https://gallery.ecr.aws/codebuild/amazonlinux2-x86_64-standard the 5.0 image was released "11 days ago" (that would be 2023-11-04), why did this problem only appear in CodeBuild on 2023-11-14?
- as for @johan-sesaw, we worked around the problem yesterday by pinning the image version to 5.0-23.07.28, but honestly speaking it's a bit difficult to investigate/debug image versions if the latest version called 5.0 is a moving target and apparently there is no fixed tag for the latest version. For example, even after your fix, https://gallery.ecr.aws/codebuild/amazonlinux2-x86_64-standard still looks like
  ![image](https://github.com/aws/aws-codebuild-docker-images/assets/873082/ad880a2d-1c26-47bd-8758-50a07ab1d2e3)
  and it's hard to understand which "5.0" is the one with the defect, which "5.0" has the fix, and which of those "5.0"s is the one running in CodeBuild as "latest".

  Would it be possible to also give the latest version a tag and upload it to the public ECR and/or display the concrete version used as the latest one in CodeBuild? (Sorry, fairly unrelated to this repository.)

**Comment by jonnysooter** [comment]
We did not publish an image with this defect, so it's not available to use in ECR. The image versions you see listed are safe to use. The 5.0 image is our latest image and is defect free.

**Comment by kyptov** [comment]
2 days ago my pipelines started to fail.
No updates, no issues. It was very strange. I added `npm install -g n` to solve the issue.
Yesterday it started to fail again. Found this issue, reverted all buildspecs.

The question is, where I can view releases or updates?
