### ISSUE TITLE
support dotnet version 8

### ISSUE THREAD

**Issue by emilianoangieri** [aws/aws-codebuild-docker-images#685]
**Describe the bug**
At the moment reading the official AWS docs seems not present a CodeBuild image for linux or ubuntu that support .dotnet version 8.
https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html

**Platform (please complete the following information):**
 - OS: [e.g. Linux x86, Linux ARM]

**Comment by Dylan-AWS** [comment]
We released .NET 8.0 in the AL:5.0 image and Ubuntu 7.0 (https://github.com/aws/aws-codebuild-docker-images/pull/689).

**Comment by Dylan-AWS** [comment]
CodeBuild released .NET 8.0 for ARM (#697)
