### ISSUE TITLE
SBT build and sbt docker:publishLocal

### ISSUE THREAD

**Issue by psriramula** [aws/aws-codebuild-docker-images#69]
Hi, I am working on this problem of building Docker images using sbt feature to generate docker images and content  (i.e sbt docker:publishLocal ) for a while now. 

This feature would make all Scala Play based micro services to be deployed on to ECS quite easily. 

Ideally following steps from a Scala SBT based builds 

sbt clean compile test
sbt docker:publishLocal

And later pipeline or something can generate docker images from resulting <app>/target/docker/stage    folder

**Comment by subinataws** [comment]
@psriramula - What's the ask here? Are you reporting an issue? Requesting a feature? 

I believe we have sbt in openjdk-9 image @ https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/java/openjdk-9/Dockerfile and you can enable privileged mode in any build container.

**Comment by clareliguori** [comment]
Hi @psriramula, have you tried enabling the "privileged" attribute in your CodeBuild project?  Docker is only able to start in CodeBuild if that flag is enabled.
