### ISSUE TITLE
Add support for Node 20 in ARM images

### ISSUE THREAD

**Issue by wilhen01** [aws/aws-codebuild-docker-images#691]
#631 has now been closed via #689 but that didn't cover adding Node 20 support to the ARM images. Can someone do this please? We've migrated all of our estate to run on ARM, so we need support in the ARM images before we can upgrade.

**Comment by wilhen01** [comment]
Docs [here](https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html) suggest that there are `standard:nodejs20` runtimes available but I can't see those images in the repo?

**Comment by subinataws** [comment]
Arm images should get the update in early Jan. Reopened https://github.com/aws/aws-codebuild-docker-images/issues/631 to track in a single place. Resolving this issue instead. Apologies for the confusion.
