### ISSUE TITLE
PHP 8.3 Support

### ISSUE THREAD

**Issue by sukh-idgateway** [aws/aws-codebuild-docker-images#692]
Hi,

Are there any plans to support PHP 8.3 as part of the standard codebuild image?

Thanks

**Comment by Dylan-AWS** [comment]
PHP 8.3 is now available on the aarch64 image. #697

**Comment by sukh-idgateway** [comment]
Thanks @Dylan-AWS 

Do you know if the Ubuntu 22.04 image will support 8.3?

**Comment by raymonsupportbook** [comment]
I created a pull request for this: #714

**Comment by subinataws** [comment]
Added in the latest release for Ubuntu 7.0 image: https://github.com/aws/aws-codebuild-docker-images/releases/tag/24.04.10.
