### ISSUE TITLE
Local CodeBuild environment variables

### ISSUE THREAD

**Issue by StefanSmith** [aws/aws-codebuild-docker-images#70]
Is it possible to pass environment variables to the build container from the command line? This would be really useful to replicate passing environment variables via CodeBuild/CodePipeline configuration, rather than hard-coding into buildspec.yml

**Comment by subinataws** [comment]
We are only planning to support environment variables through buildspec.yml file, at this time. However, we are considering how best to pass aws creds to the local agent.

We added support to specify a buildspec file with the latest update "docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false".  

Command:
docker run -it -v /var/run/docker.sock/var/run/docker.sock -e "IMAGE_NAME=<Build image>" -e "ARTIFACTS=<Absolute path to your artifact output folder>" -e "SOURCE=<Absolute path to your source directory>" -e "BUILDSPEC=<Relative path to your buildspec override> amazon/aws-codebuild-local

**Comment by rayj-pgi** [comment]
This would be nice. I just temporarily added the ENV vars to the buildspec.yml to get going.

**Comment by rey-dx** [comment]
Is it solved now?
