### ISSUE TITLE
Add browsers to aws/codebuild/standard:7.0

### ISSUE THREAD

**Issue by rforster-dev** [aws/aws-codebuild-docker-images#704]
**Describe the bug**
aws/codebuild/standard:7.0 does not have any browsers pre-installed, it would be useful to have at least Chrome pre-installed for when CodeBuild is being used for selenium tests.

**To Reproduce**
Steps to reproduce the behaviuor:
1. Run Selenium tests on a aws/codebuild/standard:7.0 image

**Expected behavior**
Chrome binary should launch

**Platform (please complete the following information):**
- aws/codebuild/standard:7.0

**Additional context**
I can see previous images - https://github.com/aws/aws-codebuild-docker-images/blob/9dacbd58d0f46b6e6a179a48c1edffecd94abb05/ubuntu/standard/5.0/Dockerfile#L78 - have it installed? So curious to understand why it isn't on newer images.

**Comment by subinataws** [comment]
Lets track in https://github.com/aws/aws-codebuild-docker-images/issues/562
