### ISSUE TITLE
Add support for Node 21 

### ISSUE THREAD

**Issue by aliosmanmenekse** [aws/aws-codebuild-docker-images#708]
Hello there 👋 ,

Now that Node 21 is available (https://nodejs.org/en/), can we add support for Node 21 as a supported runtime on CodeBuild?

Thanks heaps.

**Comment by subinataws** [comment]
Thanks for the suggestion. CodeBuild unfortunately will only be adding support for LTS versions of the runtime. Version 21 is not an LTS and will go out of support shortly. You may consider using a custom image for nodejs 21. Resolving.
