### ISSUE TITLE
Feature Request: `dotnet8` Lambda compute image

### ISSUE THREAD

**Issue by skirk-mpr** [aws/aws-codebuild-docker-images#713]
**Describe the feature request**

We put in a ticket with AWS Support for a feature request and they recommend we add an issue here.  We are hoping to leverage the new AWS Lambda Compute option for some CodeBuild projects - which is extremely cool and extremely fast 🚀 !   However, since AWS Lambda added .NET 8 as a support managed runtime, we've upgraded _most_ of our apps to target .NET 8.  Looks like currently there is only a .NET 6 image which won't allow us to build .NET 8 apps, so we would love to have an officially provided .NET 8.  Thanks!

**Comment by LZY7977** [comment]
.NET8 Lambda compute image is now available on CodeBuild
