### ISSUE TITLE
Using local AWS credentials for Local CodeBuild

### ISSUE THREAD

**Issue by jakebenn** [aws/aws-codebuild-docker-images#72]
Is it possible to pass through local AWS credentials (e.g. from ~/.aws) to the build container when running CodeBuild locally? This would be ideal when making AWS CLI calls in buildspec.yml. Otherwise, it's not clear how to pass through an ACCESS_KEY_ID and SECRET_ACCESS_KEY to the build container.

**Comment by heitorlessa** [comment]
@subinataws just bumped this same issue here too - Tried mounting my `~/.aws` as a Docker volume for the build environment or passing environment variables and they don't get passed through when the local agent runs the docker container using IMAGE_NAME.

This reads as a feature request here and would be very useful as most of the builds use AWS CLI - Happy to write a quick proposal

**Comment by cm-wada-yusuke** [comment]
+1 
I found that environment variable can be passed using `codebuild_build.sh`, I tried it like this:
 
```env.txt
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=xxx
AWS_SESSION_TOKEN=xxx
AWS_DEFAULT_REGION=ap-northeast-1
AWS_DEFAULT_OUTPUT=json
```

```
./codebuild_build.sh \ 
-i aws/codebuild/python:3.6.5 \
-a ./artifacts \
-e ./env.txt
```

However, it did not work. In `buildspec.yml`, I simply set the environment variable from the parameter store, but the output is error status:

```
agent_1 | [Container] 2018/06/18 07: 51: 07 Waiting for agent ping
agent_1 | [Container] 2018/06/18 07: 51: 07 Waiting for DOWNLOAD_SOURCE
agent_1 | [Container] 2018/06/18 07: 51: 21 Phase is DOWNLOAD_SOURCE
agent_1 | [Container] 2018/06/18 07: 51: 22 CODEBUILD_SRC_DIR = / codebuild / output / src204298312 / src
agent_1 | [Container] 2018/06/18 07: 51: 22 YAML location is / codebuild / output / src204298312 / src / baselspec.yml
agent_1 | [Container] 2018/06/18 07: 51: 22 Processing environment variables
agent_1 | [Container] 2018/06/18 07: 51: 22 Decrypting parameter store environment variables
agent_1 | [Container] 2018/06/18 07:51:22 Phase complete: DOWNLOAD_SOURCE Success: false
agent_1 | [Container] 2018/06/18 07: 51: 22 Phase context status code: Decrypted Variables Error Message: Missing Region: could not find region configuration
agent_1 | [Container] 2018/06/18 07: 51: 22 Runtime error (* awserr.baseError: MissingRegion: could not find region configuration)
```

**Comment by AWSstangers** [comment]
The latest release of the local agent solves this issue. Please download the latest image from [dockerhub](https://hub.docker.com/r/amazon/aws-codebuild-local/) along with the updated wrapper [script](https://github.com/aws/aws-codebuild-docker-images/blob/master/local_builds/codebuild_build.sh).

**Comment by lockenj** [comment]
@AWSstangers this doesn't seem to work for me...
I ran: 

`docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false`
`docker build -t aws/codebuild/noaws/codebuild/nodejs:8.11.0`
`./codebuild_build.sh -i aws/codebuild/noaws/codebuild/nodejs:8.11.0 -a dist-codebuild -c`
also tried
`./codebuild_build.sh -i aws/codebuild/noaws/codebuild/nodejs:8.11.0 -a dist-codebuild -e codebuild.env`
where codebuild.env had `AWS_ACCESS_KEY_ID` `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION` all set

Any info/help would be huge thanks!

**Comment by lockenj** [comment]
@jakebenn I got further this time I am getting stuck on this error
`Phase context status code: Decrypted Variables Error Message: parameter does not exist: coin-cobo-srfr-slack-incoming-web-hook`

using `aws ssm get-parameter --name coin-cobo-srfr-slack-incoming-web-hook --with-decryption` from my local host machine it works fine. Any thoughts?

**Comment by hsiddhu2** [comment]
Thank you @jakebenn, The command that you gave worked fine for me. Seems like mentioning ".env" makes it look for a local evn file. I see this error but it is because it's looking at the file first here -  /LocalBuild/envFile/.env
[Environment Variables] Couldn't open specified environment variable file: open /LocalBuild/envFile/.env: no such file or directory
