### ISSUE TITLE
Add `setfacl` tool

### ISSUE THREAD

**Issue by moltar** [aws/aws-codebuild-docker-images#722]
This tool is used by `projen` to set permissions, which is a very common tool used by AWS and AWS CDK-related projects.

https://github.com/projen/projen/blob/64206de9dbe4e492cb3e6c17d5b02fda6a204d5d/src/build/build-workflow.ts#L272

But it doesn't seem to be included in the default CodeBuild images.

**Comment by leoherran-aws** [comment]
added in https://github.com/aws/aws-codebuild-docker-images/commit/1bd6ad2e247b957c8597fc31e172e3d2df185a19
