### ISSUE TITLE
AWS git-credential-helper is not compatible with git 2.46.0 (aws/codebuild/standard:5.0)

### ISSUE THREAD

**Issue by ikfid** [aws/aws-codebuild-docker-images#731]
It seems that git was recently updated from 2.45.0 to 2.46.0.
git 2.46.0 sends more lines to AWS CodeBuild git-credential-helper than it used to, and git-credential-helper fails.
https://git-scm.com/docs/git-credential/2.46.0 - see 'capability' section.

the input sent by new git (as traced using CodeBuild Debug):
```
capability[]=authtype
capability[]=state
protocol=https
host=github.com
wwwauth[]=Basic realm="GitHub"
```

observer error message in the logs:
`duplicate key: capability[] [authtype, state]`

**To Reproduce**
1. setup a CodeBuild job with aws/codebuild/standard:5.0, 'github.com' with some private repository and Personal Access Token
3. in the build template enable git-credential-helper and set one of the commands to 'git remote update'
```
env:
  git-credential-helper: yes

phases:
  build:
    commands:
      - git remote update
```

4. Start build
5. Check the logs

**Expected behavior**
no issues when executing 'git remote update'

** Work Around **
before 'git remote update' in the template execute the following command:
git config --global --replace-all credential.helper "$(pwd)/fix-credential-helper.sh"

where fix-credential-helper.sh content is:
```
#!/bin/sh
awk '{if (!match($0, "capability")) print $0}' | /codebuild/readonly/git-credential-helper "$@"
```

this would call the original AWS git-credential-helper with filtered out 'capability' lines from stdin.

**Comment by awszhen** [comment]
Thanks for reporting this issue. We have deployed a change to address this issue. Please try again, thanks.
