### ISSUE TITLE
Install gh command on images

### ISSUE THREAD

**Issue by ajkerr** [aws/aws-codebuild-docker-images#732]
Many of our self-hosted GitHub workflows that we run on CodeBuild require the [gh](https://cli.github.com/) command from GitHub.

It would be great if the images came with this preinstalled, like they do with git, so we don't need to waste time installing it with apt-get or yum.

**Comment by subinataws** [comment]
Added in latest images: 

https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/7.0/Dockerfile#L178
https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/5.0/Dockerfile#L160
