### ISSUE TITLE
Update sam to version 1.130.0

### ISSUE THREAD

**Issue by bs-dl1-baichen** [aws/aws-codebuild-docker-images#748]
**Describe the bug**
Node.js 22 has been released on AWS. It requires SAM version [1.130.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.130.0). However, the SAM CLI in amazonlinux2-x86_64-standard:5.0 only supports up to version 1.126.0, which causes the Node.js 22 code to fail to compile.

**To Reproduce**

**Expected behavior**
sam --version
1.130.0+

**Logs**

**Additional context**

**Comment by mdgm88** [comment]
There is a workaround that you can use to update aws-sam-cli, but not ideal as it means extra build time:
https://github.com/aws/aws-codebuild-docker-images/issues/662

**Comment by bs-dl1-baichen** [comment]
amazonlinux2-x86_64-standard:5.0 has been upgrade sam ver to 1.131.0 ~

**Comment by perrin4869** [comment]
I haven't checked the `x86_64` image, but the arm image `amazonlinux2-aarch64-standard:3.0` is still using `1.126.0`...

**Comment by mdgm88** [comment]
@perrin4869 can you check again? Unlike last week, I didn't get a log entry about there being a newer version of aws-sam-cli when I did a build of an aarch64 codebuild project today.

**Comment by perrin4869** [comment]
oh nice, just checked and it seems to have been updated! Thanks!
