### ISSUE TITLE
unbunto/docker/1.12.1 error - "SECONDS: not found"

### ISSUE THREAD

**Issue by revof11** [aws/aws-codebuild-docker-images#8]
Trying to run **ubuntu/docker/1.12.1/Dockerfile** without any alterations, I am seeing this error:

> /usr/local/bin/dockerd-entrypoint.sh: 12: /usr/local/bin/dockerd-entrypoint.sh: SECONDS: not found

Tried adding an environment variable for _SECONDS_ with no luck.

**Tried:**
`docker run <IMAGE_ID>`

**Also tried with cap-add to avoid mount issues:**
`docker run --cap-add=SYS_ADMIN <IMAGE_ID>`

Suggestions?  Errors?

**Comment by subinataws** [comment]
Suggestion: Enable privileged parameter for local run.

Nice write up here: https://medium.com/@coderhound/using-aws-codebuild-for-java-docker-project-24a139c8b3e9

**Comment by clareliguori** [comment]
Thanks for reporting this!  I have pushed our latest set of images, where this is fixed.
