### ISSUE TITLE
Install SSH client

### ISSUE THREAD

**Issue by aniketbhatnagar** [aws/aws-codebuild-docker-images#82]
Currently, SSH client is not installed in the image which makes cloning github repos (especially submodules) difficult using deploy keys (https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys). It would be great to have the SSH client pre-installed in the build image.

**Comment by clareliguori** [comment]
Fixed in 3287e7ed206895d6695a64fa0af17618fa8a905a
