### ISSUE TITLE
Docker 17 image can't be built (inconsistent dependencies)

### ISSUE THREAD

**Issue by talolard** [aws/aws-codebuild-docker-images#87]
Hi,
When building the docker 17 image I get the error message
` libpq-dev : Depends: libpq5 (= 9.3.22-0ubuntu0.14.04) but 9.3.23-0ubuntu0.14.04 is to be installed`
Modifying  line 23 in the Dockerfile from
`libpq-dev=9.3.22-` 
to
`libpq-dev=9.3.23-`
Solved this for me. I'd submit a PR but this seems to just defer the problem rather than solve it. 
Cheers

**Comment by johnhanks1** [comment]
Fix: https://github.com/aws/aws-codebuild-docker-images/commit/3036c2749dd4fa064685dfd9367b6dcfbdfbb249
