### ISSUE TITLE
xsltproc no longer available on aws/codebuild/python:2.7.12 

### ISSUE THREAD

**Issue by radix** [aws/aws-codebuild-docker-images#88]
I believe something changed recently with the docker images that made the `xsltproc` command disappear from my build environment. It seems to have disappeared between 7:41:50 PM and 8:41:52 PM UTC on June 13th, 2018, according to my AWS CodeBuild logs.

**Comment by radix** [comment]
on top of that, for some reason adding `apt-get install -y xsltproc` is not working to install the project, despite the fact that [it is contained in ubuntu 14.04 Trusty Tahr](https://packages.ubuntu.com/trusty/xsltproc). So I'm not really sure what's going on...

**Comment by clareliguori** [comment]
We're looking into what change caused this package to be removed.  In the meantime, you will need to do an "apt-get update" before any "apt-get install" in order to get the package list in your build.

**Comment by radix** [comment]
thank you @clareliguori, the `apt-get update` solved that problem.

**Comment by clareliguori** [comment]
Fixed in 3287e7ed206895d6695a64fa0af17618fa8a905a
