### ISSUE TITLE
Can't pip install pymssql or pip install pyodbc in python 3.6 docker

### ISSUE THREAD

**Issue by OtisHarrison24** [aws/aws-codebuild-docker-images#90]
Below is the error I am getting every time i pip install pymssql. Getting pretty much the same for pyodbc

Installing collected packages: pymssql
  Running setup.py install for pymssql: started
    Running setup.py install for pymssql: finished with status 'error'
    Complete output from command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ubxvkcv8/pymssql/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_5nse9t6/install-record.txt --single-version-externally-managed --compile:
    setup.py: platform.system() => 'Linux'
    setup.py: platform.architecture() => ('64bit', 'ELF')
    setup.py: platform.linux_distribution() => ('debian', 'jessie/sid', '')
    setup.py: platform.libc_ver() => ('glibc', '2.3.4')
    setup.py: Not using bundled FreeTDS
    setup.py: include_dirs = ['/usr/local/include']
    setup.py: library_dirs = ['/usr/local/lib']
    running install
    running build
    running build_ext
    building '_mssql' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/local/include/python3.6m -c _mssql.c -o build/temp.linux-x86_64-3.6/_mssql.o -DMSDBLIB
    _mssql.c:266:22: fatal error: sqlfront.h: No such file or directory
     #include "sqlfront.h"
                          ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ubxvkcv8/pymssql/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_5nse9t6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ubxvkcv8/pymssql/

**Comment by clareliguori** [comment]
Based on the error message you're getting, it sounds like you need to install FreeTDS before pip installing pymssql.
`apt-get update && apt-get install freetds-dev`
