### ISSUE TITLE
Version '1:2.17.1*' for 'git' was not found

### ISSUE THREAD

**Issue by djamison** [aws/aws-codebuild-docker-images#93]
Commit 3036c2749dd4fa064685dfd9367b6dcfbdfbb249 added a dependence on git 2.17.1, but it appears that that version has been unpublished from the [PPA](https://launchpad.net/~git-core/+archive/ubuntu/ppa) where it used to be found. I'm trying to build docker/17.09.0 in particular, which produces this error:

```
E: Version '1:2.17.1*' for 'git' was not found
The command '/bin/sh -c set -ex     && apt-get update     && apt-get install software-properties-common -y --no-install-recommends    && apt-add-repository ppa:git-core/ppa     && apt-get update     && apt-get install git=1:2.17.1* -y --no-install-recommends    && git version' returned a non-zero code: 100
```

**Comment by omar-nahhas** [comment]
I cannot build the image ether

**Comment by subinataws** [comment]
Thanks for reporting this issue. Fixed with https://github.com/aws/aws-codebuild-docker-images/commit/7fe7ca62b578df60764471b8bb94022e7e0a2eaa
